window.loadedQuestions = [
    { word: "Apa Makna dari 'Look up'", arti: "Mencari informasi di buku, internet, atau sumber lainnya" },
    { word: "Apa Makna dari 'Turn off'", arti: "Mematikan suatu perangkat atau lampu" },
    { word: "Apa Makna dari 'Give in'", arti: "Menyerah dalam suatu argumen atau situasi" },
    { word: "Apa Makna dari 'Run out'", arti: "Kehabisan atau kehabisan sesuatu" },
    { word: "Apa Makna dari 'Take off'", arti: "Melepas pakaian atau pesawat terbang" },
    { word: "Apa Makna dari 'Bring up'", arti: "Membahas suatu topik atau membesarkan anak" },
    { word: "Apa Makna dari 'Set up'", arti: "Mendirikan atau menyusun sesuatu" },
    { word: "Apa Makna dari 'Break down'", arti: "Mengalami kerusakan atau kegagalan" },
    { word: "Apa Makna dari 'Call off'", arti: "Membatalkan suatu acara atau pertemuan" },
    { word: "Apa Makna dari 'Go on'", arti: "Melanjutkan atau terus berlangsung" },
    { word: "Apa Makna dari 'Put off'", arti: "Menunda suatu kegiatan atau rencana" },
    { word: "Apa Makna dari 'Bring in'", arti: "Memperkenalkan atau membawa sesuatu ke dalam" },
    { word: "Apa Makna dari 'Look after'", arti: "Menjaga atau merawat sesuatu atau seseorang" },
    { word: "Apa Makna dari 'Turn on'", arti: "Menghidupkan suatu perangkat atau lampu" },
    { word: "Apa Makna dari 'Break up'", arti: "Mengakhiri hubungan atau memecah menjadi bagian-bagian" },
    { word: "Apa Makna dari 'Get up'", arti: "Bangun dari tidur atau berdiri" },
    { word: "Apa Makna dari 'Give up'", arti: "Menyerah atau berhenti mencoba" },
    { word: "Apa Makna dari 'Run into'", arti: "Bertemu secara kebetulan" },
    { word: "Apa Makna dari 'Take up'", arti: "Memulai atau mengambil hobi atau aktivitas baru" },
    { word: "Apa Makna dari 'Bring out'", arti: "Menerbitkan atau memperkenalkan sesuatu ke publik" },
    { word: "Apa Makna dari 'Settle down'", arti: "Menetap atau meredakan" },
    { word: "Apa Makna dari 'Break out'", arti: "Meletus atau mulai secara tiba-tiba" },
    { word: "Apa Makna dari 'Call up'", arti: "Menghubungi seseorang melalui telepon" },
    { word: "Apa Makna dari 'Go over'", arti: "Meninjau atau melewati suatu materi" },
    { word: "Apa Makna dari 'Put on'", arti: "Memakai pakaian atau menyalakan suatu perangkat" },
    { word: "Apa Makna dari 'Bring back'", arti: "Mengembalikan atau memulihkan sesuatu" },
    { word: "Apa Makna dari 'Look for'", arti: "Mencari sesuatu atau seseorang" },
    { word: "Apa Makna dari 'Turn around'", arti: "Berbalik atau mengubah arah" },
    { word: "Apa Makna dari 'Check out'", arti: "Mengecek atau memeriksa sesuatu" },
    { word: "Apa Makna dari 'Get in'", arti: "Masuk ke dalam suatu tempat atau kendaraan" },
];