window.loadedQuestions = [
  { word: "He …. run fast.", arti: "could" },
  { word: "You ….. wear a helmet.", arti: "must" },
  { word: "….. I borrow your pen?", arti: "May" },
  { word: "She ….. swim very well.", arti: "can" },
  { word: "They ….. be at home now.", arti: "might" },
  { word: "We ….. start now?", arti: "Shall" },
  { word: "You ….. listen to your parents.", arti: "should" },
  { word: "I ….. help you with your homework tomorrow.", arti: "will" },
  { word: "He ….. like some tea?", arti: "Would" },
  { word: "You ….. come in now.", arti: "may" },
  { word: "She ….. play the piano when she was five.", arti: "could" },
  { word: "You ….. not smoke here.", arti: "must" },
  { word: "….. I help you with that?", arti: "May" },
  { word: "He ….. arrive late due to traffic.", arti: "might" },
  { word: "….. we go out now?", arti: "Shall" },
  { word: "You ….. see a dentist about that tooth.", arti: "should" },
  { word: "I ….. be able to finish it tonight.", arti: "might" },
  { word: "You ….. turn off the light when you leave.", arti: "must" },
  { word: "….. you lend me some money?", arti: "Could" },
  { word: "She ….. be the one who called you.", arti: "might" },
  { word: "He ….. not be at the office now.", arti: "may" },
  { word: "We ….. not agree with that idea.", arti: "might" },
  { word: "You ….. not forget your homework.", arti: "must" },
  { word: "They ….. finish the project on time.", arti: "can" },
  { word: "She ….. be sleeping right now.", arti: "might" },
  { word: "I ….. go if I had time.", arti: "would" },
  { word: "You ….. not speak loudly in the library.", arti: "should" },
  { word: "….. I see your ID, please?", arti: "May" },
  { word: "He ….. know the answer already.", arti: "may" },
  { word: "They ….. like to join us later.", arti: "might" },
  { word: "You ….. take this medicine after meals.", arti: "must" },
  { word: "She ….. have helped us if we had asked.", arti: "would" },
  { word: "I ….. speak three languages.", arti: "can" },
  { word: "….. you help me carry this box?", arti: "Can" },
  { word: "They ….. not attend the meeting.", arti: "might" },
  { word: "We ….. meet again someday.", arti: "will" },
  { word: "You ….. have called me earlier.", arti: "should" },
  { word: "….. I open the window?", arti: "Shall" },
  { word: "He ….. not understand what you're saying.", arti: "may" },
  { word: "She ….. be angry if you’re late.", arti: "might" },
  { word: "You ….. not park here.", arti: "must" },
  { word: "He ….. join us for dinner.", arti: "will" },
  { word: "I ….. always help my friends.", arti: "will" },
  { word: "….. you like some coffee?", arti: "Would" },
  { word: "They ….. go to the beach tomorrow.", arti: "may" },
  { word: "You ….. apologize for being rude.", arti: "should" },
  { word: "He ….. play football before he got injured.", arti: "could" },
  { word: "We ….. meet after work.", arti: "shall" },
  { word: "She ….. always be trusted.", arti: "can" },
  { word: "You ….. be more careful next time.", arti: "should" }
];
