window.loadedQuestions = [
  { word: "You ….. ask the teacher for help.", arti: "can" },
  { word: "He ….. be sleeping now.", arti: "might" },
  { word: "….. we start the meeting?", arti: "Shall" },
  { word: "They ….. bring their own drinks.", arti: "should" },
  { word: "I ….. go to the party if I finish early.", arti: "will" },
  { word: "….. I leave early today?", arti: "May" },
  { word: "She ….. solve the problem alone.", arti: "can" },
  { word: "He ….. have told you the truth.", arti: "might" },
  { word: "You ….. not speak during the test.", arti: "must" },
  { word: "I ….. visit my grandmother this weekend.", arti: "will" },
  { word: "They ….. not like the news.", arti: "might" },
  { word: "She ….. not be able to come.", arti: "may" },
  { word: "You ….. help the elderly cross the street.", arti: "should" },
  { word: "….. I take your order?", arti: "May" },
  { word: "He ….. win if he tries harder.", arti: "could" },
  { word: "I ….. not agree more with your idea.", arti: "could" },
  { word: "….. you close the window, please?", arti: "Could" },
  { word: "We ….. not be late for the train.", arti: "must" },
  { word: "They ….. go hiking if the weather is good.", arti: "might" },
  { word: "She ….. not believe what she saw.", arti: "could" },
  { word: "You ….. tell the truth.", arti: "must" },
  { word: "I ….. bake a cake for your birthday.", arti: "will" },
  { word: "….. we continue tomorrow?", arti: "Shall" },
  { word: "He ….. come back later.", arti: "may" },
  { word: "You ….. leave your bag here.", arti: "can" },
  { word: "She ….. study harder to pass.", arti: "should" },
  { word: "….. I go to the restroom?", arti: "May" },
  { word: "He ….. see her from a distance.", arti: "could" },
  { word: "We ….. always count on you.", arti: "can" },
  { word: "You ….. say that to your parents.", arti: "should" },
  { word: "They ….. know what happened.", arti: "might" },
  { word: "I ….. help you with your luggage.", arti: "can" },
  { word: "She ….. need more time to think.", arti: "may" },
  { word: "You ….. be proud of yourself.", arti: "should" },
  { word: "….. you wait for a moment?", arti: "Could" },
  { word: "I ….. prefer to stay at home.", arti: "would" },
  { word: "They ….. not want to join us.", arti: "might" },
  { word: "He ….. be busy now.", arti: "may" },
  { word: "You ….. turn in your assignment tomorrow.", arti: "can" },
  { word: "We ….. call him later.", arti: "will" },
  { word: "….. I join the game?", arti: "May" },
  { word: "She ….. be the right person for the job.", arti: "might" },
  { word: "You ….. finish before the deadline.", arti: "must" },
  { word: "I ….. not be available next week.", arti: "may" },
  { word: "He ….. have forgotten the appointment.", arti: "might" },
  { word: "….. we go together?", arti: "Shall" },
  { word: "They ….. accept our invitation.", arti: "could" },
  { word: "You ….. show more respect.", arti: "should" },
  { word: "She ….. travel to Japan next year.", arti: "will" }
];
