window.loadedQuestions = [
  { word: "He ….. lift the box alone.", arti: "can" },
  { word: "You ….. not enter without a ticket.", arti: "must" },
  { word: "….. I turn off the lights?", arti: "Shall" },
  { word: "They ….. be waiting outside.", arti: "might" },
  { word: "We ….. help the poor.", arti: "should" },
  { word: "She ….. already know the answer.", arti: "may" },
  { word: "I ….. go now, it's getting late.", arti: "must" },
  { word: "….. you like to join us for lunch?", arti: "Would" },
  { word: "He ….. reach the top easily.", arti: "can" },
  { word: "You ….. not shout at your sister.", arti: "should" },
  { word: "….. I carry your bag?", arti: "May" },
  { word: "They ….. try harder next time.", arti: "should" },
  { word: "She ….. finish her work early.", arti: "might" },
  { word: "We ….. go to the beach if it's sunny.", arti: "could" },
  { word: "He ….. not hear the phone ring.", arti: "may" },
  { word: "You ….. save your money wisely.", arti: "should" },
  { word: "….. I stay here for a while?", arti: "May" },
  { word: "She ….. become a great doctor someday.", arti: "will" },
  { word: "I ….. call you later tonight.", arti: "will" },
  { word: "They ….. be busy with their assignments.", arti: "might" },
  { word: "You ….. bring an umbrella today.", arti: "should" },
  { word: "He ….. play the guitar well.", arti: "can" },
  { word: "….. we invite him to the event?", arti: "Shall" },
  { word: "She ….. get hurt if she runs too fast.", arti: "might" },
  { word: "I ….. not go if it's raining.", arti: "will" },
  { word: "You ….. call the doctor immediately.", arti: "must" },
  { word: "He ….. have taken the wrong turn.", arti: "might" },
  { word: "….. you open the door, please?", arti: "Could" },
  { word: "We ….. not allow such behavior.", arti: "must" },
  { word: "I ….. not remember his name.", arti: "may" },
  { word: "You ….. be quiet during the performance.", arti: "must" },
  { word: "She ….. drive when she was 16.", arti: "could" },
  { word: "….. I speak to your manager?", arti: "May" },
  { word: "He ….. like to join the team.", arti: "would" },
  { word: "They ….. not know about the meeting.", arti: "might" },
  { word: "We ….. be friends again someday.", arti: "might" },
  { word: "I ….. eat something soon, I’m hungry.", arti: "must" },
  { word: "….. you help me find my phone?", arti: "Could" },
  { word: "She ….. apologize for her mistake.", arti: "should" },
  { word: "You ….. not use your phone here.", arti: "must" },
  { word: "They ….. go to school by bike.", arti: "can" },
  { word: "….. I take a break now?", arti: "May" },
  { word: "He ….. not understand the instructions.", arti: "may" },
  { word: "She ….. be at the airport by now.", arti: "might" },
  { word: "We ….. bring snacks for everyone.", arti: "should" },
  { word: "I ….. never forget this moment.", arti: "will" },
  { word: "You ….. always be polite.", arti: "should" },
  { word: "….. we go shopping this afternoon?", arti: "Shall" },
  { word: "He ….. explain it again if needed.", arti: "can" }
];
