window.loadedQuestions = [
  { Soal: "0:00", British: "midnight", American: "twelve AM" },
  { Soal: "1:00", British: "one in the morning", American: "one AM" },
  { Soal: "2:00", British: "two in the morning", American: "two AM" },
  { Soal: "3:00", British: "three in the morning", American: "three AM" },
  { Soal: "4:00", British: "four in the morning", American: "four AM" },
  { Soal: "5:00", British: "five in the morning", American: "five AM" },
  { Soal: "6:00", British: "six in the morning", American: "six AM" },
  { Soal: "7:00", British: "seven in the morning", American: "seven AM" },
  { Soal: "8:00", British: "eight in the morning", American: "eight AM" },
  { Soal: "9:00", British: "nine in the morning", American: "nine AM" },
  { Soal: "10:00", British: "ten in the morning", American: "ten AM" },
  { Soal: "11:00", British: "eleven in the morning", American: "eleven AM" },
  { Soal: "12:00", British: "noon", American: "twelve PM" },
  { Soal: "13:00", British: "one in the afternoon", American: "one PM" },
  { Soal: "14:00", British: "two in the afternoon", American: "two PM" },
  { Soal: "15:00", British: "three in the afternoon", American: "three PM" },
  { Soal: "16:00", British: "four in the afternoon", American: "four PM" },
  { Soal: "17:00", British: "five in the afternoon", American: "five PM" },
  { Soal: "18:00", British: "six in the evening", American: "six PM" },
  { Soal: "19:00", British: "seven in the evening", American: "seven PM" },
  { Soal: "20:00", British: "eight in the evening", American: "eight PM" },
  { Soal: "21:00", British: "nine in the evening", American: "nine PM" },
  { Soal: "22:00", British: "ten at night", American: "ten PM" },
  { Soal: "23:00", British: "eleven at night", American: "eleven PM" },
  { Soal: "0:30", British: "half past midnight", American: "twelve thirty AM" },
  { Soal: "6:30", British: "half past six in the morning", American: "six thirty AM" },
  { Soal: "9:30", British: "half past nine in the morning", American: "nine thirty AM" },
  { Soal: "11:30", British: "half past eleven in the morning", American: "eleven thirty AM" },
  { Soal: "12:30", British: "half past twelve", American: "twelve thirty PM" },
  { Soal: "13:30", British: "half past one in the afternoon", American: "one thirty PM" },
  { Soal: "14:30", British: "half past two in the afternoon", American: "two thirty PM" },
  { Soal: "15:30", British: "half past three in the afternoon", American: "three thirty PM" },
  { Soal: "16:30", British: "half past four in the afternoon", American: "four thirty PM" },
  { Soal: "17:30", British: "half past five in the afternoon", American: "five thirty PM" },
  { Soal: "18:30", British: "half past six in the evening", American: "six thirty PM" },
  { Soal: "19:30", British: "half past seven in the evening", American: "seven thirty PM" },
  { Soal: "20:30", British: "half past eight in the evening", American: "eight thirty PM" },
  { Soal: "21:30", British: "half past nine in the evening", American: "nine thirty PM" },
  { Soal: "22:30", British: "half past ten at night", American: "ten thirty PM" },
  { Soal: "23:30", British: "half past eleven at night", American: "eleven thirty PM" },
  { Soal: "0:15", British: "quarter past midnight", American: "twelve fifteen AM" },
  { Soal: "7:15", British: "quarter past seven in the morning", American: "seven fifteen AM" },
  { Soal: "12:15", British: "quarter past twelve", American: "twelve fifteen PM" },
  { Soal: "18:15", British: "quarter past six in the evening", American: "six fifteen PM" },
  { Soal: "20:15", British: "quarter past eight in the evening", American: "eight fifteen PM" },
  { Soal: "21:45", British: "quarter to ten in the evening", American: "nine forty-five PM" },
  { Soal: "23:45", British: "quarter to midnight", American: "eleven forty-five PM" },
  { Soal: "11:45", British: "quarter to twelve", American: "eleven forty-five AM" }
];
