window.loadedQuestions = [
  { Soal: "1", PenulisanSingkat: "1st", PenulisanPanjang: "first"},
  { Soal: "2", PenulisanSingkat: "2nd", PenulisanPanjang: "second"},
  { Soal: "3", PenulisanSingkat: "3rd", PenulisanPanjang: "third"},
  { Soal: "4", PenulisanSingkat: "4th", PenulisanPanjang: "fourth"},
  { Soal: "5", PenulisanSingkat: "5th", PenulisanPanjang: "fifth"},
  { Soal: "6", PenulisanSingkat: "6th", PenulisanPanjang: "sixth"},
  { Soal: "7", PenulisanSingkat: "7th", PenulisanPanjang: "seventh"},
  { Soal: "8", PenulisanSingkat: "8th", PenulisanPanjang: "eighth"},
  { Soal: "9", PenulisanSingkat: "9th", PenulisanPanjang: "ninth"},
  { Soal: "10", PenulisanSingkat: "10th", PenulisanPanjang: "tenth"},
  { Soal: "11", PenulisanSingkat: "11th", PenulisanPanjang: "eleventh"},
  { Soal: "12", PenulisanSingkat: "12th", PenulisanPanjang: "twelfth"},
  { Soal: "13", PenulisanSingkat: "13th", PenulisanPanjang: "thirteenth"},
  { Soal: "14", PenulisanSingkat: "14th", PenulisanPanjang: "fourteenth"},
  { Soal: "15", PenulisanSingkat: "15th", PenulisanPanjang: "fifteenth"},
  { Soal: "16", PenulisanSingkat: "16th", PenulisanPanjang: "sixteenth"},
  { Soal: "17", PenulisanSingkat: "17th", PenulisanPanjang: "seventeenth"},
  { Soal: "18", PenulisanSingkat: "18th", PenulisanPanjang: "eighteenth"},
  { Soal: "19", PenulisanSingkat: "19th", PenulisanPanjang: "nineteenth"},
  { Soal: "20", PenulisanSingkat: "20th", PenulisanPanjang: "twentieth"},
  { Soal: "21", PenulisanSingkat: "21st", PenulisanPanjang: "twenty-first"},
  { Soal: "22", PenulisanSingkat: "22nd", PenulisanPanjang: "twenty-second"},
  { Soal: "23", PenulisanSingkat: "23rd", PenulisanPanjang: "twenty-third"},
  { Soal: "24", PenulisanSingkat: "24th", PenulisanPanjang: "twenty-fourth"},
  { Soal: "25", PenulisanSingkat: "25th", PenulisanPanjang: "twenty-fifth"},
  { Soal: "26", PenulisanSingkat: "26th", PenulisanPanjang: "twenty-sixth"},
  { Soal: "27", PenulisanSingkat: "27th", PenulisanPanjang: "twenty-seventh"},
  { Soal: "28", PenulisanSingkat: "28th", PenulisanPanjang: "twenty-eighth"},
  { Soal: "29", PenulisanSingkat: "29th", PenulisanPanjang: "twenty-ninth"},
  { Soal: "30", PenulisanSingkat: "30th", PenulisanPanjang: "thirtieth"},
  { Soal: "31", PenulisanSingkat: "31st", PenulisanPanjang: "thirty-first"},
  { Soal: "32", PenulisanSingkat: "32nd", PenulisanPanjang: "thirty-second"},
  { Soal: "33", PenulisanSingkat: "33rd", PenulisanPanjang: "thirty-third"},
  { Soal: "34", PenulisanSingkat: "34th", PenulisanPanjang: "thirty-fourth"},
  { Soal: "35", PenulisanSingkat: "35th", PenulisanPanjang: "thirty-fifth"},
  { Soal: "36", PenulisanSingkat: "36th", PenulisanPanjang: "thirty-sixth"},
  { Soal: "37", PenulisanSingkat: "37th", PenulisanPanjang: "thirty-seventh"},
  { Soal: "38", PenulisanSingkat: "38th", PenulisanPanjang: "thirty-eighth"},
  { Soal: "39", PenulisanSingkat: "39th", PenulisanPanjang: "thirty-ninth"},
  { Soal: "40", PenulisanSingkat: "40th", PenulisanPanjang: "fortieth"},
  { Soal: "41", PenulisanSingkat: "41st", PenulisanPanjang: "forty-first"},
  { Soal: "42", PenulisanSingkat: "42nd", PenulisanPanjang: "forty-second"},
  { Soal: "43", PenulisanSingkat: "43rd", PenulisanPanjang: "forty-third"},
  { Soal: "44", PenulisanSingkat: "44th", PenulisanPanjang: "forty-fourth"},
  { Soal: "45", PenulisanSingkat: "45th", PenulisanPanjang: "forty-fifth"},
  { Soal: "46", PenulisanSingkat: "46th", PenulisanPanjang: "forty-sixth"},
  { Soal: "47", PenulisanSingkat: "47th", PenulisanPanjang: "forty-seventh"},
  { Soal: "48", PenulisanSingkat: "48th", PenulisanPanjang: "forty-eighth"},
  { Soal: "49", PenulisanSingkat: "49th", PenulisanPanjang: "forty-ninth"},
  { Soal: "50", PenulisanSingkat: "50th", PenulisanPanjang: "fiftieth"},
  { Soal: "51", PenulisanSingkat: "51st", PenulisanPanjang: "fifty-first"},
  { Soal: "52", PenulisanSingkat: "52nd", PenulisanPanjang: "fifty-second"},
  { Soal: "53", PenulisanSingkat: "53rd", PenulisanPanjang: "fifty-third"},
  { Soal: "54", PenulisanSingkat: "54th", PenulisanPanjang: "fifty-fourth"},
  { Soal: "55", PenulisanSingkat: "55th", PenulisanPanjang: "fifty-fifth"},
  { Soal: "56", PenulisanSingkat: "56th", PenulisanPanjang: "fifty-sixth"},
  { Soal: "57", PenulisanSingkat: "57th", PenulisanPanjang: "fifty-seventh"},
  { Soal: "58", PenulisanSingkat: "58th", PenulisanPanjang: "fifty-eighth"},
  { Soal: "59", PenulisanSingkat: "59th", PenulisanPanjang: "fifty-ninth"},
  { Soal: "60", PenulisanSingkat: "60th", PenulisanPanjang: "sixtieth"},
  { Soal: "61", PenulisanSingkat: "61st", PenulisanPanjang: "sixty-first"},
  { Soal: "62", PenulisanSingkat: "62nd", PenulisanPanjang: "sixty-second"},
  { Soal: "63", PenulisanSingkat: "63rd", PenulisanPanjang: "sixty-third"},
  { Soal: "64", PenulisanSingkat: "64th", PenulisanPanjang: "sixty-fourth"},
  { Soal: "65", PenulisanSingkat: "65th", PenulisanPanjang: "sixty-fifth"},
  { Soal: "66", PenulisanSingkat: "66th", PenulisanPanjang: "sixty-sixth"},
  { Soal: "67", PenulisanSingkat: "67th", PenulisanPanjang: "sixty-seventh"},
  { Soal: "68", PenulisanSingkat: "68th", PenulisanPanjang: "sixty-eighth"},
  { Soal: "69", PenulisanSingkat: "69th", PenulisanPanjang: "sixty-ninth"},
  { Soal: "70", PenulisanSingkat: "70th", PenulisanPanjang: "seventieth"},
  { Soal: "71", PenulisanSingkat: "71st", PenulisanPanjang: "seventy-first"},
  { Soal: "72", PenulisanSingkat: "72nd", PenulisanPanjang: "seventy-second"},
  { Soal: "73", PenulisanSingkat: "73rd", PenulisanPanjang: "seventy-third"},
  { Soal: "74", PenulisanSingkat: "74th", PenulisanPanjang: "seventy-fourth"},
  { Soal: "75", PenulisanSingkat: "75th", PenulisanPanjang: "seventy-fifth"},
  { Soal: "76", PenulisanSingkat: "76th", PenulisanPanjang: "seventy-sixth"},
  { Soal: "77", PenulisanSingkat: "77th", PenulisanPanjang: "seventy-seventh"},
  { Soal: "78", PenulisanSingkat: "78th", PenulisanPanjang: "seventy-eighth"},
  { Soal: "79", PenulisanSingkat: "79th", PenulisanPanjang: "seventy-ninth"},
  { Soal: "80", PenulisanSingkat: "80th", PenulisanPanjang: "eightieth"},
  { Soal: "81", PenulisanSingkat: "81st", PenulisanPanjang: "eighty-first"},
  { Soal: "82", PenulisanSingkat: "82nd", PenulisanPanjang: "eighty-second"},
  { Soal: "83", PenulisanSingkat: "83rd", PenulisanPanjang: "eighty-third"},
  { Soal: "84", PenulisanSingkat: "84th", PenulisanPanjang: "eighty-fourth"},
  { Soal: "85", PenulisanSingkat: "85th", PenulisanPanjang: "eighty-fifth"},
  { Soal: "86", PenulisanSingkat: "86th", PenulisanPanjang: "eighty-sixth"},
  { Soal: "87", PenulisanSingkat: "87th", PenulisanPanjang: "eighty-seventh"},
  { Soal: "88", PenulisanSingkat: "88th", PenulisanPanjang: "eighty-eighth"},
  { Soal: "89", PenulisanSingkat: "89th", PenulisanPanjang: "eighty-ninth"},
  { Soal: "90", PenulisanSingkat: "90th", PenulisanPanjang: "ninetieth"},
  { Soal: "91", PenulisanSingkat: "91st", PenulisanPanjang: "ninety-first"},
  { Soal: "92", PenulisanSingkat: "92nd", PenulisanPanjang: "ninety-second"},
  { Soal: "93", PenulisanSingkat: "93rd", PenulisanPanjang: "ninety-third"},
  { Soal: "94", PenulisanSingkat: "94th", PenulisanPanjang: "ninety-fourth"},
  { Soal: "95", PenulisanSingkat: "95th", PenulisanPanjang: "ninety-fifth"},
  { Soal: "96", PenulisanSingkat: "96th", PenulisanPanjang: "ninety-sixth"},
  { Soal: "97", PenulisanSingkat: "97th", PenulisanPanjang: "ninety-seventh"},
  { Soal: "98", PenulisanSingkat: "98th", PenulisanPanjang: "ninety-eighth"},
  { Soal: "99", PenulisanSingkat: "99th", PenulisanPanjang: "ninety-ninth"},
  { Soal: "100", PenulisanSingkat: "100th", PenulisanPanjang: "one hundredth"}
];

/*
  { Soal: "0", PenulisanSingkat: "0th", PenulisanPanjang: "zeroth" },
  { Soal: "1", PenulisanSingkat: "1st", PenulisanPanjang: "first" },
  { Soal: "2", PenulisanSingkat: "2nd", PenulisanPanjang: "second" },
  { Soal: "3", PenulisanSingkat: "3rd", PenulisanPanjang: "third" },
  { Soal: "4", PenulisanSingkat: "4th", PenulisanPanjang: "fourth" },
  { Soal: "5", PenulisanSingkat: "5th", PenulisanPanjang: "fifth" },
  { Soal: "6", PenulisanSingkat: "6th", PenulisanPanjang: "sixth" },
  { Soal: "7", PenulisanSingkat: "7th", PenulisanPanjang: "seventh" },
  { Soal: "8", PenulisanSingkat: "8th", PenulisanPanjang: "eighth" },
  { Soal: "9", PenulisanSingkat: "9th", PenulisanPanjang: "ninth" },
  { Soal: "10", PenulisanSingkat: "10th", PenulisanPanjang: "tenth" },
  { Soal: "11", PenulisanSingkat: "11th", PenulisanPanjang: "eleventh" },
  { Soal: "12", PenulisanSingkat: "12th", PenulisanPanjang: "twelfth" },
  { Soal: "13", PenulisanSingkat: "13th", PenulisanPanjang: "thirteenth" },
  { Soal: "14", PenulisanSingkat: "14th", PenulisanPanjang: "fourteenth" },
  { Soal: "15", PenulisanSingkat: "15th", PenulisanPanjang: "fifteenth" },
  { Soal: "16", PenulisanSingkat: "16th", PenulisanPanjang: "sixteenth" },
  { Soal: "17", PenulisanSingkat: "17th", PenulisanPanjang: "seventeenth" },
  { Soal: "18", PenulisanSingkat: "18th", PenulisanPanjang: "eighteenth" },
  { Soal: "19", PenulisanSingkat: "19th", PenulisanPanjang: "nineteenth" },
  { Soal: "20", PenulisanSingkat: "20th", PenulisanPanjang: "twentieth" },
  { Soal: "21", PenulisanSingkat: "21st", PenulisanPanjang: "twenty-first" },
  { Soal: "22", PenulisanSingkat: "22nd", PenulisanPanjang: "twenty-second" },
  { Soal: "23", PenulisanSingkat: "23rd", PenulisanPanjang: "twenty-third" },
  { Soal: "24", PenulisanSingkat: "24th", PenulisanPanjang: "twenty-fourth" },
  { Soal: "25", PenulisanSingkat: "25th", PenulisanPanjang: "twenty-fifth" },
  { Soal: "26", PenulisanSingkat: "26th", PenulisanPanjang: "twenty-sixth" },
  { Soal: "27", PenulisanSingkat: "27th", PenulisanPanjang: "twenty-seventh" },
  { Soal: "28", PenulisanSingkat: "28th", PenulisanPanjang: "twenty-eighth" },
  { Soal: "29", PenulisanSingkat: "29th", PenulisanPanjang: "twenty-ninth" },
  { Soal: "30", PenulisanSingkat: "30th", PenulisanPanjang: "thirtieth" },
  { Soal: "31", PenulisanSingkat: "31st", PenulisanPanjang: "thirty-first" },
  { Soal: "32", PenulisanSingkat: "32nd", PenulisanPanjang: "thirty-second" },
  { Soal: "33", PenulisanSingkat: "33rd", PenulisanPanjang: "thirty-third" },
  { Soal: "34", PenulisanSingkat: "34th", PenulisanPanjang: "thirty-fourth" },
  { Soal: "35", PenulisanSingkat: "35th", PenulisanPanjang: "thirty-fifth" },
  { Soal: "36", PenulisanSingkat: "36th", PenulisanPanjang: "thirty-sixth" },
  { Soal: "37", PenulisanSingkat: "37th", PenulisanPanjang: "thirty-seventh" },
  { Soal: "38", PenulisanSingkat: "38th", PenulisanPanjang: "thirty-eighth" },
  { Soal: "39", PenulisanSingkat: "39th", PenulisanPanjang: "thirty-ninth" },
  { Soal: "40", PenulisanSingkat: "40th", PenulisanPanjang: "fortieth" },
  { Soal: "41", PenulisanSingkat: "41st", PenulisanPanjang: "forty-first" },
  { Soal: "42", PenulisanSingkat: "42nd", PenulisanPanjang: "forty-second" },
  { Soal: "43", PenulisanSingkat: "43rd", PenulisanPanjang: "forty-third" },
  { Soal: "44", PenulisanSingkat: "44th", PenulisanPanjang: "forty-fourth" },
  { Soal: "45", PenulisanSingkat: "45th", PenulisanPanjang: "forty-fifth" },
  { Soal: "46", PenulisanSingkat: "46th", PenulisanPanjang: "forty-sixth" },
  { Soal: "47", PenulisanSingkat: "47th", PenulisanPanjang: "forty-seventh" },
  { Soal: "48", PenulisanSingkat: "48th", PenulisanPanjang: "forty-eighth" },
  { Soal: "49", PenulisanSingkat: "49th", PenulisanPanjang: "forty-ninth" },
  { Soal: "50", PenulisanSingkat: "50th", PenulisanPanjang: "fiftieth" },
  // Lanjutkan dari 51 hingga 100 jika ingin seluruh daftar
*/
