window.loadedQuestions = [
  { v1: "Study", v2: "studied", v3: "studied", arti: "belajar" },
  { v1: "Learn", v2: "learned", v3: "learned", arti: "mempelajari" },
  { v1: "Read", v2: "read", v3: "read", arti: "membaca" },
  { v1: "Write", v2: "wrote", v3: "written", arti: "menulis" },
  { v1: "Teach", v2: "taught", v3: "taught", arti: "mengajar" },
  { v1: "Explain", v2: "explained", v3: "explained", arti: "menjelaskan" },
  { v1: "Ask", v2: "asked", v3: "asked", arti: "bertanya" },
  { v1: "Answer", v2: "answered", v3: "answered", arti: "menjawab" },
  { v1: "Memorize", v2: "memorized", v3: "memorized", arti: "menghafal" },
  { v1: "Review", v2: "reviewed", v3: "reviewed", arti: "meninjau ulang" },
  { v1: "Discuss", v2: "discussed", v3: "discussed", arti: "mendiskusikan" },
  { v1: "Present", v2: "presented", v3: "presented", arti: "mempersembahkan / mempresentasikan" },
  { v1: "Research", v2: "researched", v3: "researched", arti: "meneliti" },
  { v1: "Understand", v2: "understood", v3: "understood", arti: "memahami" },
  { v1: "Solve", v2: "solved", v3: "solved", arti: "menyelesaikan (masalah)" },
  { v1: "Calculate", v2: "calculated", v3: "calculated", arti: "menghitung" },
  { v1: "Draw", v2: "drew", v3: "drawn", arti: "menggambar" },
  { v1: "Count", v2: "counted", v3: "counted", arti: "menghitung (jumlah)" },
  { v1: "Observe", v2: "observed", v3: "observed", arti: "mengamati" },
  { v1: "Submit", v2: "submitted", v3: "submitted", arti: "mengumpulkan (tugas)" },
  { v1: "Prepare", v2: "prepared", v3: "prepared", arti: "mempersiapkan" },
  { v1: "Practice", v2: "practiced", v3: "practiced", arti: "berlatih" },
  { v1: "Fail", v2: "failed", v3: "failed", arti: "gagal" },
  { v1: "Pass", v2: "passed", v3: "passed", arti: "lulus" },
  { v1: "Test", v2: "tested", v3: "tested", arti: "menguji" }
];
