window.loadedQuestions = [
  { v1: "Speak", v2: "spoke", v3: "spoken", arti: "berbicara" },
  { v1: "Talk", v2: "talked", v3: "talked", arti: "mengobrol" },
  { v1: "Say", v2: "said", v3: "said", arti: "mengatakan" },
  { v1: "Tell", v2: "told", v3: "told", arti: "menceritakan" },
  { v1: "Ask", v2: "asked", v3: "asked", arti: "bertanya" },
  { v1: "Answer", v2: "answered", v3: "answered", arti: "menjawab" },
  { v1: "Call", v2: "called", v3: "called", arti: "menelpon / memanggil" },
  { v1: "Text", v2: "texted", v3: "texted", arti: "mengirim pesan" },
  { v1: "Chat", v2: "chatted", v3: "chatted", arti: "mengobrol" },
  { v1: "Email", v2: "emailed", v3: "emailed", arti: "mengirim email" },
  { v1: "Write", v2: "wrote", v3: "written", arti: "menulis" },
  { v1: "Read", v2: "read", v3: "read", arti: "membaca" },
  { v1: "Report", v2: "reported", v3: "reported", arti: "melaporkan" },
  { v1: "Explain", v2: "explained", v3: "explained", arti: "menjelaskan" },
  { v1: "Describe", v2: "described", v3: "described", arti: "menggambarkan" },
  { v1: "Complain", v2: "complained", v3: "complained", arti: "mengeluh" },
  { v1: "Announce", v2: "announced", v3: "announced", arti: "mengumumkan" },
  { v1: "Inform", v2: "informed", v3: "informed", arti: "memberi tahu" },
  { v1: "Persuade", v2: "persuaded", v3: "persuaded", arti: "membujuk" },
  { v1: "Argue", v2: "argued", v3: "argued", arti: "berdebat" },
  { v1: "Discuss", v2: "discussed", v3: "discussed", arti: "mendiskusikan" },
  { v1: "Agree", v2: "agreed", v3: "agreed", arti: "setuju" },
  { v1: "Disagree", v2: "disagreed", v3: "disagreed", arti: "tidak setuju" },
  { v1: "Whisper", v2: "whispered", v3: "whispered", arti: "berbisik" },
  { v1: "Shout", v2: "shouted", v3: "shouted", arti: "berteriak" },
  { v1: "Annoy", v2: "annoyed", v3: "annoyed", arti: "mengganggu" },
  { v1: "Interrupt", v2: "interrupted", v3: "interrupted", arti: "menyela" },
  { v1: "Apologize", v2: "apologized", v3: "apologized", arti: "meminta maaf" },
  { v1: "Promise", v2: "promised", v3: "promised", arti: "berjanji" },
  { v1: "Lie", v2: "lied", v3: "lied", arti: "berbohong" }
];
