window.loadedQuestions = [
  { v1: "Breathe", v2: "breathed", v3: "breathed", arti: "bernapas" },
  { v1: "Cough", v2: "coughed", v3: "coughed", arti: "batuk" },
  { v1: "Sneeze", v2: "sneezed", v3: "sneezed", arti: "bersin" },
  { v1: "Bleed", v2: "bled", v3: "bled", arti: "berdarah" },
  { v1: "Faint", v2: "fainted", v3: "fainted", arti: "pingsan" },
  { v1: "Hurt", v2: "hurt", v3: "hurt", arti: "terluka / sakit" },
  { v1: "Heal", v2: "healed", v3: "healed", arti: "sembuh / menyembuhkan" },
  { v1: "Recover", v2: "recovered", v3: "recovered", arti: "pulih" },
  { v1: "Rest", v2: "rested", v3: "rested", arti: "istirahat" },
  { v1: "Sleep", v2: "slept", v3: "slept", arti: "tidur" },
  { v1: "Wake", v2: "woke", v3: "woken", arti: "bangun" },
  { v1: "Exercise", v2: "exercised", v3: "exercised", arti: "berolahraga" },
  { v1: "Move", v2: "moved", v3: "moved", arti: "bergerak" },
  { v1: "Stretch", v2: "stretched", v3: "stretched", arti: "meregangkan" },
  { v1: "Touch", v2: "touched", v3: "touched", arti: "menyentuh" },
  { v1: "Feel", v2: "felt", v3: "felt", arti: "merasa" },
  { v1: "See", v2: "saw", v3: "seen", arti: "melihat" },
  { v1: "Hear", v2: "heard", v3: "heard", arti: "mendengar" },
  { v1: "Taste", v2: "tasted", v3: "tasted", arti: "merasakan (lidah)" },
  { v1: "Smell", v2: "smelled", v3: "smelled", arti: "mencium (hidung)" },
  { v1: "Take", v2: "took", v3: "taken", arti: "mengambil (obat)" },
  { v1: "Check", v2: "checked", v3: "checked", arti: "memeriksa" },
  { v1: "Treat", v2: "treated", v3: "treated", arti: "mengobati" },
  { v1: "Inject", v2: "injected", v3: "injected", arti: "menyuntik" },
  { v1: "Diagnose", v2: "diagnosed", v3: "diagnosed", arti: "mendiagnosis" }
];
