window.loadedQuestions = [
  //Regular Verb
  //Awalan A
  { v1: "Abase", v2: "abased", v3: "abased", arti: "menghinakan" },
  { v1: "Abash", v2: "abashed", v3: "abashed", arti: "memalukan" },
  { v1: "Abate", v2: "abated", v3: "abated", arti: "berkurang" },
  { v1: "Abbreviate", v2: "abbreviated", v3: "abbreviated", arti: "menyingkat" },
  { v1: "Abdicate", v2: "abdicated", v3: "abdicated", arti: "turun tahta" },
  { v1: "Abduct", v2: "abducted", v3: "abducted", arti: "menculik" },
  { v1: "Abhor", v2: "abhorred", v3: "abhorred", arti: "membenci" },
  { v1: "Abolish", v2: "abolished", v3: "abolished", arti: "menghapuskan" },
  { v1: "Abridge", v2: "abridged", v3: "abridged", arti: "menyingkat" },
  { v1: "Abrogate", v2: "abrogated", v3: "abrogated", arti: "membatalkan" },
  { v1: "Absolve", v2: "absolved", v3: "absolved", arti: "membebaskan" },
  { v1: "Absorb", v2: "absorbed", v3: "absorbed", arti: "menyerap" },
  { v1: "Abstain", v2: "abstained", v3: "abstained", arti: "berpantang" },
  { v1: "Abuse", v2: "abused", v3: "abused", arti: "mencaci maki" },
  { v1: "Accede", v2: "acceded", v3: "acceded", arti: "naik (tahta)" },
  { v1: "Accelerate", v2: "accelerated", v3: "accelerated", arti: "mempercepat" },
  { v1: "Accentuate", v2: "accentuated", v3: "accentuated", arti: "menekankan / memperjelas" },
  { v1: "Accept", v2: "accepted", v3: "accepted", arti: "menerima" },
  { v1: "Acclaim", v2: "acclaimed", v3: "acclaimed", arti: "menyambut gembira" },
  { v1: "Acclimate", v2: "acclimated", v3: "acclimated", arti: "menyesuaikan diri dengan iklim" },
  { v1: "Accommodate", v2: "accommodated", v3: "accommodated", arti: "menampung" },
  { v1: "Accompany", v2: "accompanied", v3: "accompanied", arti: "menemani" },
  { v1: "Accomplish", v2: "accomplished", v3: "accomplished", arti: "menyelesaikan" },
  { v1: "Accost", v2: "accosted", v3: "accosted", arti: "menegur" },
  { v1: "Account", v2: "accounted", v3: "accounted", arti: "menghitung / mempertanggungjawabkan" },
  { v1: "Accrue", v2: "accrued", v3: "accrued", arti: "bertambah / meluas" },
  { v1: "Accumulate", v2: "accumulated", v3: "accumulated", arti: "menimbun / mengumpulkan" },
  { v1: "Accuse", v2: "accused", v3: "accused", arti: "menuduh" },
  { v1: "Achieve", v2: "achieved", v3: "achieved", arti: "mencapai" },
  { v1: "Acquaint", v2: "acquainted", v3: "acquainted", arti: "memperkenalkan" },
  { v1: "Acquire", v2: "acquired", v3: "acquired", arti: "memperoleh" },
  { v1: "Acquit", v2: "acquitted", v3: "acquitted", arti: "membebaskan" },
  { v1: "Cross", v2: "crossed", v3: "crossed", arti: "melintasi / menyeberang" },
  { v1: "Act", v2: "acted", v3: "acted", arti: "bertindak" },
  { v1: "Actuate", v2: "actuated", v3: "actuated", arti: "menjalankan / menggerakkan" },
  { v1: "Adapt", v2: "adapted", v3: "adapted", arti: "menyesuaikan" },
  { v1: "Add", v2: "added", v3: "added", arti: "menambahkan" },
  { v1: "Address", v2: "addressed", v3: "addressed", arti: "mengalamatkan / menyampaikan" },
  { v1: "Adhere", v2: "adhered", v3: "adhered", arti: "menganut / melekat" },
  { v1: "Adjoin", v2: "adjoined", v3: "adjoined", arti: "menggabungkan / berdampingan" },
  { v1: "Adjourn", v2: "adjourned", v3: "adjourned", arti: "menangguhkan / menunda" },
  { v1: "Adjudge", v2: "adjudged", v3: "adjudged", arti: "menghukum / memutuskan" },
  { v1: "Adjure", v2: "adjured", v3: "adjured", arti: "meminta dengan sangat / memohon" },
  { v1: "Adjust", v2: "adjusted", v3: "adjusted", arti: "menyesuaikan" },
  { v1: "Administer", v2: "administered", v3: "administered", arti: "mengelola / mengatur" },
  { v1: "Admire", v2: "admired", v3: "admired", arti: "memuji / mengagumi" },
  { v1: "Admit", v2: "admitted", v3: "admitted", arti: "mengakui / mengizinkan masuk" },
  { v1: "Admix", v2: "admixed", v3: "admixed", arti: "mencampurkan" },
  { v1: "Admonish", v2: "admonished", v3: "admonished", arti: "memperingatkan / menegur" },
  { v1: "Adopt", v2: "adopted", v3: "adopted", arti: "memungut / mengadopsi" },
  { v1: "Adore", v2: "adored", v3: "adored", arti: "memuja" },
  { v1: "Adorn", v2: "adorned", v3: "adorned", arti: "menghiasi" },
  { v1: "Adulate", v2: "adulated", v3: "adulated", arti: "membujuk / memuja berlebihan" },
  { v1: "Adulterate", v2: "adulterated", v3: "adulterated", arti: "memalsukan / mencampur" },
  { v1: "Advance", v2: "advanced", v3: "advanced", arti: "memajukan" },
  { v1: "Advert", v2: "adverted", v3: "adverted", arti: "memperhatikan" },
  { v1: "Advertise", v2: "advertised", v3: "advertised", arti: "mengiklankan" },
  { v1: "Advise", v2: "advised", v3: "advised", arti: "menasehati" },
  { v1: "Advocate", v2: "advocated", v3: "advocated", arti: "membela / mendukung" },
  { v1: "Affect", v2: "affected", v3: "affected", arti: "mempengaruhi" },
  { v1: "Affiliate", v2: "affiliated", v3: "affiliated", arti: "menggabungkan diri" },
  { v1: "Affirm", v2: "affirmed", v3: "affirmed", arti: "menegaskan" },
  { v1: "Afford", v2: "afforded", v3: "afforded", arti: "mampu / menyediakan" },
  { v1: "Afforest", v2: "afforested", v3: "afforested", arti: "menghutankan" },
  { v1: "Affranchise", v2: "affranchised", v3: "affranchised", arti: "memerdekakan" },
  { v1: "Affront", v2: "affronted", v3: "affronted", arti: "menghina" },
  { v1: "Agglomerate", v2: "agglomerated", v3: "agglomerated", arti: "mengelompokkan" },
  { v1: "Agglutinate", v2: "agglutinated", v3: "agglutinated", arti: "melekatkan" },
  { v1: "Aggrandize", v2: "aggrandized", v3: "aggrandized", arti: "memperbesar" },
  { v1: "Aggravate", v2: "aggravated", v3: "aggravated", arti: "menjengkelkan / memperburuk" },
  { v1: "Aggress", v2: "aggressed", v3: "aggressed", arti: "menyerang" },
  { v1: "Agitate", v2: "agitated", v3: "agitated", arti: "menghasut / mengguncang" },
  { v1: "Aid", v2: "aided", v3: "aided", arti: "membantu" },
  { v1: "Aim", v2: "aimed", v3: "aimed", arti: "membidik / bertujuan" },
  { v1: "Alight", v2: "alighted", v3: "alighted", arti: "hinggap / turun" },
  { v1: "Align", v2: "aligned", v3: "aligned", arti: "meluruskan / menyelaraskan" },
  { v1: "Allay", v2: "allayed", v3: "allayed", arti: "menenangkan / meredakan" },
  { v1: "Allege", v2: "alleged", v3: "alleged", arti: "menyatakan / menuduh" },
  { v1: "Alleviate", v2: "alleviated", v3: "alleviated", arti: "meringankan" },
  { v1: "Allocate", v2: "allocated", v3: "allocated", arti: "menentukan tempat / mengalokasikan" },
  { v1: "Allot", v2: "allotted", v3: "allotted", arti: "membagikan / menetapkan" },
  { v1: "Allude", v2: "alluded", v3: "alluded", arti: "menyinggung / merujuk" },
  { v1: "Allure", v2: "allured", v3: "allured", arti: "memikat / menggoda" },
  { v1: "Ally", v2: "allied", v3: "allied", arti: "bersekutu / bersatu" },
  { v1: "Alter", v2: "altered", v3: "altered", arti: "mengubah" },
  { v1: "Altercate", v2: "altercated", v3: "altercated", arti: "bertengkar" },
  { v1: "Alternate", v2: "alternated", v3: "alternated", arti: "berganti-ganti" },
  { v1: "Amalgamate", v2: "amalgamated", v3: "amalgamated", arti: "mencampur / menggabungkan" },
  { v1: "Amass", v2: "amassed", v3: "amassed", arti: "menghimpun / menumpuk" },
  { v1: "Amaze", v2: "amazed", v3: "amazed", arti: "menakjubkan / mengherankan" },
  { v1: "Ameliorate", v2: "ameliorated", v3: "ameliorated", arti: "memperbaiki / meningkatkan" },
  { v1: "Amend", v2: "amended", v3: "amended", arti: "mengubah / memperbaiki" },
  { v1: "Amortize", v2: "amortized", v3: "amortized", arti: "melunasi dengan mengangsur" },
  { v1: "Amplify", v2: "amplified", v3: "amplified", arti: "memperkuat / memperbesar" },
  { v1: "Amputate", v2: "amputated", v3: "amputated", arti: "memotong anggota badan" },
  { v1: "Amuse", v2: "amused", v3: "amused", arti: "menghibur / membuat senang" },
  { v1: "Anaesthesize", v2: "anaesthesized", v3: "anaesthesized", arti: "membius" },
  { v1: "Analogize", v2: "analogized", v3: "analogized", arti: "menganalogi / membandingkan" },
  { v1: "Analyze", v2: "analyzed", v3: "analyzed", arti: "menganalisa" },
  { v1: "Anglicize", v2: "anglicized", v3: "anglicized", arti: "menginggriskan" },
  { v1: "Animate", v2: "animated", v3: "animated", arti: "menghidupkan / menganimasikan" },
  { v1: "Annex", v2: "annexed", v3: "annexed", arti: "menggabungkan / mencaplok" },
  { v1: "Annihilate", v2: "annihilated", v3: "annihilated", arti: "membasmi / memusnahkan" },
  { v1: "Annotate", v2: "annotated", v3: "annotated", arti: "membubuhi keterangan" },
  { v1: "Announce", v2: "announced", v3: "announced", arti: "mengumumkan" },
  { v1: "Annoy", v2: "annoyed", v3: "annoyed", arti: "menjengkelkan / mengganggu" },
  { v1: "Annul", v2: "annulled", v3: "annulled", arti: "membatalkan" },
  { v1: "Answer", v2: "answered", v3: "answered", arti: "menjawab" },
  { v1: "Antagonize", v2: "antagonized", v3: "antagonized", arti: "menentang / memusuhi" },
  { v1: "Antedate", v2: "antedated", v3: "antedated", arti: "memberi tanggal lebih maju" },
  { v1: "Anticipate", v2: "anticipated", v3: "anticipated", arti: "mendahului / mengantisipasi" },
  { v1: "Antiquate", v2: "antiquated", v3: "antiquated", arti: "menjadikan benda kuno" },
  { v1: "Apologize", v2: "apologized", v3: "apologized", arti: "minta maaf" },
  { v1: "Appal", v2: "appalled", v3: "appalled", arti: "menggemparkan / mengejutkan" },
  { v1: "Appear", v2: "appeared", v3: "appeared", arti: "tampak / muncul" },
  { v1: "Applaud", v2: "applauded", v3: "applauded", arti: "bertepuk tangan / memuji" },
  { v1: "Apply", v2: "applied", v3: "applied", arti: "menggunakan / menerapkan" },
  { v1: "Appoint", v2: "appointed", v3: "appointed", arti: "menunjuk / menetapkan" },
  { v1: "Apportion", v2: "apportioned", v3: "apportioned", arti: "membagi secara adil" },
  { v1: "Appreciate", v2: "appreciated", v3: "appreciated", arti: "menghargai" },
  { v1: "Apprise", v2: "apprised", v3: "apprised", arti: "memberi kabar / memberitahu" },
  { v1: "Approach", v2: "approached", v3: "approached", arti: "mendekat / menghampiri" },
  { v1: "Appropriate", v2: "appropriated", v3: "appropriated", arti: "menyediakan / mengalokasikan" },
  { v1: "Approve", v2: "approved", v3: "approved", arti: "menyetujui" },
  { v1: "Arbitrate", v2: "arbitrated", v3: "arbitrated", arti: "menengahi / menjadi penengah" },
  { v1: "Argue", v2: "argued", v3: "argued", arti: "mendebatkan / berargumen" },
  { v1: "Arrange", v2: "arranged", v3: "arranged", arti: "menata / mengatur" },
  { v1: "Array", v2: "arrayed", v3: "arrayed", arti: "mempersiapkan / menyusun (barisan)" },
  { v1: "Arrive", v2: "arrived", v3: "arrived", arti: "tiba" },
  { v1: "Ascertain", v2: "ascertained", v3: "ascertained", arti: "memastikan" },
  { v1: "Ascribe", v2: "ascribed", v3: "ascribed", arti: "menganggap berasal" },
  { v1: "Ask", v2: "asked", v3: "asked", arti: "bertanya" },
  { v1: "Aspirate", v2: "aspirated", v3: "aspirated", arti: "mengucap bunyi dengan nafas keras" },
  { v1: "Aspire", v2: "aspired", v3: "aspired", arti: "bercita-cita" },
  { v1: "Assail", v2: "assailed", v3: "assailed", arti: "menyerang" },
  { v1: "Assay", v2: "assayed", v3: "assayed", arti: "menguji / mencoba" },
  { v1: "Assemble", v2: "assembled", v3: "assembled", arti: "memasang / merakit / berkumpul" },
  { v1: "Assert", v2: "asserted", v3: "asserted", arti: "menegaskan" },
  { v1: "Assess", v2: "assessed", v3: "assessed", arti: "menaksir / menilai" },
  { v1: "Assign", v2: "assigned", v3: "assigned", arti: "menugaskan" },
  { v1: "Assimilate", v2: "assimilated", v3: "assimilated", arti: "mengasimilasi" },
  { v1: "Associate", v2: "associated", v3: "associated", arti: "menghubungkan / berhubungan" },
  { v1: "Assort", v2: "assorted", v3: "assorted", arti: "memilih / menyortir" },
  { v1: "Assuage", v2: "assuaged", v3: "assuaged", arti: "meredakan / menenangkan" },
  { v1: "Assure", v2: "assured", v3: "assured", arti: "menjamin" },
  { v1: "Astonish", v2: "astonished", v3: "astonished", arti: "mengherankan" },
  { v1: "Astound", v2: "astounded", v3: "astounded", arti: "mengejutkan / mengagumkan" },
  { v1: "Atone", v2: "atoned", v3: "atoned", arti: "bertobat / menebus kesalahan" },
  { v1: "Attach", v2: "attached", v3: "attached", arti: "melampirkan" },
  { v1: "Attack", v2: "attacked", v3: "attacked", arti: "menyerang" },
  { v1: "Attain", v2: "attained", v3: "attained", arti: "mencapai" },
  { v1: "Attempt", v2: "attempted", v3: "attempted", arti: "berusaha" },
  { v1: "Attend", v2: "attended", v3: "attended", arti: "menghadiri" },
  { v1: "Attenuate", v2: "attenuated", v3: "attenuated", arti: "melemahkan / menipiskan" },
  { v1: "Attest", v2: "attested", v3: "attested", arti: "membuktikan / bersaksi" },
  { v1: "Attire", v2: "attired", v3: "attired", arti: "berpakaian" },
  { v1: "Attract", v2: "attracted", v3: "attracted", arti: "memikat / menarik" },
  { v1: "Attune", v2: "attuned", v3: "attuned", arti: "mencoba bunyi / menyesuaikan" },
  { v1: "Augment", v2: "augmented", v3: "augmented", arti: "memperbanyak / menambah" },
  { v1: "Augur", v2: "augured", v3: "augured", arti: "meramalkan / menandakan" },
  { v1: "Authorize", v2: "authorized", v3: "authorized", arti: "mengesahkan / memberi wewenang" },
  { v1: "Avert", v2: "averted", v3: "averted", arti: "mencegah / menghindarkan" },
  { v1: "Aviate", v2: "aviated", v3: "aviated", arti: "terbang dengan pesawat" },
  { v1: "Avoid", v2: "avoided", v3: "avoided", arti: "menghindari" },
  { v1: "Avouch", v2: "avouched", v3: "avouched", arti: "menjamin / menyatakan dengan tegas" },
  { v1: "Avow", v2: "avowed", v3: "avowed", arti: "mengakui / menyatakan" },
  { v1: "Await", v2: "awaited", v3: "awaited", arti: "menunggu" },
  { v1: "Award", v2: "awarded", v3: "awarded", arti: "menganugerahi" },
  { v1: "Axe", v2: "axed", v3: "axed", arti: "memotong / menghapuskan" },
  //Awalan B
  { v1: "Babble", v2: "babbled", v3: "babbled", arti: "ngoceh / bergumam" },
  { v1: "Balance", v2: "balanced", v3: "balanced", arti: "mencocokkan / menyeimbangkan" },
  { v1: "Balk", v2: "balked", v3: "balked", arti: "mogok / enggan" },
  { v1: "Bamboozle", v2: "bamboozled", v3: "bamboozled", arti: "memperdayakan / menipu" },
  { v1: "Ban", v2: "banned", v3: "banned", arti: "melarang" },
  { v1: "Bandage", v2: "bandaged", v3: "bandaged", arti: "membalut" },
  { v1: "Banish", v2: "banished", v3: "banished", arti: "membuang / mengusir" },
  { v1: "Baptize", v2: "baptized", v3: "baptized", arti: "membaptis" },
  { v1: "Barbarize", v2: "barbarized", v3: "barbarized", arti: "menjadi biadab" },
  { v1: "Bargain", v2: "bargained", v3: "bargained", arti: "tawar-menawar" },
  { v1: "Bark", v2: "barked", v3: "barked", arti: "menyalak" },
  { v1: "Bate", v2: "bated", v3: "bated", arti: "mengurangi / menahan" },
  { v1: "Bathe", v2: "bathed", v3: "bathed", arti: "memandikan / mandi" },
  { v1: "Batter", v2: "battered", v3: "battered", arti: "memukul berulang-ulang" },
  { v1: "Bawl", v2: "bawled", v3: "bawled", arti: "berteriak / menangis keras" },
  { v1: "Becalm", v2: "becalmed", v3: "becalmed", arti: "menenangkan / membuat diam" },
  { v1: "Beckon", v2: "beckoned", v3: "beckoned", arti: "mengisyaratkan / memanggil dengan gerakan" },
  { v1: "Bedazzle", v2: "bedazzled", v3: "bedazzled", arti: "menyilaukan / mempesona" },
  { v1: "Bedeck", v2: "bedecked", v3: "bedecked", arti: "menghias" },
  { v1: "Bedevil", v2: "bedeviled", v3: "bedeviled", arti: "menggoda / mengganggu" },
  { v1: "Bedew", v2: "bedewed", v3: "bedewed", arti: "melumuri / membasahi" },
  { v1: "Befit", v2: "befitted", v3: "befitted", arti: "mencocokkan / sesuai" },
  { v1: "Befool", v2: "befooled", v3: "befooled", arti: "membodohi" },
  { v1: "Beg", v2: "begged", v3: "begged", arti: "meminta / mengemis" },
  { v1: "Begrime", v2: "begrimed", v3: "begrimed", arti: "mencemari / mengotori" },
  { v1: "Begrudge", v2: "begrudged", v3: "begrudged", arti: "mengiri / merasa berat hati" },
  { v1: "Beguile", v2: "beguiled", v3: "beguiled", arti: "memperdayakan / menipu dengan rayuan" },
  { v1: "Behead", v2: "beheaded", v3: "beheaded", arti: "memenggal" },
  { v1: "Belabour", v2: "belaboured", v3: "belaboured", arti: "memukul dengan keras / mengulang-ulang" },
  { v1: "Belaud", v2: "belauded", v3: "belauded", arti: "memuji" },
  { v1: "Beleaguer", v2: "beleaguered", v3: "beleaguered", arti: "mengepung / mengepung musuh" },
  { v1: "Believe", v2: "believed", v3: "believed", arti: "mempercayai" },
  { v1: "Belittle", v2: "belittled", v3: "belittled", arti: "meremehkan / mengecilkan" },
  { v1: "Bellow", v2: "bellowed", v3: "bellowed", arti: "melenguh / berteriak keras" },
  { v1: "Bemoan", v2: "bemoaned", v3: "bemoaned", arti: "meratapi / meratapkan" },
  { v1: "Benumb", v2: "benumbed", v3: "benumbed", arti: "menjadi kaku kedinginan / membuat kebas" },
  { v1: "Bequeath", v2: "bequeathed", v3: "bequeathed", arti: "mewariskan" },
  { v1: "Bereave", v2: "bereaved/bereft", v3: "bereaved/bereft", arti: "merampas / membuat kehilangan" },
  { v1: "Besiege", v2: "besieged", v3: "besieged", arti: "mengepung" },
  { v1: "Besmear", v2: "besmeared", v3: "besmeared", arti: "mengotori" },
  { v1: "Besprinkle", v2: "besprinkled", v3: "besprinkled", arti: "memerciki" },
  { v1: "Betray", v2: "betrayed", v3: "betrayed", arti: "mengkhianati" },
  { v1: "Betroth", v2: "betrothed", v3: "betrothed", arti: "bertunangan" },
  { v1: "Bevel", v2: "beveled", v3: "beveled", arti: "memiringkan / memotong miring" },
  { v1: "Bewail", v2: "bewailed", v3: "bewailed", arti: "meratapi" },
  { v1: "Bewilder", v2: "bewildered", v3: "bewildered", arti: "membingungkan" },
  { v1: "Bewitch", v2: "bewitched", v3: "bewitched", arti: "mempesonakan / menyihir" },
  { v1: "Bicker", v2: "bickered", v3: "bickered", arti: "bercekcok" },
  { v1: "Bivouac", v2: "bivouacked", v3: "bivouacked", arti: "berkemah" },
  { v1: "Blame", v2: "blamed", v3: "blamed", arti: "menyalahkan" },
  { v1: "Blast", v2: "blasted", v3: "blasted", arti: "menghancurkan / meledakkan" },
  { v1: "Bless", v2: "blessed", v3: "blessed", arti: "memberkahi" },
  { v1: "Block", v2: "blocked", v3: "blocked", arti: "merintangi / menghalangi" },
  { v1: "Bluster", v2: "blustered", v3: "blustered", arti: "menggertak / mengamuk" },
  { v1: "Boast", v2: "boasted", v3: "boasted", arti: "menyombongkan diri" },
  { v1: "Bode", v2: "boded", v3: "boded", arti: "menunjukkan / meramalkan" },
  { v1: "Boggle", v2: "boggled", v3: "boggled", arti: "meragukan / terkejut bingung" },
  { v1: "Boil", v2: "boiled", v3: "boiled", arti: "mendidihkan" },
  { v1: "Boobytrap", v2: "boobytrapped", v3: "boobytrapped", arti: "memasang ranjau" },
  { v1: "Bootleg", v2: "bootlegged", v3: "bootlegged", arti: "menyelundupkan" },
  { v1: "Bop", v2: "bopped", v3: "bopped", arti: "memukul" },
  { v1: "Bounce", v2: "bounced", v3: "bounced", arti: "memantul" },
  { v1: "Boycott", v2: "boycotted", v3: "boycotted", arti: "memboikot" },
  { v1: "Brag", v2: "bragged", v3: "bragged", arti: "menyombongkan" },
  { v1: "Brandish", v2: "brandished", v3: "brandished", arti: "mengacungkan" },
  { v1: "Braze", v2: "brazed", v3: "brazed", arti: "memateri / menyolder" },
  { v1: "Breathe", v2: "breathed", v3: "breathed", arti: "bernafas" },
  { v1: "Bribe", v2: "bribed", v3: "bribed", arti: "menyuap" },
  { v1: "Brim", v2: "brimmed", v3: "brimmed", arti: "penuh sampai tepi / meluap" },
  { v1: "Broadcast", v2: "broadcast", v3: "broadcast", arti: "menyiarkan" },
  { v1: "Brush", v2: "brushed", v3: "brushed", arti: "menyikat" },
  { v1: "Bulge", v2: "bulged", v3: "bulged", arti: "menonjol (keluar)" },
  { v1: "Burden", v2: "burdened", v3: "burdened", arti: "menyusahkan" },
  { v1: "Burgle", v2: "burgled", v3: "burgled", arti: "membongkar" },
  { v1: "Burrow", v2: "burrowed", v3: "burrowed", arti: "bersembunyi" },
  { v1: "Bury", v2: "buried", v3: "buried", arti: "mengubur" },
  //Awalan C
  { v1: "Cackle", v2: "cackled", v3: "cackled", arti: "tertawa cekikikan" },
  { v1: "Cadge", v2: "cadged", v3: "cadged", arti: "mengemis / meminta-minta" },
  { v1: "Calcify", v2: "calcified", v3: "calcified", arti: "mengeras (jadi batu kapur)" },
  { v1: "Calculate", v2: "calculated", v3: "calculated", arti: "menghitung" },
  { v1: "Call", v2: "called", v3: "called", arti: "memanggil" },
  { v1: "Calumniate", v2: "calumniated", v3: "calumniated", arti: "memfitnah" },
  { v1: "Canvass", v2: "canvassed", v3: "canvassed", arti: "meneliti / mengampanyekan" },
  { v1: "Capitulate", v2: "capitulated", v3: "capitulated", arti: "menyerah" },
  { v1: "Capture", v2: "captured", v3: "captured", arti: "menangkap" },
  { v1: "Carry", v2: "carried", v3: "carried", arti: "membawa" },
  { v1: "Castigate", v2: "castigated", v3: "castigated", arti: "menghukum keras / menyiksa" },
  { v1: "Celebrate", v2: "celebrated", v3: "celebrated", arti: "merayakan" },
  { v1: "Charge", v2: "charged", v3: "charged", arti: "menagih / menuduh / menyerang" },
  { v1: "Charter", v2: "chartered", v3: "chartered", arti: "mencarter" },
  { v1: "Chat", v2: "chatted", v3: "chatted", arti: "mengobrol" },
  { v1: "Cheat", v2: "cheated", v3: "cheated", arti: "menipu" },
  { v1: "Check", v2: "checked", v3: "checked", arti: "memeriksa" },
  { v1: "Cherish", v2: "cherished", v3: "cherished", arti: "menghargai / menyayangi" },
  { v1: "Chew", v2: "chewed", v3: "chewed", arti: "mengunyah" },
  { v1: "Chicane", v2: "chicaned", v3: "chicaned", arti: "mengelabui / mengganggu" },
  { v1: "Chum", v2: "chummed", v3: "chummed", arti: "berteman akrab" },
  { v1: "Circulate", v2: "circulated", v3: "circulated", arti: "mengedarkan" },
  { v1: "Circumcise", v2: "circumcised", v3: "circumcised", arti: "menyunat" },
  { v1: "Claim", v2: "claimed", v3: "claimed", arti: "mengklaim / menuntut" },
  { v1: "Clap", v2: "clapped", v3: "clapped", arti: "bertepuk tangan" },
  { v1: "Clarify", v2: "clarified", v3: "clarified", arti: "menjelaskan" },
  { v1: "Classify", v2: "classified", v3: "classified", arti: "mengklasifikasikan" },
  { v1: "Climb", v2: "climbed", v3: "climbed", arti: "memanjat" },
  { v1: "Clip", v2: "clipped", v3: "clipped", arti: "memotong / menjepit" },
  { v1: "Clog", v2: "clogged", v3: "clogged", arti: "menyumbat" },
  { v1: "Clop", v2: "clopped", v3: "clopped", arti: "berbunyi klop-klop (suara langkah kuda)" },
  { v1: "Close", v2: "closed", v3: "closed", arti: "menutup" },
  { v1: "Cogitate", v2: "cogitated", v3: "cogitated", arti: "merenungkan" },
  { v1: "Collide", v2: "collided", v3: "collided", arti: "bertabrakan" },
  { v1: "Comfort", v2: "comforted", v3: "comforted", arti: "menghibur / menenangkan" },
  { v1: "Compile", v2: "compiled", v3: "compiled", arti: "mengompilasi / menyusun" },
  { v1: "Complicate", v2: "complicated", v3: "complicated", arti: "memperumit" },
  { v1: "Conceal", v2: "concealed", v3: "concealed", arti: "menyembunyikan" },
  { v1: "Conduct", v2: "conducted", v3: "conducted", arti: "memimpin / melaksanakan" },
  { v1: "Confer", v2: "conferred", v3: "conferred", arti: "berunding / menganugerahkan" },
  { v1: "Confine", v2: "confined", v3: "confined", arti: "membatasi / mengurung" },
  { v1: "Confirm", v2: "confirmed", v3: "confirmed", arti: "mengonfirmasi / meneguhkan" },
  { v1: "Conjugate", v2: "conjugated", v3: "conjugated", arti: "mengonjugasi / mengubah bentuk kata kerja" },
  { v1: "Connect", v2: "connected", v3: "connected", arti: "menghubungkan" },
  { v1: "Consign", v2: "consigned", v3: "consigned", arti: "mengirim / menyerahkan" },
  { v1: "Consume", v2: "consumed", v3: "consumed", arti: "mengonsumsi / menghabiskan" },
  { v1: "Cook", v2: "cooked", v3: "cooked", arti: "memasak" },
  { v1: "Copulate", v2: "copulated", v3: "copulated", arti: "bersetubuh" },
  { v1: "Copy", v2: "copied", v3: "copied", arti: "menyalin" },
  { v1: "Cough", v2: "coughed", v3: "coughed", arti: "batuk" },
  { v1: "Count", v2: "counted", v3: "counted", arti: "menghitung" },
  { v1: "Cram", v2: "crammed", v3: "crammed", arti: "belajar keras / menjejalkan" },
  { v1: "Crib", v2: "cribbed", v3: "cribbed", arti: "mencontek / menjiplak" },
  { v1: "Criticize", v2: "criticized", v3: "criticized", arti: "mengkritik" },
  { v1: "Crucify", v2: "crucified", v3: "crucified", arti: "menyalibkan" },
  { v1: "Cry", v2: "cried", v3: "cried", arti: "menangis" },
  { v1: "Curtsey", v2: "curtseyed", v3: "curtseyed", arti: "membungkuk memberi hormat (wanita)" },
  { v1: "Curtsy", v2: "curtsied", v3: "curtsied", arti: "membungkuk memberi hormat (wanita)" },
  { v1: "Cycle", v2: "cycled", v3: "cycled", arti: "bersepeda / berputar" },
  //Awalan D
  { v1: "Dab", v2: "dabbed", v3: "dabbed", arti: "menepuk ringan" },
  { v1: "Dabble", v2: "dabbled", v3: "dabbled", arti: "menceburkan / bermain-main" },
  { v1: "Dam", v2: "dammed", v3: "dammed", arti: "membendung" },
  { v1: "Damage", v2: "damaged", v3: "damaged", arti: "merusak" },
  { v1: "Dance", v2: "danced", v3: "danced", arti: "menari" },
  { v1: "Dash", v2: "dashed", v3: "dashed", arti: "berlari cepat" },
  { v1: "Daze", v2: "dazed", v3: "dazed", arti: "membingungkan / membuat pusing" },
  { v1: "Dazzle", v2: "dazzled", v3: "dazzled", arti: "menyilaukan / mempesona" },
  { v1: "Debar", v2: "debarred", v3: "debarred", arti: "melarang / mencegah" },
  { v1: "Debase", v2: "debased", v3: "debased", arti: "merendahkan / menghinakan" },
  { v1: "Debate", v2: "debated", v3: "debated", arti: "berdebat" },
  { v1: "Decay", v2: "decayed", v3: "decayed", arti: "membusuk / merosot" },
  { v1: "Declare", v2: "declared", v3: "declared", arti: "menyatakan" },
  { v1: "Decline", v2: "declined", v3: "declined", arti: "menolak / menurun" },
  { v1: "Decorate", v2: "decorated", v3: "decorated", arti: "menghiasi" },
  { v1: "Decoy", v2: "decoyed", v3: "decoyed", arti: "memikat / menjebak" },
  { v1: "Decry", v2: "decried", v3: "decried", arti: "mengecam" },
  { v1: "Defend", v2: "defended", v3: "defended", arti: "membela / mempertahankan" },
  { v1: "Defer", v2: "deferred", v3: "deferred", arti: "menunda" },
  { v1: "Deforest", v2: "deforested", v3: "deforested", arti: "menggunduli hutan" },
  { v1: "Defy", v2: "defied", v3: "defied", arti: "menentang / melawan" },
  { v1: "Degrade", v2: "degraded", v3: "degraded", arti: "merendahkan / menurunkan" },
  { v1: "Delete", v2: "deleted", v3: "deleted", arti: "menghapus" },
  { v1: "Deliver", v2: "delivered", v3: "delivered", arti: "mengantar / menyampaikan" },
  { v1: "Demobilize", v2: "demobilized", v3: "demobilized", arti: "membubarkan / mendemobilisasi" },
  { v1: "Deposit", v2: "deposited", v3: "deposited", arti: "menyetorkan / menyimpan" },
  { v1: "Deprive", v2: "deprived", v3: "deprived", arti: "merampas / mencabut" },
  { v1: "Deride", v2: "derided", v3: "derided", arti: "mengejek / mencemooh" },
  { v1: "Describe", v2: "described", v3: "described", arti: "menggambarkan / menjelaskan" },
  { v1: "Desert", v2: "deserted", v3: "deserted", arti: "meninggalkan / menggurun" },
  { v1: "Design", v2: "designed", v3: "designed", arti: "merancang / mendesain" },
  { v1: "Desolate", v2: "desolated", v3: "desolated", arti: "membinasakan / menghancurkan" },
  { v1: "Destroy", v2: "destroyed", v3: "destroyed", arti: "menghancurkan" },
  { v1: "Deter", v2: "deterred", v3: "deterred", arti: "mencegah / menghalangi" },
  { v1: "Deteriorate", v2: "deteriorated", v3: "deteriorated", arti: "memburuk / merosot" },
  { v1: "Detonate", v2: "detonated", v3: "detonated", arti: "meledakkan" },
  { v1: "Develop", v2: "developed", v3: "developed", arti: "mengembangkan" },
  { v1: "Devour", v2: "devoured", v3: "devoured", arti: "melahap / memakan habis" },
  { v1: "Dictate", v2: "dictated", v3: "dictated", arti: "mendikte" },
  { v1: "Digest", v2: "digested", v3: "digested", arti: "mencerna" },
  { v1: "Direct", v2: "directed", v3: "directed", arti: "mengarahkan" },
  { v1: "Discard", v2: "discarded", v3: "discarded", arti: "membuang / menyingkirkan" },
  { v1: "Discuss", v2: "discussed", v3: "discussed", arti: "mendiskusikan" },
  { v1: "Disparage", v2: "disparaged", v3: "disparaged", arti: "merendahkan / meremehkan" },
  { v1: "Dispatch", v2: "dispatched", v3: "dispatched", arti: "mengirim / memberangkatkan" },
  { v1: "Display", v2: "displayed", v3: "displayed", arti: "menampilkan / memamerkan" },
  { v1: "Disturb", v2: "disturbed", v3: "disturbed", arti: "mengganggu" },
  { v1: "Divide", v2: "divided", v3: "divided", arti: "membagi" },
  { v1: "Dominate", v2: "dominated", v3: "dominated", arti: "menguasai / mendominasi" },
  { v1: "Drag", v2: "dragged", v3: "dragged", arti: "menyeret" },
  { v1: "Drip", v2: "dripped", v3: "dripped", arti: "menetes" },
  { v1: "Dry", v2: "dried", v3: "dried", arti: "mengeringkan" },
  { v1: "Dun", v2: "dunned", v3: "dunned", arti: "menagih (hutang)" },
  { v1: "Duplicate", v2: "duplicated", v3: "duplicated", arti: "menggandakan" },
  { v1: "Dynamite", v2: "dynamited", v3: "dynamited", arti: "meledakkan (dengan dinamit)" },
  //Awalan E
  { v1: "Earn", v2: "earned", v3: "earned", arti: "menghasilkan / memperoleh" },
  { v1: "Edify", v2: "edified", v3: "edified", arti: "mendidik / memperbaiki moral" },
  { v1: "Edit", v2: "edited", v3: "edited", arti: "mengedit" },
  { v1: "Ejaculate", v2: "ejaculated", v3: "ejaculated", arti: "mengeluarkan (ejakulasi / seruan)" },
  { v1: "Eliminate", v2: "eliminated", v3: "eliminated", arti: "menghilangkan / menyingkirkan" },
  { v1: "Embezzle", v2: "embezzled", v3: "embezzled", arti: "menggelapkan (uang)" },
  { v1: "Empty", v2: "emptied", v3: "emptied", arti: "mengosongkan" },
  { v1: "Engross", v2: "engrossed", v3: "engrossed", arti: "menyerap perhatian" },
  { v1: "Enjoy", v2: "enjoyed", v3: "enjoyed", arti: "menikmati" },
  { v1: "Equip", v2: "equipped", v3: "equipped", arti: "melengkapi / membekali" },
  { v1: "Erase", v2: "erased", v3: "erased", arti: "menghapus" },
  { v1: "Erect", v2: "erected", v3: "erected", arti: "mendirikan" },
  { v1: "Erupt", v2: "erupted", v3: "erupted", arti: "meletus" },
  { v1: "Escalate", v2: "escalated", v3: "escalated", arti: "meningkat / memperburuk" },
  { v1: "Escape", v2: "escaped", v3: "escaped", arti: "melarikan diri" },
  { v1: "Escort", v2: "escorted", v3: "escorted", arti: "mengawal" },
  { v1: "Establish", v2: "established", v3: "established", arti: "mendirikan / menetapkan" },
  { v1: "Estimate", v2: "estimated", v3: "estimated", arti: "memperkirakan" },
  { v1: "Evacuate", v2: "evacuated", v3: "evacuated", arti: "mengungsi / mengevakuasi" },
  { v1: "Evade", v2: "evaded", v3: "evaded", arti: "menghindari" },
  { v1: "Evaluate", v2: "evaluated", v3: "evaluated", arti: "mengevaluasi / menilai" },
  { v1: "Evict", v2: "evicted", v3: "evicted", arti: "mengusir (dari rumah / tanah)" },
  { v1: "Examine", v2: "examined", v3: "examined", arti: "memeriksa" },
  { v1: "Excavate", v2: "excavated", v3: "excavated", arti: "menggali" },
  { v1: "Excel", v2: "excelled", v3: "excelled", arti: "unggul / sangat baik dalam" },
  { v1: "Exclaim", v2: "exclaimed", v3: "exclaimed", arti: "berseru" },
  { v1: "Exhibit", v2: "exhibited", v3: "exhibited", arti: "memamerkan" },
  { v1: "Expand", v2: "expanded", v3: "expanded", arti: "memperluas" },
  { v1: "Explain", v2: "explained", v3: "explained", arti: "menjelaskan" },
  { v1: "Explode", v2: "exploded", v3: "exploded", arti: "meledak" },
  { v1: "Export", v2: "exported", v3: "exported", arti: "mengekspor" },
  { v1: "Extricate", v2: "extricated", v3: "extricated", arti: "membebaskan" },
  //Awalan F
  { v1: "Face", v2: "faced", v3: "faced", arti: "menghadapi" },
  { v1: "Faint", v2: "fainted", v3: "fainted", arti: "pingsan" },
  { v1: "Falsify", v2: "falsified", v3: "falsified", arti: "memalsukan" },
  { v1: "Fart", v2: "farted", v3: "farted", arti: "kentut" },
  { v1: "Fib", v2: "fibbed", v3: "fibbed", arti: "berbohong kecil" },
  { v1: "Filter", v2: "filtered", v3: "filtered", arti: "menyaring" },
  { v1: "Flatter", v2: "flattered", v3: "flattered", arti: "memuji berlebihan" },
  { v1: "Flavour", v2: "flavoured", v3: "flavoured", arti: "memberi rasa" },
  { v1: "Flicker", v2: "flickered", v3: "flickered", arti: "berkedip / berkelap-kelip" },
  { v1: "Flimflam", v2: "flimflammed", v3: "flimflammed", arti: "menipu / memperdaya" },
  { v1: "Flip", v2: "flipped", v3: "flipped", arti: "membalik" },
  { v1: "Flirt", v2: "flirted", v3: "flirted", arti: "menggoda" },
  { v1: "Flog", v2: "flogged", v3: "flogged", arti: "mencambuk" },
  { v1: "Fluctuate", v2: "fluctuated", v3: "fluctuated", arti: "berfluktuasi" },
  { v1: "Focus", v2: "focused", v3: "focused", arti: "memusatkan" },
  { v1: "Fog", v2: "fogged", v3: "fogged", arti: "mengaburkan" },
  { v1: "Fold", v2: "folded", v3: "folded", arti: "melipat" },
  { v1: "Forecast", v2: "forecast / forecasted", v3: "forecast / forecasted", arti: "meramalkan" },
  { v1: "Formulate", v2: "formulated", v3: "formulated", arti: "merumuskan" },
  { v1: "Free", v2: "freed", v3: "freed", arti: "membebaskan" },
  { v1: "Frolic", v2: "frolicked", v3: "frolicked", arti: "bermain riang" },
  { v1: "Fry", v2: "fried", v3: "fried", arti: "menggoreng" },
  { v1: "Fulfil", v2: "fulfilled", v3: "fulfilled", arti: "memenuhi / menunaikan" },
  { v1: "Furbish", v2: "furbished", v3: "furbished", arti: "memperbaiki / memperbarui" },
  //Awalan G
  { v1: "Gag", v2: "gagged", v3: "gagged", arti: "membekap / mencekik / muntah tersedak" },
  { v1: "Garmish", v2: "garmished", v3: "garmished", arti: "menghias makanan" },
  { v1: "Gaze", v2: "gazed", v3: "gazed", arti: "menatap" },
  { v1: "Gesticulate", v2: "gesticulated", v3: "gesticulated", arti: "mengisyaratkan dengan tangan" },
  { v1: "Glitter", v2: "glittered", v3: "glittered", arti: "berkilauan" },
  { v1: "Grab", v2: "grabbed", v3: "grabbed", arti: "meraih / menangkap" },
  { v1: "Grib", v2: "gribbed", v3: "gribbed", arti: "menangkap (kata jarang)" },
  { v1: "Groan", v2: "groaned", v3: "groaned", arti: "merintih" },
  { v1: "Grumble", v2: "grumbled", v3: "grumbled", arti: "menggerutu" },
  { v1: "Guide", v2: "guided", v3: "guided", arti: "memandu" },
  { v1: "Gut", v2: "gutted", v3: "gutted", arti: "mengosongkan isi / memotong perut" },
  //Awalan H
  { v1: "Hallow", v2: "hallowed", v3: "hallowed", arti: "menguduskan" },
  { v1: "Handcuff", v2: "handcuffed", v3: "handcuffed", arti: "memborgol" },
  { v1: "Handicap", v2: "handicapped", v3: "handicapped", arti: "merugikan / menghalangi" },
  { v1: "Handle", v2: "handled", v3: "handled", arti: "menangani" },
  { v1: "Harry", v2: "harried", v3: "harried", arti: "mengganggu / menyerang terus-menerus" },
  { v1: "Hatch", v2: "hatched", v3: "hatched", arti: "menetaskan" },
  { v1: "Haunt", v2: "haunted", v3: "haunted", arti: "menghantui" },
  { v1: "Haze", v2: "hazed", v3: "hazed", arti: "mengaburkan / mengerjai" },
  { v1: "Help", v2: "helped", v3: "helped", arti: "membantu" },
  { v1: "Hesitate", v2: "hesitated", v3: "hesitated", arti: "ragu-ragu / bimbang" },
  { v1: "Hijack", v2: "hijacked", v3: "hijacked", arti: "membajak" },
  { v1: "Hop", v2: "hopped", v3: "hopped", arti: "melompat kecil" },
  { v1: "Horsewhip", v2: "horsewhipped", v3: "horsewhipped", arti: "mencambuk dengan pecut kuda" },
  { v1: "Howl", v2: "howled", v3: "howled", arti: "meraung / melolong" },
  { v1: "Hug", v2: "hugged", v3: "hugged", arti: "memeluk" },
  { v1: "Hum", v2: "hummed", v3: "hummed", arti: "bersenandung" },
  { v1: "Humidify", v2: "humidified", v3: "humidified", arti: "melembabkan" },
  { v1: "Hustle", v2: "hustled", v3: "hustled", arti: "berdesakan / mendorong" },
  //Awalan I
  { v1: "Identify", v2: "identified", v3: "identified", arti: "mengidentifikasi" },
  { v1: "Ignore", v2: "ignored", v3: "ignored", arti: "mengabaikan" },
  { v1: "Imagine", v2: "imagined", v3: "imagined", arti: "membayangkan" },
  { v1: "Imitate", v2: "imitated", v3: "imitated", arti: "meniru" },
  { v1: "Impel", v2: "impelled", v3: "impelled", arti: "mendorong / memaksa" },
  { v1: "Import", v2: "imported", v3: "imported", arti: "mengimpor" },
  { v1: "Improve", v2: "improved", v3: "improved", arti: "memperbaiki" },
  { v1: "Incur", v2: "incurred", v3: "incurred", arti: "menanggung / mengalami" },
  { v1: "Infect", v2: "infected", v3: "infected", arti: "menginfeksi" },
  { v1: "Infer", v2: "inferred", v3: "inferred", arti: "menyimpulkan" },
  { v1: "Inhale", v2: "inhaled", v3: "inhaled", arti: "menghirup" },
  { v1: "Inscribe", v2: "inscribed", v3: "inscribed", arti: "mengukir / menuliskan" },
  { v1: "Insist", v2: "insisted", v3: "insisted", arti: "bersikeras" },
  { v1: "Inspect", v2: "inspected", v3: "inspected", arti: "memeriksa" },
  { v1: "Install", v2: "installed", v3: "installed", arti: "menginstal / memasang" },
  { v1: "Instill", v2: "instilled", v3: "instilled", arti: "menanamkan (nilai/ajaran)" },
  { v1: "Instruct", v2: "instructed", v3: "instructed", arti: "mengajar / memberi instruksi" },
  { v1: "Integerate", v2: "integerated", v3: "integerated", arti: "menggabungkan / mengintegrasikan" }, // seharusnya "Integrate"
  { v1: "Inter", v2: "interred", v3: "interred", arti: "menguburkan" },
  { v1: "Interrupt", v2: "interrupted", v3: "interrupted", arti: "mengganggu / menyela" },
  { v1: "Invade", v2: "invaded", v3: "invaded", arti: "menyerbu / menginvasi" },
  { v1: "Invent", v2: "invented", v3: "invented", arti: "menciptakan" },
  { v1: "Invest", v2: "invested", v3: "invested", arti: "menginvestasikan" },
  { v1: "Invite", v2: "invited", v3: "invited", arti: "mengundang" },
  { v1: "Irrigate", v2: "irrigated", v3: "irrigated", arti: "mengairi / mengirigasi" },
  { v1: "Irritate", v2: "irritated", v3: "irritated", arti: "mengganggu / mengiritasi" },
  { v1: "Isolate", v2: "isolated", v3: "isolated", arti: "mengisolasi" },
  { v1: "Itemize", v2: "itemized", v3: "itemized", arti: "merinci" },
  //Awalan J
  { v1: "Jam", v2: "jammed", v3: "jammed", arti: "macet / menjepit" },
  { v1: "Jig", v2: "jigged", v3: "jigged", arti: "menari cepat (jig)" },
  { v1: "Jingle", v2: "jingled", v3: "jingled", arti: "berbunyi gemerincing" },
  { v1: "Jog", v2: "jogged", v3: "jogged", arti: "berjoging" },
  { v1: "Jolt", v2: "jolted", v3: "jolted", arti: "terguncang" },
  { v1: "Juggle", v2: "juggled", v3: "juggled", arti: "menyulap" },
  { v1: "Jumble", v2: "jumbled", v3: "jumbled", arti: "mengacak-acak / mengacaukan" },
  { v1: "Jump", v2: "jumped", v3: "jumped", arti: "melompat" },
  { v1: "Justify", v2: "justified", v3: "justified", arti: "membenarkan / mempertahankan" },
  { v1: "Jut", v2: "jutted", v3: "jutted", arti: "menonjol keluar" },
  { v1: "Juxtapose", v2: "juxtaposed", v3: "juxtaposed", arti: "menempatkan berdampingan" },
  //Awalan K
  { v1: "Kick", v2: "kicked", v3: "kicked", arti: "menendang" },
  { v1: "Kid", v2: "kidded", v3: "kidded", arti: "menggoda / bercanda" },
  { v1: "Kidnap", v2: "kidnapped", v3: "kidnapped", arti: "menculik" },
  { v1: "Kill", v2: "killed", v3: "killed", arti: "membunuh" },
  { v1: "Kiss", v2: "kissed", v3: "kissed", arti: "mencium" },
  { v1: "Knit", v2: "knit/knitted", v3: "knit/knitted", arti: "merajut / menyatu" },
  { v1: "Knock", v2: "knocked", v3: "knocked", arti: "mengetuk / memukul" },
  { v1: "Knot", v2: "knotted", v3: "knotted", arti: "mengikat simpul" },
  //Awalan L
  { v1: "Label", v2: "labeled", v3: "labeled", arti: "memberi label" },
  { v1: "Lament", v2: "lamented", v3: "lamented", arti: "meratapi" },
  { v1: "Land", v2: "landed", v3: "landed", arti: "mendarat" },
  { v1: "Lap", v2: "lapped", v3: "lapped", arti: "menjilat / putaran" },
  { v1: "Lash", v2: "lashed", v3: "lashed", arti: "mencambuk / mengikat" },
  { v1: "Launch", v2: "launched", v3: "launched", arti: "meluncurkan" },
  { v1: "Lavish", v2: "lavished", v3: "lavished", arti: "menghamburkan / bermurah hati" },
  { v1: "Legalize", v2: "legalized", v3: "legalized", arti: "melegalkan" },
  { v1: "Lessen", v2: "lessened", v3: "lessened", arti: "mengurangi" },
  { v1: "Levy", v2: "levied", v3: "levied", arti: "memungut (pajak)" },
  { v1: "Liberate", v2: "liberated", v3: "liberated", arti: "membebaskan" },
  { v1: "Lick", v2: "licked", v3: "licked", arti: "menjilat" },
  { v1: "Lift", v2: "lifted", v3: "lifted", arti: "mengangkat" },
  { v1: "Limit", v2: "limited", v3: "limited", arti: "membatasi" },
  { v1: "Liquefy", v2: "liquefied", v3: "liquefied", arti: "mencairkan" },
  { v1: "Listen", v2: "listened", v3: "listened", arti: "mendengarkan" },
  { v1: "Litter", v2: "littered", v3: "littered", arti: "mengotori / membuang sampah sembarangan" },
  { v1: "Load", v2: "loaded", v3: "loaded", arti: "memuat / mengisi" },
  { v1: "Lob", v2: "lobbed", v3: "lobbed", arti: "melempar (tinggi/melayang)" },
  { v1: "Localize", v2: "localized", v3: "localized", arti: "melokalisasi / menyesuaikan lokal" },
  { v1: "Lock", v2: "locked", v3: "locked", arti: "mengunci" },
  { v1: "Lodge", v2: "lodged", v3: "lodged", arti: "menitipkan / mengajukan" },
  { v1: "Loiter", v2: "loitered", v3: "loitered", arti: "berlalu-lalang / berkeliaran" },
  { v1: "Look", v2: "looked", v3: "looked", arti: "melihat / memandang" },
  { v1: "Lug", v2: "lugged", v3: "lugged", arti: "menyeret / memikul" },
  { v1: "Lunge", v2: "lunged", v3: "lunged", arti: "menerjang / menusuk" },
  { v1: "Lurk", v2: "lurked", v3: "lurked", arti: "bersembunyi / mengintai" },
  //Awalan M
  { v1: "Magnify", v2: "magnified", v3: "magnified", arti: "memperbesar" },
  { v1: "Mail", v2: "mailed", v3: "mailed", arti: "mengirim surat" },
  { v1: "Maintain", v2: "maintained", v3: "maintained", arti: "memelihara / mempertahankan" },
  { v1: "Maltreat", v2: "maltreated", v3: "maltreated", arti: "menyiksa / memperlakukan dengan buruk" },
  { v1: "Manage", v2: "managed", v3: "managed", arti: "mengelola" },
  { v1: "Manipulate", v2: "manipulated", v3: "manipulated", arti: "memanipulasi" },
  { v1: "Memorize", v2: "memorized", v3: "memorized", arti: "menghafal" },
  { v1: "Massage", v2: "massaged", v3: "massaged", arti: "memijat" },
  { v1: "Masturbate", v2: "masturbated", v3: "masturbated", arti: "masturbasi" },
  { v1: "Merge", v2: "merged", v3: "merged", arti: "menggabungkan" },
  { v1: "Mimic", v2: "mimicked", v3: "mimicked", arti: "menirukan" },
  { v1: "Misapply", v2: "misapplied", v3: "misapplied", arti: "menyalahgunakan / salah menerapkan" },
  { v1: "Mix", v2: "mixed", v3: "mixed", arti: "mencampur" },
  { v1: "Mock", v2: "mocked", v3: "mocked", arti: "mengejek" },
  { v1: "Mourn", v2: "mourned", v3: "mourned", arti: "berduka" },
  { v1: "Muzzle", v2: "muzzled", v3: "muzzled", arti: "memasang pelindung mulut (anjing) / membungkam" },
  //Awalan N
  { v1: "Nab", v2: "nabbed", v3: "nabbed", arti: "menangkap / menciduk" },
  { v1: "Nag", v2: "nagged", v3: "nagged", arti: "mengomel" },
  { v1: "Nap", v2: "napped", v3: "napped", arti: "tidur sebentar" },
  { v1: "Neglect", v2: "neglected", v3: "neglected", arti: "mengabaikan" },
  { v1: "Nip", v2: "nipped", v3: "nipped", arti: "mencubit / menggigit kecil" },
  { v1: "Notify", v2: "notified", v3: "notified", arti: "memberitahu / memberi tahu resmi" },
  { v1: "Nourish", v2: "nourished", v3: "nourished", arti: "memberi makan / menutrisi" },
  { v1: "Nullify", v2: "nullified", v3: "nullified", arti: "membatalkan / meniadakan" },
  { v1: "Number", v2: "numbered", v3: "numbered", arti: "memberi nomor" },
  { v1: "Nurse", v2: "nursed", v3: "nursed", arti: "merawat" },
  { v1: "Nurture", v2: "nurtured", v3: "nurtured", arti: "membesarkan / memelihara" },
  { v1: "Nuzzle", v2: "nuzzled", v3: "nuzzled", arti: "mengusap dengan hidung / membelai" },
  //Awalan O
  { v1: "Obey", v2: "obeyed", v3: "obeyed", arti: "menaati / mematuhi" },
  { v1: "Obscure", v2: "obscured", v3: "obscured", arti: "mengaburkan" },
  { v1: "Observe", v2: "observed", v3: "observed", arti: "mengamati" },
  { v1: "Occur", v2: "occurred", v3: "occurred", arti: "terjadi" },
  { v1: "Offend", v2: "offended", v3: "offended", arti: "menyinggung / menyinggung perasaan" },
  { v1: "Offer", v2: "offered", v3: "offered", arti: "menawarkan" },
  { v1: "Open", v2: "opened", v3: "opened", arti: "membuka" },
  { v1: "Operate", v2: "operated", v3: "operated", arti: "mengoperasikan" },
  { v1: "Oppress", v2: "oppressed", v3: "oppressed", arti: "menindas" },
  { v1: "Orbit", v2: "orbited", v3: "orbited", arti: "beredar / mengorbit" },
  { v1: "Organize", v2: "organized", v3: "organized", arti: "mengorganisir / mengatur" },
  { v1: "Outfit", v2: "outfitted", v3: "outfitted", arti: "membekali / melengkapi" },
  { v1: "Overcrowd", v2: "overcrowded", v3: "overcrowded", arti: "terlalu padat / memadati berlebihan" },
  { v1: "Oxidize", v2: "oxidized", v3: "oxidized", arti: "mengoksidasi" },
  //Awalan P
  { v1: "Pacify", v2: "pacified", v3: "pacified", arti: "menenangkan / mendamaikan" },
  { v1: "Paint", v2: "painted", v3: "painted", arti: "melukis / mengecat" },
  { v1: "Panic", v2: "panicked", v3: "panicked", arti: "panik / menjadi panik" },
  { v1: "Parry", v2: "parried", v3: "parried", arti: "menangkis" },
  { v1: "Pass", v2: "passed", v3: "passed", arti: "melewati / lulus" },
  { v1: "Pat", v2: "patted", v3: "patted", arti: "menepuk" },
  { v1: "Peep", v2: "peeped", v3: "peeped", arti: "mengintip" },
  { v1: "Penalize", v2: "penalized", v3: "penalized", arti: "memberi hukuman / penalti" },
  { v1: "Perform", v2: "performed", v3: "performed", arti: "melakukan / tampil" },
  { v1: "Perspire", v2: "perspired", v3: "perspired", arti: "berkeringat" },
  { v1: "Pet", v2: "petted", v3: "petted", arti: "membelai (hewan)" },
  { v1: "Phone", v2: "phoned", v3: "phoned", arti: "menelepon" },
  { v1: "Photocopy", v2: "photocopied", v3: "photocopied", arti: "memfotokopi" },
  { v1: "Pin", v2: "pinned", v3: "pinned", arti: "menyematkan / menjepit" },
  { v1: "Pit", v2: "pitted", v3: "pitted", arti: "membuat lubang / melubangi" },
  { v1: "Play", v2: "played", v3: "played", arti: "bermain" },
  { v1: "Pleat", v2: "pleated", v3: "pleated", arti: "melipat (kain)" },
  { v1: "Plot", v2: "plotted", v3: "plotted", arti: "merencanakan / bersekongkol" },
  { v1: "Polish", v2: "polished", v3: "polished", arti: "memoles / mengkilapkan" },
  { v1: "Postdate", v2: "postdated", v3: "postdated", arti: "memberi tanggal mundur" },
  { v1: "Postpone", v2: "postponed", v3: "postponed", arti: "menunda" },
  { v1: "Prepare", v2: "prepared", v3: "prepared", arti: "mempersiapkan" },
  { v1: "Present", v2: "presented", v3: "presented", arti: "menyajikan / menghadirkan" },
  { v1: "Print", v2: "printed", v3: "printed", arti: "mencetak" },
  { v1: "Process", v2: "processed", v3: "processed", arti: "memproses" },
  { v1: "Propel", v2: "propelled", v3: "propelled", arti: "mendorong / menggerakkan" },
  { v1: "Provide", v2: "provided", v3: "provided", arti: "menyediakan" },
  { v1: "Pull", v2: "pulled", v3: "pulled", arti: "menarik" },
  { v1: "Purify", v2: "purified", v3: "purified", arti: "memurnikan" },
  { v1: "Push", v2: "pushed", v3: "pushed", arti: "mendorong" },
  { v1: "Putrefy", v2: "putrefied", v3: "putrefied", arti: "membusukkan" },
  //Awalan Q
  { v1: "Quack", v2: "quacked", v3: "quacked", arti: "berkwek (bebek) / berpura-pura jadi ahli" },
  { v1: "Quake", v2: "quaked", v3: "quaked", arti: "gemetar / bergetar" },
  { v1: "Qualify", v2: "qualified", v3: "qualified", arti: "memenuhi syarat / mengkualifikasi" },
  { v1: "Quantify", v2: "quantified", v3: "quantified", arti: "mengukur jumlah" },
  { v1: "Quarrel", v2: "quarreled", v3: "quarreled", arti: "bertengkar" },
  { v1: "Quarry", v2: "quarried", v3: "quarried", arti: "menambang batu" },
  { v1: "Quell", v2: "quelled", v3: "quelled", arti: "menekan / meredakan" },
  { v1: "Query", v2: "queried", v3: "queried", arti: "mempertanyakan / menanyakan" },
  { v1: "Question", v2: "questioned", v3: "questioned", arti: "mempertanyakan / menginterogasi" },
  { v1: "Quicken", v2: "quickened", v3: "quickened", arti: "mempercepat / menghidupkan" },
  { v1: "Quip", v2: "quipped", v3: "quipped", arti: "melontarkan lelucon" },
  { v1: "Quiz", v2: "quizzed", v3: "quizzed", arti: "mengkuis / menguji pengetahuan" },
  { v1: "Quote", v2: "quoted", v3: "quoted", arti: "mengutip" },
  //Awalan R
  { v1: "Radiate", v2: "radiated", v3: "radiated", arti: "memancarkan" },
  { v1: "Rag", v2: "ragged", v3: "ragged", arti: "menggoda / mengolok-olok" },
  { v1: "Raid", v2: "raided", v3: "raided", arti: "merazia / menyerbu" },
  { v1: "Rape", v2: "raped", v3: "raped", arti: "memperkosa" },
  { v1: "Ratify", v2: "ratified", v3: "ratified", arti: "meratifikasi / mengesahkan" },
  { v1: "Rebel", v2: "rebelled", v3: "rebelled", arti: "memberontak" },
  { v1: "Rectify", v2: "rectified", v3: "rectified", arti: "membetulkan / memperbaiki" },
  { v1: "Refresh", v2: "refreshed", v3: "refreshed", arti: "menyegarkan" },
  { v1: "Regulate", v2: "regulated", v3: "regulated", arti: "mengatur" },
  { v1: "Repair", v2: "repaired", v3: "repaired", arti: "memperbaiki" },
  { v1: "Reply", v2: "replied", v3: "replied", arti: "membalas / menjawab" },
  { v1: "Report", v2: "reported", v3: "reported", arti: "melaporkan" },
  { v1: "Review", v2: "reviewed", v3: "reviewed", arti: "mengulas / meninjau" },
  { v1: "Rob", v2: "robbed", v3: "robbed", arti: "merampok" },
  { v1: "Rub", v2: "rubbed", v3: "rubbed", arti: "menggosok" },
  { v1: "Rumble", v2: "rumbled", v3: "rumbled", arti: "bergemuruh" },
  //Awalan S
  { v1: "Sabotage", v2: "sabotaged", v3: "sabotaged", arti: "mensabotase" },
  { v1: "Sail", v2: "sailed", v3: "sailed", arti: "berlayar" },
  { v1: "Sanctify", v2: "sanctified", v3: "sanctified", arti: "menguduskan / mensucikan" },
  { v1: "Satirize", v2: "satirized", v3: "satirized", arti: "menyindir / menyatir" },
  { v1: "Satisfy", v2: "satisfied", v3: "satisfied", arti: "memuaskan" },
  { v1: "Scan", v2: "scanned", v3: "scanned", arti: "memindai / meneliti" },
  { v1: "Scurry", v2: "scurried", v3: "scurried", arti: "berlari terburu-buru" },
  { v1: "Seduce", v2: "seduced", v3: "seduced", arti: "merayu / menggoda" },
  { v1: "Settle", v2: "settled", v3: "settled", arti: "menyelesaikan / menetap" },
  { v1: "Shellac", v2: "shellacked", v3: "shellacked", arti: "melapisi dengan pernis" },
  { v1: "Ship", v2: "shipped", v3: "shipped", arti: "mengirim / mengapalkan" },
  { v1: "Simplify", v2: "simplified", v3: "simplified", arti: "menyederhanakan" },
  { v1: "Sip", v2: "sipped", v3: "sipped", arti: "menyeruput" },
  { v1: "Smoke", v2: "smoked", v3: "smoked", arti: "merokok / mengasapi" },
  { v1: "Snap", v2: "snapped", v3: "snapped", arti: "mematahkan / menjepret" },
  { v1: "Snore", v2: "snored", v3: "snored", arti: "mengorok / mendengkur" },
  { v1: "Spray", v2: "sprayed", v3: "sprayed", arti: "menyemprot" },
  { v1: "Squat", v2: "squatted", v3: "squatted", arti: "jongkok" },
  { v1: "Stabilize", v2: "stabilized", v3: "stabilized", arti: "menstabilkan" },
  { v1: "Stop", v2: "stopped", v3: "stopped", arti: "berhenti" },
  { v1: "Supply", v2: "supplied", v3: "supplied", arti: "menyediakan / memasok" },
  { v1: "Swish", v2: "swished", v3: "swished", arti: "menderu / mendesis halus" },
  //Awalan T
  { v1: "Tackle", v2: "tackled", v3: "tackled", arti: "menangani / menubruk (olahraga)" },
  { v1: "Talk", v2: "talked", v3: "talked", arti: "berbicara" },
  { v1: "Tan", v2: "tanned", v3: "tanned", arti: "menghitamkan kulit / menyamak" },
  { v1: "Telegraph", v2: "telegraphed", v3: "telegraphed", arti: "mengirim telegram" },
  { v1: "Telephone", v2: "telephoned", v3: "telephoned", arti: "menelepon" },
  { v1: "Televise", v2: "televised", v3: "televised", arti: "menyiarkan lewat televisi" },
  { v1: "Terrorize", v2: "terrorized", v3: "terrorized", arti: "meneror" },
  { v1: "Testify", v2: "testified", v3: "testified", arti: "bersaksi" },
  { v1: "Thicken", v2: "thickened", v3: "thickened", arti: "mengentalkan / menebalkan" },
  { v1: "Thin", v2: "thinned", v3: "thinned", arti: "menipiskan" },
  { v1: "Throb", v2: "throbbed", v3: "throbbed", arti: "berdenyut" },
  { v1: "Tickle", v2: "tickled", v3: "tickled", arti: "menggelitik" },
  { v1: "Tie", v2: "tied", v3: "tied", arti: "mengikat" },
  { v1: "Torture", v2: "tortured", v3: "tortured", arti: "menyiksa" },
  { v1: "Train", v2: "trained", v3: "trained", arti: "melatih" },
  { v1: "Trap", v2: "trapped", v3: "trapped", arti: "menjebak" },
  { v1: "Travel", v2: "traveled", v3: "traveled", arti: "bepergian" },
  { v1: "Trim", v2: "trimmed", v3: "trimmed", arti: "memangkas / merapikan" },
  { v1: "Type", v2: "typed", v3: "typed", arti: "mengetik" },
  { v1: "Tyrannize", v2: "tyrannized", v3: "tyrannized", arti: "menindas" },
  //Awalan U
  { v1: "Umpire", v2: "umpired", v3: "umpired", arti: "menjadi wasit" },
  { v1: "Uncork", v2: "uncorked", v3: "uncorked", arti: "membuka sumbat botol" },
  { v1: "Underline", v2: "underlined", v3: "underlined", arti: "menggarisbawahi" },
  { v1: "Unify", v2: "unified", v3: "unified", arti: "menyatukan" },
  { v1: "Unlock", v2: "unlocked", v3: "unlocked", arti: "membuka kunci" },
  { v1: "Unpin", v2: "unpinned", v3: "unpinned", arti: "melepaskan pin / menyemat" },
  { v1: "Unplug", v2: "unplugged", v3: "unplugged", arti: "mencabut colokan" },
  { v1: "Unveil", v2: "unveiled", v3: "unveiled", arti: "mengungkapkan / membuka tabir" },
  { v1: "Unzip", v2: "unzipped", v3: "unzipped", arti: "membuka resleting" },
  { v1: "Update", v2: "updated", v3: "updated", arti: "memperbarui" },
  { v1: "Urge", v2: "urged", v3: "urged", arti: "mendesak / mendorong" },
  { v1: "Urinate", v2: "urinated", v3: "urinated", arti: "buang air kecil" },
  { v1: "Use", v2: "used", v3: "used", arti: "menggunakan" },
  { v1: "Usurp", v2: "usurped", v3: "usurped", arti: "merampas / merebut secara paksa" },
  { v1: "Utilize", v2: "utilized", v3: "utilized", arti: "memanfaatkan" },
  { v1: "Utter", v2: "uttered", v3: "uttered", arti: "mengucapkan" },
  //Awalan V
  { v1: "Vacillate", v2: "vacillated", v3: "vacillated", arti: "bimbang / ragu-ragu" },
  { v1: "Vanquish", v2: "vanquished", v3: "vanquished", arti: "menaklukkan" },
  { v1: "Vanish", v2: "vanished", v3: "vanished", arti: "menghilang" },
  { v1: "Vary", v2: "varied", v3: "varied", arti: "bervariasi / berubah" },
  { v1: "Veil", v2: "veiled", v3: "veiled", arti: "menutupi" },
  { v1: "Vend", v2: "vended", v3: "vended", arti: "menjual" },
  { v1: "Venerate", v2: "venerated", v3: "venerated", arti: "menghormati / memuja" },
  { v1: "Ventilate", v2: "ventilated", v3: "ventilated", arti: "memberi ventilasi / mengalirkan udara" },
  { v1: "Verbalize", v2: "verbalized", v3: "verbalized", arti: "mengungkapkan dengan kata-kata" },
  { v1: "Verify", v2: "verified", v3: "verified", arti: "memverifikasi / memastikan" },
  { v1: "Versify", v2: "versified", v3: "versified", arti: "menulis dalam bentuk puisi" },
  { v1: "Veto", v2: "vetoed", v3: "vetoed", arti: "memveto / menolak" },
  { v1: "Vex", v2: "vexed", v3: "vexed", arti: "mengganggu / menyulitkan" },
  { v1: "Vibrate", v2: "vibrated", v3: "vibrated", arti: "bergetar" },
  { v1: "Victimize", v2: "victimized", v3: "victimized", arti: "mengorbankan / menindas" },
  { v1: "Vie", v2: "vied", v3: "vied", arti: "bersaing" },
  { v1: "View", v2: "viewed", v3: "viewed", arti: "melihat / memandang" },
  { v1: "Vilify", v2: "vilified", v3: "vilified", arti: "memfitnah / menjelekkan" },
  { v1: "Vindicate", v2: "vindicated", v3: "vindicated", arti: "membenarkan / membebaskan dari tuduhan" },
  { v1: "Violate", v2: "violated", v3: "violated", arti: "melanggar" },
  { v1: "Visit", v2: "visited", v3: "visited", arti: "mengunjungi" },
  { v1: "Visualize", v2: "visualized", v3: "visualized", arti: "membayangkan / memvisualisasikan" },
  { v1: "Vote", v2: "voted", v3: "voted", arti: "memilih / memberikan suara" },
  { v1: "Vulcanize", v2: "vulcanized", v3: "vulcanized", arti: "memvulkanisir (karet)" },
  //Awalan W
  { v1: "Wag", v2: "wagged", v3: "wagged", arti: "mengibaskan / menggoyangkan" },
  { v1: "Wait", v2: "waited", v3: "waited", arti: "menunggu" },
  { v1: "Walk", v2: "walked", v3: "walked", arti: "berjalan" },
  { v1: "Wallop", v2: "walloped", v3: "walloped", arti: "menghantam / memukul keras" },
  { v1: "Wash", v2: "washed", v3: "washed", arti: "mencuci" },
  { v1: "Waste", v2: "wasted", v3: "wasted", arti: "membuang / menyia-nyiakan" },
  { v1: "Watch", v2: "watched", v3: "watched", arti: "menonton / mengawasi" },
  { v1: "Weld", v2: "welded", v3: "welded", arti: "mengelas" },
  { v1: "Whip", v2: "whipped", v3: "whipped", arti: "mencambuk / mengocok" },
  { v1: "Whisper", v2: "whispered", v3: "whispered", arti: "berbisik" },
  { v1: "Whistle", v2: "whistled", v3: "whistled", arti: "bersiul" },
  { v1: "Wiggle", v2: "wiggled", v3: "wiggled", arti: "menggeliat / menggoyang" },
  { v1: "Woo", v2: "wooed", v3: "wooed", arti: "membujuk / merayu" },
  { v1: "Worry", v2: "worried", v3: "worried", arti: "khawatir / mencemaskan" },
  { v1: "Wrestle", v2: "wrestled", v3: "wrestled", arti: "bergulat" },
  { v1: "Wriggle", v2: "wriggled", v3: "wriggled", arti: "menggelinjang / menggeliat" },
  //Awalan Y
  { v1: "Yank", v2: "yanked", v3: "yanked", arti: "menarik dengan keras" },
  { v1: "Yap", v2: "yapped", v3: "yapped", arti: "menggonggong kecil / cerewet" },
  { v1: "Yawn", v2: "yawned", v3: "yawned", arti: "mengantuk / menguap" },
  { v1: "Yell", v2: "yelled", v3: "yelled", arti: "berteriak" },
  { v1: "Yield", v2: "yielded", v3: "yielded", arti: "menyerah / menghasilkan" },
  { v1: "Yowl", v2: "yowled", v3: "yowled", arti: "meraung / melolong" },
  //Awalan Z
  { v1: "Zigzag", v2: "zigzagged", v3: "zigzagged", arti: "bergerak berkelok-kelok" },
  { v1: "Zip", v2: "zipped", v3: "zipped", arti: "menutup dengan resleting" },
  { v1: "Zipper", v2: "zippered", v3: "zippered", arti: "menutup dengan ritsleting" },
  { v1: "Zoom", v2: "zoomed", v3: "zoomed", arti: "melaju cepat / memperbesar tampilan" },
  //Irregular Verb
  //Awalan A
  { v1: "Abide", v2: "abode/abided", v3: "abode/abided", arti: "menaati / mematuhi" },
  { v1: "Arise", v2: "arose", v3: "arisen", arti: "muncul / timbul" },
  { v1: "Awake", v2: "awoke/awakened", v3: "awoken/awakened", arti: "bangun" },
  //Awalan B
  { v1: "Backslide", v2: "backslid", v3: "backslid/backslidden", arti: "kembali ke kebiasaan buruk" },
  { v1: "Be (am, is)", v2: "was", v3: "been", arti: "adalah (tunggal)" },
  { v1: "Be (are)", v2: "were", v3: "been", arti: "adalah (jamak)" },
  { v1: "Bear", v2: "bore", v3: "borne/born", arti: "menanggung / melahirkan" },
  { v1: "Beat", v2: "beat", v3: "beaten/beat", arti: "memukul" },
  { v1: "Become", v2: "became", v3: "become", arti: "menjadi" },
  { v1: "Befall", v2: "befell", v3: "befallen", arti: "menimpa" },
  { v1: "Beget", v2: "begot", v3: "begotten/begot", arti: "menyebabkan / memperanakkan" },
  { v1: "Begin", v2: "began", v3: "begun", arti: "memulai" },
  { v1: "Behold", v2: "beheld", v3: "beheld", arti: "menyaksikan / memandang" },
  { v1: "Bend", v2: "bent", v3: "bent", arti: "membengkokkan" },
  { v1: "Bereave", v2: "bereft/bereaved", v3: "bereft/bereaved", arti: "merampas / kehilangan" },
  { v1: "Beseech", v2: "besought/beseeched", v3: "besought/beseeched", arti: "memohon" },
  { v1: "Beset", v2: "beset", v3: "beset", arti: "mengepung / menyerang" },
  { v1: "Bet", v2: "bet/betted", v3: "bet/betted", arti: "bertaruh" },
  { v1: "Betake", v2: "betook", v3: "betaken", arti: "pergi menuju / menempuh" },
  { v1: "Bethink", v2: "bethought", v3: "bethought", arti: "merenungkan / mengingat kembali" },
  { v1: "Bid", v2: "bade/bid", v3: "bidden/bid", arti: "menawar / memerintahkan" },
  { v1: "Bide", v2: "bided/bode", v3: "bided/bidden", arti: "menunggu / tinggal" },
  { v1: "Bind", v2: "bound", v3: "bound", arti: "mengikat" },
  { v1: "Bite", v2: "bit", v3: "bitten", arti: "menggigit" },
  { v1: "Bleed", v2: "bled", v3: "bled", arti: "berdarah" },
  { v1: "Blend", v2: "blended/blent", v3: "blended/blent", arti: "mencampur" },
  { v1: "Bless", v2: "blessed/blest", v3: "blessed/blest", arti: "memberkati" },
  { v1: "Blow", v2: "blew", v3: "blown", arti: "meniup" },
  { v1: "Break", v2: "broke", v3: "broken", arti: "memecahkan / merusak" },
  { v1: "Breed", v2: "bred", v3: "bred", arti: "membiakkan / berkembang biak" },
  { v1: "Bring", v2: "brought", v3: "brought", arti: "membawa" },
  { v1: "Broadcast", v2: "broadcast/broadcasted", v3: "broadcast/broadcasted", arti: "menyiarkan" },
  { v1: "Browbeat", v2: "browbeat", v3: "browbeaten/browbeat", arti: "mengintimidasi" },
  { v1: "Build", v2: "built", v3: "built", arti: "membangun" },
  { v1: "Burn", v2: "burned/burnt", v3: "burned/burnt", arti: "membakar" },
  { v1: "Burst", v2: "burst", v3: "burst", arti: "meledak / pecah" },
  { v1: "Buy", v2: "bought", v3: "bought", arti: "membeli" },
  //Awalan C
  { v1: "Can", v2: "could", v3: "been able", arti: "bisa / mampu" },
  { v1: "Cast", v2: "cast", v3: "cast", arti: "melempar / mencampakkan" },
  { v1: "Catch", v2: "caught", v3: "caught", arti: "menangkap" },
  { v1: "Chide", v2: "chided/chid", v3: "chided/chidden", arti: "menegur / memarahi" },
  { v1: "Choose", v2: "chose", v3: "chosen", arti: "memilih" },
  { v1: "Cleave", v2: "cleft/clove/cleaved", v3: "cleft/cloven/cleaved", arti: "membelah / berpegang teguh" },
  { v1: "Cling", v2: "clung", v3: "clung", arti: "melekat / bergantung" },
  { v1: "Clothe", v2: "clothed/clad", v3: "clothed/clad", arti: "mengenakan pakaian" },
  { v1: "Come", v2: "came", v3: "come", arti: "datang" },
  { v1: "Cost", v2: "cost", v3: "cost", arti: "berharga / menelan biaya" },
  { v1: "Creep", v2: "crept", v3: "crept", arti: "merayap" },
  { v1: "Crow", v2: "crowed/crew", v3: "crowed", arti: "berkokok / bersorak" },
  { v1: "Cut", v2: "cut", v3: "cut", arti: "memotong" },
  //Awalan D
  { v1: "Dare", v2: "dared/durst", v3: "dared", arti: "berani / menantang" },
  { v1: "Deal", v2: "dealt", v3: "dealt", arti: "membagi / berurusan" },
  { v1: "Dig", v2: "dug", v3: "dug", arti: "menggali" },
  { v1: "Do", v2: "did", v3: "done", arti: "melakukan" },
  { v1: "Draw", v2: "drew", v3: "drawn", arti: "menggambar / menarik" },
  { v1: "Dream", v2: "dreamed/dreamt", v3: "dreamed/dreamt", arti: "bermimpi" },
  { v1: "Drink", v2: "drank", v3: "drunk", arti: "minum" },
  { v1: "Drive", v2: "drove", v3: "driven", arti: "mengemudi / mengendarai" },
  { v1: "Dwell", v2: "dwelt/dwelled", v3: "dwelt/dwelled", arti: "tinggal / mendiami" },
  //Awalan E
  { v1: "Eat", v2: "ate", v3: "eaten", arti: "makan" },
  //Awalan F
  { v1: "Fall", v2: "fell", v3: "fallen", arti: "jatuh" },
  { v1: "Feed", v2: "fed", v3: "fed", arti: "memberi makan" },
  { v1: "Feel", v2: "felt", v3: "felt", arti: "merasa" },
  { v1: "Fight", v2: "fought", v3: "fought", arti: "bertarung / berkelahi" },
  { v1: "Find", v2: "found", v3: "found", arti: "menemukan" },
  { v1: "Flee", v2: "fled", v3: "fled", arti: "melarikan diri" },
  { v1: "Fling", v2: "flung", v3: "flung", arti: "melempar" },
  { v1: "Fly", v2: "flew", v3: "flown", arti: "terbang" },
  { v1: "Forbear", v2: "forbore", v3: "forborne", arti: "menahan diri" },
  { v1: "Forbid", v2: "forbade/forbad", v3: "forbidden", arti: "melarang" },
  { v1: "Forecast", v2: "forecast/forecasted", v3: "forecast/forecasted", arti: "meramalkan" },
  { v1: "Forego", v2: "forewent", v3: "foregone", arti: "melepaskan / mendahului" },
  { v1: "Foresee", v2: "foresaw", v3: "foreseen", arti: "meramalkan / melihat sebelumnya" },
  { v1: "Foretell", v2: "foretold", v3: "foretold", arti: "meramalkan / menubuatkan" },
  { v1: "Forget", v2: "forgot", v3: "forgotten", arti: "melupakan" },
  { v1: "Forgive", v2: "forgave", v3: "forgiven", arti: "memaafkan" },
  { v1: "Forsake", v2: "forsook", v3: "forsaken", arti: "meninggalkan / mengabaikan" },
  { v1: "Forswear", v2: "forswore", v3: "forsworn", arti: "bersumpah untuk meninggalkan" },
  { v1: "Freeze", v2: "froze", v3: "frozen", arti: "membeku" },
  //Awalan G
  { v1: "Gainsay", v2: "gainsaid", v3: "gainsaid", arti: "menyangkal / membantah" },
  { v1: "Get", v2: "got", v3: "got/gotten", arti: "mendapatkan" },
  { v1: "Gild", v2: "gilt/gilded", v3: "gilt/gilded", arti: "melapisi emas" },
  { v1: "Gird", v2: "girt/girded", v3: "girt/girded", arti: "melilit / mengikat pinggang" },
  { v1: "Give", v2: "gave", v3: "given", arti: "memberikan" },
  { v1: "Go", v2: "went", v3: "gone", arti: "pergi" },
  { v1: "Grind", v2: "ground", v3: "ground", arti: "menggiling / mengasah" },
  { v1: "Grow", v2: "grew", v3: "grown", arti: "tumbuh" },
  //Awalan H
  { v1: "Hang", v2: "hung/hanged", v3: "hung/hanged", arti: "menggantung" },
  { v1: "Have/Has", v2: "had", v3: "had", arti: "memiliki" },
  { v1: "Hear", v2: "heard", v3: "heard", arti: "mendengar" },
  { v1: "Heave", v2: "heaved/hove", v3: "heaved/hove", arti: "mengangkat berat" },
  { v1: "Hew", v2: "hewed", v3: "hewn/hewed", arti: "menebang / memahat" },
  { v1: "Hide", v2: "hid", v3: "hidden", arti: "bersembunyi / menyembunyikan" },
  { v1: "Hit", v2: "hit", v3: "hit", arti: "memukul" },
  { v1: "Hold", v2: "held", v3: "held", arti: "memegang / menahan" },
  { v1: "Hurt", v2: "hurt", v3: "hurt", arti: "melukai / menyakiti" },
  //Awalan I
  { v1: "Inlay", v2: "inlaid", v3: "inlaid", arti: "menyisipkan / melapisi" },
  //Awalan K
  { v1: "Keep", v2: "kept", v3: "kept", arti: "menyimpan / menjaga" },
  { v1: "Kneel", v2: "knelt/kneeled", v3: "knelt/kneeled", arti: "berlutut" },
  { v1: "Knit", v2: "knit/knitted", v3: "knit/knitted", arti: "merajut" },
  { v1: "Know", v2: "knew", v3: "known", arti: "mengetahui / mengenal" },
  //Awalan L
  { v1: "Lay", v2: "laid", v3: "laid", arti: "meletakkan" },
  { v1: "Lead", v2: "led", v3: "led", arti: "memimpin / menuntun" },
  { v1: "Lean", v2: "leant/leaned", v3: "leant/leaned", arti: "bersandar / condong" },
  { v1: "Leap", v2: "leapt/leaped", v3: "leapt/leaped", arti: "melompat" },
  { v1: "Learn", v2: "learnt/learned", v3: "learnt/learned", arti: "belajar" },
  { v1: "Leave", v2: "left", v3: "left", arti: "meninggalkan" },
  { v1: "Lend", v2: "lent", v3: "lent", arti: "meminjamkan" },
  { v1: "Let", v2: "let", v3: "let", arti: "membiarkan / menyewakan" },
  { v1: "Lie", v2: "lay", v3: "lain", arti: "berbaring" },
  { v1: "Light", v2: "lit/lighted", v3: "lit/lighted", arti: "menyalakan / menerangi" },
  { v1: "Lose", v2: "lost", v3: "lost", arti: "kehilangan" },
  //Awalan M
  { v1: "Make", v2: "made", v3: "made", arti: "membuat" },
  { v1: "May", v2: "might", v3: "-", arti: "mungkin / boleh" },
  { v1: "Mean", v2: "meant", v3: "meant", arti: "bermaksud / berarti" },
  { v1: "Meet", v2: "met", v3: "met", arti: "bertemu" },
  { v1: "Melt", v2: "melted", v3: "molten/melted", arti: "mencair" },
  { v1: "Misdeal", v2: "misdealt", v3: "misdealt", arti: "membagi salah (kartu)" },
  { v1: "Mislay", v2: "mislaid", v3: "mislaid", arti: "salah menaruh" },
  { v1: "Mislead", v2: "misled", v3: "misled", arti: "menyesatkan / menipu" },
  { v1: "Mistake", v2: "mistook", v3: "mistaken", arti: "salah sangka" },
  { v1: "Misunderstand", v2: "misunderstood", v3: "misunderstood", arti: "salah paham" },
  { v1: "Mow", v2: "mowed", v3: "mown/mowed", arti: "memotong rumput" },
  { v1: "Must", v2: "-", v3: "-", arti: "harus" },
  //Awalan O
  { v1: "Ought", v2: "-", v3: "-", arti: "seharusnya" },
  { v1: "Outbid", v2: "outbid", v3: "outbid", arti: "menawar lebih tinggi" },
  { v1: "Outdo", v2: "outdid", v3: "outdone", arti: "mengungguli / melebihi" },
  { v1: "Outgrow", v2: "outgrew", v3: "outgrown", arti: "tumbuh melebihi / meninggalkan" },
  { v1: "Outrun", v2: "outran", v3: "outrun", arti: "berlari lebih cepat" },
  { v1: "Outshine", v2: "outshone", v3: "outshone", arti: "mengalahkan dengan cemerlang" },
  { v1: "Outspread", v2: "outspread", v3: "outspread", arti: "membentangkan / menyebarkan" },
  { v1: "Outwear", v2: "outwore", v3: "outworn", arti: "menghabiskan / melampaui masa pakai" },
  { v1: "Overbear", v2: "overbore", v3: "overborne", arti: "menindas / menguasai" },
  { v1: "Overcast", v2: "overcast", v3: "overcast", arti: "mendung / menutupi" },
  { v1: "Overcome", v2: "overcame", v3: "overcome", arti: "mengatasi / menaklukkan" },
  { v1: "Overdo", v2: "overdid", v3: "overdone", arti: "berlebihan / terlalu banyak" },
  { v1: "Overdraw", v2: "overdrew", v3: "overdrawn", arti: "menarik melebihi saldo" },
  { v1: "Overeat", v2: "overate", v3: "overeaten", arti: "makan terlalu banyak" },
  { v1: "Overfeed", v2: "overfed", v3: "overfed", arti: "memberi makan terlalu banyak" },
  { v1: "Overhang", v2: "overhung", v3: "overhung", arti: "menjulang / menggantung" },
  { v1: "Overhear", v2: "overheard", v3: "overheard", arti: "mendengar tanpa sengaja" },
  { v1: "Overlay", v2: "overlaid", v3: "overlaid", arti: "melapisi / menutupi" },
  { v1: "Override", v2: "overrode", v3: "overridden", arti: "mengabaikan / menolak" },
  { v1: "Overrun", v2: "overran", v3: "overrun", arti: "melampaui / membanjiri" },
  { v1: "Oversee", v2: "oversaw", v3: "overseen", arti: "mengawasi" },
  { v1: "Oversleep", v2: "overslept", v3: "overslept", arti: "terlalu lama tidur" },
  { v1: "Overtake", v2: "overtook", v3: "overtaken", arti: "menyalip / menyusul" },
  { v1: "Overthrow", v2: "overthrew", v3: "overthrown", arti: "menumbangkan / menggulingkan" },
  //Awalan P
  { v1: "Partake", v2: "partook", v3: "partaken", arti: "ikut serta / ambil bagian" },
  { v1: "Pay", v2: "paid", v3: "paid", arti: "membayar" },
  { v1: "Put", v2: "put", v3: "put", arti: "meletakkan / menaruh" },
  //Awalan R
  { v1: "Read", v2: "read", v3: "read", arti: "membaca" },
  { v1: "Rebuild", v2: "rebuilt", v3: "rebuilt", arti: "membangun kembali" },
  { v1: "Recast", v2: "recast", v3: "recast", arti: "membentuk ulang" },
  { v1: "Relay", v2: "relaid", v3: "relaid", arti: "mengirim kembali / memasang ulang" },
  { v1: "Rend", v2: "rent", v3: "rent", arti: "mengoyak / merobek" },
  { v1: "Reset", v2: "reset", v3: "reset", arti: "mengatur ulang" },
  { v1: "Retell", v2: "retold", v3: "retold", arti: "menceritakan kembali" },
  { v1: "Rid", v2: "rid", v3: "rid", arti: "membebaskan / menyingkirkan" },
  { v1: "Ride", v2: "rode", v3: "ridden", arti: "mengendarai" },
  { v1: "Ring", v2: "rang", v3: "rung", arti: "membunyikan / berdering" },
  { v1: "Rise", v2: "rose", v3: "risen", arti: "bangkit / naik" },
  { v1: "Run", v2: "ran", v3: "run", arti: "berlari" },
  //Awalan S
  { v1: "Saw", v2: "sawed", v3: "sawn/sawed", arti: "menggergaji" },
  { v1: "Say", v2: "said", v3: "said", arti: "mengatakan" },
  { v1: "See", v2: "saw", v3: "seen", arti: "melihat" },
  { v1: "Seek", v2: "sought", v3: "sought", arti: "mencari" },
  { v1: "Sell", v2: "sold", v3: "sold", arti: "menjual" },
  { v1: "Send", v2: "sent", v3: "sent", arti: "mengirim" },
  { v1: "Set", v2: "set", v3: "set", arti: "menetapkan / menaruh" },
  { v1: "Sew", v2: "sewed", v3: "sewn/sewed", arti: "menjahit" },
  { v1: "Shake", v2: "shook", v3: "shaken", arti: "mengguncang" },
  { v1: "Shear", v2: "sheared", v3: "shorn/sheared", arti: "mencukur (bulu/domba)" },
  { v1: "Shed", v2: "shed", v3: "shed", arti: "menumpahkan / merontokkan" },
  { v1: "Shine", v2: "shone/shined", v3: "shone/shined", arti: "bersinar" },
  { v1: "Shoe", v2: "shod", v3: "shod", arti: "memberi sepatu / tapal kuda" },
  { v1: "Shoot", v2: "shot", v3: "shot", arti: "menembak" },
  { v1: "Show", v2: "showed", v3: "shown/showed", arti: "menunjukkan" },
  { v1: "Shred", v2: "shred/shredded", v3: "shred/shredded", arti: "mencabik-cabik / menghancurkan" },
  { v1: "Shrink", v2: "shrank/shrunk", v3: "shrunk/shrunken", arti: "menyusut" },
  { v1: "Shut", v2: "shut", v3: "shut", arti: "menutup" },
  { v1: "Sing", v2: "sang", v3: "sung", arti: "menyanyi" },
  { v1: "Sink", v2: "sank", v3: "sunk", arti: "tenggelam" },
  { v1: "Sit", v2: "sat", v3: "sat", arti: "duduk" },
  { v1: "Slay", v2: "slew", v3: "slain", arti: "membunuh" },
  { v1: "Sleep", v2: "slept", v3: "slept", arti: "tidur" },
  { v1: "Slide", v2: "slid", v3: "slid", arti: "meluncur" },
  { v1: "Sling", v2: "slung", v3: "slung", arti: "melempar / menggendong" },
  { v1: "Slit", v2: "slit", v3: "slit", arti: "membelah / menyayat" },
  { v1: "Smell", v2: "smelt/smelled", v3: "smelt/smelled", arti: "mencium (bau)" },
  { v1: "Smite", v2: "smote", v3: "smitten", arti: "memukul keras / menimpa" },
  { v1: "Sow", v2: "sowed", v3: "sown/sowed", arti: "menabur" },
  { v1: "Speak", v2: "spoke", v3: "spoken", arti: "berbicara" },
  { v1: "Speed", v2: "sped/speeded", v3: "sped/speeded", arti: "mempercepat / melaju" },
  { v1: "Spell", v2: "spelt/spelled", v3: "spelt/spelled", arti: "mengeja" },
  { v1: "Spend", v2: "spent", v3: "spent", arti: "menghabiskan (waktu/uang)" },
  { v1: "Spill", v2: "spilt/spilled", v3: "spilt/spilled", arti: "menumpahkan" },
  { v1: "Spin", v2: "spun", v3: "spun", arti: "memutar / memintal" },
  { v1: "Spit", v2: "spat/spit", v3: "spat/spit", arti: "meludah" },
  { v1: "Split", v2: "split", v3: "split", arti: "membelah / memecah" },
  { v1: "Spoil", v2: "spoilt/spoiled", v3: "spoilt/spoiled", arti: "merusak / memanjakan" },
  { v1: "Spread", v2: "spread", v3: "spread", arti: "menyebar" },
  { v1: "Spring", v2: "sprang", v3: "sprung", arti: "melompat / memantul" },
  { v1: "Stand", v2: "stood", v3: "stood", arti: "berdiri" },
  { v1: "Stave", v2: "staved/stove", v3: "staved/stove", arti: "membendung / memecahkan" },
  { v1: "Steal", v2: "stole", v3: "stolen", arti: "mencuri" },
  { v1: "Stick", v2: "stuck", v3: "stuck", arti: "menempel / menusuk" },
  { v1: "Sting", v2: "stung", v3: "stung", arti: "menyengat" },
  { v1: "Stink", v2: "stank/stunk", v3: "stunk", arti: "berbau busuk" },
  { v1: "Strew", v2: "strewed", v3: "strewn/strewed", arti: "menaburkan" },
  { v1: "Stride", v2: "strode", v3: "stridden", arti: "melangkah lebar" },
  { v1: "Strike", v2: "struck", v3: "struck/stricken", arti: "memukul / menyerang" },
  { v1: "String", v2: "strung", v3: "strung", arti: "merangkai / mengikat" },
  { v1: "Strive", v2: "strove", v3: "striven", arti: "berusaha keras" },
  { v1: "Strow", v2: "strowed", v3: "strown/strowed", arti: "menyebarkan / menabur" },
  { v1: "Swear", v2: "swore", v3: "sworn", arti: "bersumpah / memaki" },
  { v1: "Sweat", v2: "sweat/sweated", v3: "sweat/sweated", arti: "berkeringat" },
  { v1: "Sweep", v2: "swept", v3: "swept", arti: "menyapu" },
  { v1: "Swell", v2: "swelled", v3: "swollen/swelled", arti: "membengkak" },
  { v1: "Swim", v2: "swam", v3: "swum", arti: "berenang" },
  { v1: "Swing", v2: "swung", v3: "swung", arti: "mengayun" },
  //Awalan T
  { v1: "Take", v2: "took", v3: "taken", arti: "mengambil" },
  { v1: "Teach", v2: "taught", v3: "taught", arti: "mengajar" },
  { v1: "Tear", v2: "tore", v3: "torn", arti: "merobek" },
  { v1: "Tell", v2: "told", v3: "told", arti: "memberitahu" },
  { v1: "Think", v2: "thought", v3: "thought", arti: "berpikir" },
  { v1: "Thrive", v2: "throve/thrived", v3: "thriven/thrived", arti: "berkembang / berhasil" },
  { v1: "Throw", v2: "threw", v3: "thrown", arti: "melempar" },
  { v1: "Thrust", v2: "thrust", v3: "thrust", arti: "menusukkan / mendorong keras" },
  { v1: "Tread", v2: "trod", v3: "trodden/trod", arti: "menginjak / menapak" },
  //Awalan U
  { v1: "Unbend", v2: "unbent", v3: "unbent", arti: "meluruskan" },
  { v1: "Undergo", v2: "underwent", v3: "undergone", arti: "menjalani / mengalami" },
  { v1: "Undersell", v2: "undersold", v3: "undersold", arti: "menjual lebih murah" },
  { v1: "Understand", v2: "understood", v3: "understood", arti: "mengerti" },
  { v1: "Undertake", v2: "undertook", v3: "undertaken", arti: "melakukan / menanggung" },
  { v1: "Underwrite", v2: "underwrote", v3: "underwritten", arti: "menanggung / menjamin" },
  { v1: "Undo", v2: "undid", v3: "undone", arti: "membatalkan / membuka" },
  { v1: "Upset", v2: "upset", v3: "upset", arti: "mengacaukan / menjatuhkan" },
  //Awalan W
  { v1: "Wear", v2: "wore", v3: "worn", arti: "memakai" },
  { v1: "Weave", v2: "wove", v3: "woven", arti: "menenun" },
  { v1: "Weep", v2: "wept", v3: "wept", arti: "menangis" },
  { v1: "Will", v2: "would", v3: "-", arti: "akan" },
  { v1: "Win", v2: "won", v3: "won", arti: "menang" },
  { v1: "Wind", v2: "wound", v3: "wound", arti: "memutar / melilit" },
  { v1: "Withdraw", v2: "withdrew", v3: "withdrawn", arti: "menarik / menarik diri" },
  { v1: "Withstand", v2: "withstood", v3: "withstood", arti: "bertahan / menahan" },
  { v1: "Wring", v2: "wrung", v3: "wrung", arti: "memeras / memelintir" },
  { v1: "Write", v2: "wrote", v3: "written", arti: "menulis" },
];
