window.loadedQuestions = [
  { v1: "Love", v2: "loved", v3: "loved", arti: "mencintai" },
  { v1: "Hate", v2: "hated", v3: "hated", arti: "membenci" },
  { v1: "Like", v2: "liked", v3: "liked", arti: "menyukai" },
  { v1: "Dislike", v2: "disliked", v3: "disliked", arti: "tidak menyukai" },
  { v1: "Enjoy", v2: "enjoyed", v3: "enjoyed", arti: "menikmati" },
  { v1: "Fear", v2: "feared", v3: "feared", arti: "takut" },
  { v1: "Worry", v2: "worried", v3: "worried", arti: "khawatir" },
  { v1: "Hope", v2: "hoped", v3: "hoped", arti: "berharap" },
  { v1: "Wish", v2: "wished", v3: "wished", arti: "mengharapkan" },
  { v1: "Miss", v2: "missed", v3: "missed", arti: "merindukan" },
  { v1: "Cry", v2: "cried", v3: "cried", arti: "menangis" },
  { v1: "Laugh", v2: "laughed", v3: "laughed", arti: "tertawa" },
  { v1: "Smile", v2: "smiled", v3: "smiled", arti: "tersenyum" },
  { v1: "Scream", v2: "screamed", v3: "screamed", arti: "menjerit" },
  { v1: "Shout", v2: "shouted", v3: "shouted", arti: "berteriak" },
  { v1: "Relax", v2: "relaxed", v3: "relaxed", arti: "bersantai" },
  { v1: "Think", v2: "thought", v3: "thought", arti: "berpikir" },
  { v1: "Know", v2: "knew", v3: "known", arti: "tahu" },
  { v1: "Understand", v2: "understood", v3: "understood", arti: "memahami" },
  { v1: "Forget", v2: "forgot", v3: "forgotten", arti: "lupa" },
  { v1: "Remember", v2: "remembered", v3: "remembered", arti: "mengingat" },
  { v1: "Realize", v2: "realized", v3: "realized", arti: "menyadari" },
  { v1: "Imagine", v2: "imagined", v3: "imagined", arti: "membayangkan" },
  { v1: "Doubt", v2: "doubted", v3: "doubted", arti: "meragukan" },
  { v1: "Believe", v2: "believed", v3: "believed", arti: "percaya" },
  { v1: "Guess", v2: "guessed", v3: "guessed", arti: "menebak" },
  { v1: "Mind", v2: "minded", v3: "minded", arti: "mempermasalahkan / peduli" },
  { v1: "Care", v2: "cared", v3: "cared", arti: "peduli" },
  { v1: "Regret", v2: "regretted", v3: "regretted", arti: "menyesal" },
  { v1: "Appreciate", v2: "appreciated", v3: "appreciated", arti: "menghargai" }
];
