window.loadedQuestions = [
  { v1: "Work", v2: "worked", v3: "worked", arti: "bekerja" },
  { v1: "Manage", v2: "managed", v3: "managed", arti: "mengelola" },
  { v1: "Lead", v2: "led", v3: "led", arti: "memimpin" },
  { v1: "Hire", v2: "hired", v3: "hired", arti: "merekrut" },
  { v1: "Fire", v2: "fired", v3: "fired", arti: "memecat" },
  { v1: "Train", v2: "trained", v3: "trained", arti: "melatih" },
  { v1: "Meet", v2: "met", v3: "met", arti: "bertemu" },
  { v1: "Call", v2: "called", v3: "called", arti: "menelpon" },
  { v1: "Email", v2: "emailed", v3: "emailed", arti: "mengirim email" },
  { v1: "Send", v2: "sent", v3: "sent", arti: "mengirim" },
  { v1: "Receive", v2: "received", v3: "received", arti: "menerima" },
  { v1: "Schedule", v2: "scheduled", v3: "scheduled", arti: "menjadwalkan" },
  { v1: "Plan", v2: "planned", v3: "planned", arti: "merencanakan" },
  { v1: "Organize", v2: "organized", v3: "organized", arti: "mengorganisasi" },
  { v1: "Report", v2: "reported", v3: "reported", arti: "melaporkan" },
  { v1: "Present", v2: "presented", v3: "presented", arti: "mempresentasikan" },
  { v1: "Negotiate", v2: "negotiated", v3: "negotiated", arti: "bernegosiasi" },
  { v1: "Sell", v2: "sold", v3: "sold", arti: "menjual" },
  { v1: "Buy", v2: "bought", v3: "bought", arti: "membeli" },
  { v1: "Pay", v2: "paid", v3: "paid", arti: "membayar" },
  { v1: "Analyze", v2: "analyzed", v3: "analyzed", arti: "menganalisis" },
  { v1: "Develop", v2: "developed", v3: "developed", arti: "mengembangkan" },
  { v1: "Design", v2: "designed", v3: "designed", arti: "merancang" },
  { v1: "Build", v2: "built", v3: "built", arti: "membangun" },
  { v1: "Operate", v2: "operated", v3: "operated", arti: "mengoperasikan" },
  { v1: "Support", v2: "supported", v3: "supported", arti: "mendukung" },
  { v1: "Update", v2: "updated", v3: "updated", arti: "memperbarui" },
  { v1: "Approve", v2: "approved", v3: "approved", arti: "menyetujui" },
  { v1: "Reject", v2: "rejected", v3: "rejected", arti: "menolak" },
  { v1: "Sign", v2: "signed", v3: "signed", arti: "menandatangani" }
];
