window.loadedQuestions = [
  { v1: "Wake up", v2: "woke up", v3: "woken up", arti: "bangun" },
  { v1: "Brush", v2: "brushed", v3: "brushed", arti: "menggosok (gigi/rambut)" },
  { v1: "Shower", v2: "showered", v3: "showered", arti: "mandi" },
  { v1: "Eat", v2: "ate", v3: "eaten", arti: "makan" },
  { v1: "Drink", v2: "drank", v3: "drunk", arti: "minum" },
  { v1: "Go", v2: "went", v3: "gone", arti: "pergi" },
  { v1: "Walk", v2: "walked", v3: "walked", arti: "berjalan" },
  { v1: "Run", v2: "ran", v3: "run", arti: "lari" },
  { v1: "Work", v2: "worked", v3: "worked", arti: "bekerja" },
  { v1: "Study", v2: "studied", v3: "studied", arti: "belajar" },
  { v1: "Cook", v2: "cooked", v3: "cooked", arti: "memasak" },
  { v1: "Clean", v2: "cleaned", v3: "cleaned", arti: "membersihkan" },
  { v1: "Wash", v2: "washed", v3: "washed", arti: "mencuci" },
  { v1: "Sleep", v2: "slept", v3: "slept", arti: "tidur" },
  { v1: "Read", v2: "read", v3: "read", arti: "membaca" },
  { v1: "Write", v2: "wrote", v3: "written", arti: "menulis" },
  { v1: "Talk", v2: "talked", v3: "talked", arti: "berbicara" },
  { v1: "Listen", v2: "listened", v3: "listened", arti: "mendengarkan" },
  { v1: "Watch", v2: "watched", v3: "watched", arti: "menonton" },
  { v1: "Drive", v2: "drove", v3: "driven", arti: "mengemudi" },
  { v1: "Play", v2: "played", v3: "played", arti: "bermain" },
  { v1: "Call", v2: "called", v3: "called", arti: "memanggil" },
  { v1: "Help", v2: "helped", v3: "helped", arti: "membantu" },
  { v1: "Buy", v2: "bought", v3: "bought", arti: "membeli" },
  { v1: "Sell", v2: "sold", v3: "sold", arti: "menjual" },
  { v1: "Bring", v2: "brought", v3: "brought", arti: "membawa" },
  { v1: "Meet", v2: "met", v3: "met", arti: "bertemu" },
  { v1: "Open", v2: "opened", v3: "opened", arti: "membuka" },
  { v1: "Close", v2: "closed", v3: "closed", arti: "menutup" },
  { v1: "Fix", v2: "fixed", v3: "fixed", arti: "memperbaiki" },
  { v1: "Pay", v2: "paid", v3: "paid", arti: "membayar" },
  { v1: "Send", v2: "sent", v3: "sent", arti: "mengirim" },
  { v1: "Wait", v2: "waited", v3: "waited", arti: "menunggu" },
  { v1: "Start", v2: "started", v3: "started", arti: "memulai" },
  { v1: "Finish", v2: "finished", v3: "finished", arti: "menyelesaikan" },
  { v1: "Call", v2: "called", v3: "called", arti: "memanggil" },
  { v1: "Smile", v2: "smiled", v3: "smiled", arti: "tersenyum" },
  { v1: "Laugh", v2: "laughed", v3: "laughed", arti: "tertawa" },
  { v1: "Travel", v2: "traveled", v3: "traveled", arti: "bepergian" }
];
