window.loadedQuestions = [
  //Awalan A
  { v1: "Abase", v2: "abased", v3: "abased", arti: "menghinakan" },
  { v1: "Abash", v2: "abashed", v3: "abashed", arti: "memalukan" },
  { v1: "Abate", v2: "abated", v3: "abated", arti: "berkurang" },
  { v1: "Abbreviate", v2: "abbreviated", v3: "abbreviated", arti: "menyingkat" },
  { v1: "Abdicate", v2: "abdicated", v3: "abdicated", arti: "turun tahta" },
  { v1: "Abduct", v2: "abducted", v3: "abducted", arti: "menculik" },
  { v1: "Abhor", v2: "abhorred", v3: "abhorred", arti: "membenci" },
  { v1: "Abolish", v2: "abolished", v3: "abolished", arti: "menghapuskan" },
  { v1: "Abridge", v2: "abridged", v3: "abridged", arti: "menyingkat" },
  { v1: "Abrogate", v2: "abrogated", v3: "abrogated", arti: "membatalkan" },
  { v1: "Absolve", v2: "absolved", v3: "absolved", arti: "membebaskan" },
  { v1: "Absorb", v2: "absorbed", v3: "absorbed", arti: "menyerap" },
  { v1: "Abstain", v2: "abstained", v3: "abstained", arti: "berpantang" },
  { v1: "Abuse", v2: "abused", v3: "abused", arti: "mencaci maki" },
  { v1: "Accede", v2: "acceded", v3: "acceded", arti: "naik (tahta)" },
  { v1: "Accelerate", v2: "accelerated", v3: "accelerated", arti: "mempercepat" },
  { v1: "Accentuate", v2: "accentuated", v3: "accentuated", arti: "menekankan / memperjelas" },
  { v1: "Accept", v2: "accepted", v3: "accepted", arti: "menerima" },
  { v1: "Acclaim", v2: "acclaimed", v3: "acclaimed", arti: "menyambut gembira" },
  { v1: "Acclimate", v2: "acclimated", v3: "acclimated", arti: "menyesuaikan diri dengan iklim" },
  { v1: "Accommodate", v2: "accommodated", v3: "accommodated", arti: "menampung" },
  { v1: "Accompany", v2: "accompanied", v3: "accompanied", arti: "menemani" },
  { v1: "Accomplish", v2: "accomplished", v3: "accomplished", arti: "menyelesaikan" },
  { v1: "Accost", v2: "accosted", v3: "accosted", arti: "menegur" },
  { v1: "Account", v2: "accounted", v3: "accounted", arti: "menghitung / mempertanggungjawabkan" },
  { v1: "Accrue", v2: "accrued", v3: "accrued", arti: "bertambah / meluas" },
  { v1: "Accumulate", v2: "accumulated", v3: "accumulated", arti: "menimbun / mengumpulkan" },
  { v1: "Accuse", v2: "accused", v3: "accused", arti: "menuduh" },
  { v1: "Achieve", v2: "achieved", v3: "achieved", arti: "mencapai" },
  { v1: "Acquaint", v2: "acquainted", v3: "acquainted", arti: "memperkenalkan" },
  { v1: "Acquire", v2: "acquired", v3: "acquired", arti: "memperoleh" },
  { v1: "Acquit", v2: "acquitted", v3: "acquitted", arti: "membebaskan" },
  { v1: "Cross", v2: "crossed", v3: "crossed", arti: "melintasi / menyeberang" },
  { v1: "Act", v2: "acted", v3: "acted", arti: "bertindak" },
  { v1: "Actuate", v2: "actuated", v3: "actuated", arti: "menjalankan / menggerakkan" },
  { v1: "Adapt", v2: "adapted", v3: "adapted", arti: "menyesuaikan" },
  { v1: "Add", v2: "added", v3: "added", arti: "menambahkan" },
  { v1: "Address", v2: "addressed", v3: "addressed", arti: "mengalamatkan / menyampaikan" },
  { v1: "Adhere", v2: "adhered", v3: "adhered", arti: "menganut / melekat" },
  { v1: "Adjoin", v2: "adjoined", v3: "adjoined", arti: "menggabungkan / berdampingan" },
  { v1: "Adjourn", v2: "adjourned", v3: "adjourned", arti: "menangguhkan / menunda" },
  { v1: "Adjudge", v2: "adjudged", v3: "adjudged", arti: "menghukum / memutuskan" },
  { v1: "Adjure", v2: "adjured", v3: "adjured", arti: "meminta dengan sangat / memohon" },
  { v1: "Adjust", v2: "adjusted", v3: "adjusted", arti: "menyesuaikan" },
  { v1: "Administer", v2: "administered", v3: "administered", arti: "mengelola / mengatur" },
  { v1: "Admire", v2: "admired", v3: "admired", arti: "memuji / mengagumi" },
  { v1: "Admit", v2: "admitted", v3: "admitted", arti: "mengakui / mengizinkan masuk" },
  { v1: "Admix", v2: "admixed", v3: "admixed", arti: "mencampurkan" },
  { v1: "Admonish", v2: "admonished", v3: "admonished", arti: "memperingatkan / menegur" },
  { v1: "Adopt", v2: "adopted", v3: "adopted", arti: "memungut / mengadopsi" },
  { v1: "Adore", v2: "adored", v3: "adored", arti: "memuja" },
  { v1: "Adorn", v2: "adorned", v3: "adorned", arti: "menghiasi" },
  { v1: "Adulate", v2: "adulated", v3: "adulated", arti: "membujuk / memuja berlebihan" },
  { v1: "Adulterate", v2: "adulterated", v3: "adulterated", arti: "memalsukan / mencampur" },
  { v1: "Advance", v2: "advanced", v3: "advanced", arti: "memajukan" },
  { v1: "Advert", v2: "adverted", v3: "adverted", arti: "memperhatikan" },
  { v1: "Advertise", v2: "advertised", v3: "advertised", arti: "mengiklankan" },
  { v1: "Advise", v2: "advised", v3: "advised", arti: "menasehati" },
  { v1: "Advocate", v2: "advocated", v3: "advocated", arti: "membela / mendukung" },
  { v1: "Affect", v2: "affected", v3: "affected", arti: "mempengaruhi" },
  { v1: "Affiliate", v2: "affiliated", v3: "affiliated", arti: "menggabungkan diri" },
  { v1: "Affirm", v2: "affirmed", v3: "affirmed", arti: "menegaskan" },
  { v1: "Afford", v2: "afforded", v3: "afforded", arti: "mampu / menyediakan" },
  { v1: "Afforest", v2: "afforested", v3: "afforested", arti: "menghutankan" },
  { v1: "Affranchise", v2: "affranchised", v3: "affranchised", arti: "memerdekakan" },
  { v1: "Affront", v2: "affronted", v3: "affronted", arti: "menghina" },
  { v1: "Agglomerate", v2: "agglomerated", v3: "agglomerated", arti: "mengelompokkan" },
  { v1: "Agglutinate", v2: "agglutinated", v3: "agglutinated", arti: "melekatkan" },
  { v1: "Aggrandize", v2: "aggrandized", v3: "aggrandized", arti: "memperbesar" },
  { v1: "Aggravate", v2: "aggravated", v3: "aggravated", arti: "menjengkelkan / memperburuk" },
  { v1: "Aggress", v2: "aggressed", v3: "aggressed", arti: "menyerang" },
  { v1: "Agitate", v2: "agitated", v3: "agitated", arti: "menghasut / mengguncang" },
  { v1: "Aid", v2: "aided", v3: "aided", arti: "membantu" },
  { v1: "Aim", v2: "aimed", v3: "aimed", arti: "membidik / bertujuan" },
  { v1: "Alight", v2: "alighted", v3: "alighted", arti: "hinggap / turun" },
  { v1: "Align", v2: "aligned", v3: "aligned", arti: "meluruskan / menyelaraskan" },
  { v1: "Allay", v2: "allayed", v3: "allayed", arti: "menenangkan / meredakan" },
  { v1: "Allege", v2: "alleged", v3: "alleged", arti: "menyatakan / menuduh" },
  { v1: "Alleviate", v2: "alleviated", v3: "alleviated", arti: "meringankan" },
  { v1: "Allocate", v2: "allocated", v3: "allocated", arti: "menentukan tempat / mengalokasikan" },
  { v1: "Allot", v2: "allotted", v3: "allotted", arti: "membagikan / menetapkan" },
  { v1: "Allude", v2: "alluded", v3: "alluded", arti: "menyinggung / merujuk" },
  { v1: "Allure", v2: "allured", v3: "allured", arti: "memikat / menggoda" },
  { v1: "Ally", v2: "allied", v3: "allied", arti: "bersekutu / bersatu" },
  { v1: "Alter", v2: "altered", v3: "altered", arti: "mengubah" },
  { v1: "Altercate", v2: "altercated", v3: "altercated", arti: "bertengkar" },
  { v1: "Alternate", v2: "alternated", v3: "alternated", arti: "berganti-ganti" },
  { v1: "Amalgamate", v2: "amalgamated", v3: "amalgamated", arti: "mencampur / menggabungkan" },
  { v1: "Amass", v2: "amassed", v3: "amassed", arti: "menghimpun / menumpuk" },
  { v1: "Amaze", v2: "amazed", v3: "amazed", arti: "menakjubkan / mengherankan" },
  { v1: "Ameliorate", v2: "ameliorated", v3: "ameliorated", arti: "memperbaiki / meningkatkan" },
  { v1: "Amend", v2: "amended", v3: "amended", arti: "mengubah / memperbaiki" },
  { v1: "Amortize", v2: "amortized", v3: "amortized", arti: "melunasi dengan mengangsur" },
  { v1: "Amplify", v2: "amplified", v3: "amplified", arti: "memperkuat / memperbesar" },
  { v1: "Amputate", v2: "amputated", v3: "amputated", arti: "memotong anggota badan" },
  { v1: "Amuse", v2: "amused", v3: "amused", arti: "menghibur / membuat senang" },
  { v1: "Anaesthesize", v2: "anaesthesized", v3: "anaesthesized", arti: "membius" },
  { v1: "Analogize", v2: "analogized", v3: "analogized", arti: "menganalogi / membandingkan" },
  { v1: "Analyze", v2: "analyzed", v3: "analyzed", arti: "menganalisa" },
  { v1: "Anglicize", v2: "anglicized", v3: "anglicized", arti: "menginggriskan" },
  { v1: "Animate", v2: "animated", v3: "animated", arti: "menghidupkan / menganimasikan" },
  { v1: "Annex", v2: "annexed", v3: "annexed", arti: "menggabungkan / mencaplok" },
  { v1: "Annihilate", v2: "annihilated", v3: "annihilated", arti: "membasmi / memusnahkan" },
  { v1: "Annotate", v2: "annotated", v3: "annotated", arti: "membubuhi keterangan" },
  { v1: "Announce", v2: "announced", v3: "announced", arti: "mengumumkan" },
  { v1: "Annoy", v2: "annoyed", v3: "annoyed", arti: "menjengkelkan / mengganggu" },
  { v1: "Annul", v2: "annulled", v3: "annulled", arti: "membatalkan" },
  { v1: "Answer", v2: "answered", v3: "answered", arti: "menjawab" },
  { v1: "Antagonize", v2: "antagonized", v3: "antagonized", arti: "menentang / memusuhi" },
  { v1: "Antedate", v2: "antedated", v3: "antedated", arti: "memberi tanggal lebih maju" },
  { v1: "Anticipate", v2: "anticipated", v3: "anticipated", arti: "mendahului / mengantisipasi" },
  { v1: "Antiquate", v2: "antiquated", v3: "antiquated", arti: "menjadikan benda kuno" },
  { v1: "Apologize", v2: "apologized", v3: "apologized", arti: "minta maaf" },
  { v1: "Appal", v2: "appalled", v3: "appalled", arti: "menggemparkan / mengejutkan" },
  { v1: "Appear", v2: "appeared", v3: "appeared", arti: "tampak / muncul" },
  { v1: "Applaud", v2: "applauded", v3: "applauded", arti: "bertepuk tangan / memuji" },
  { v1: "Apply", v2: "applied", v3: "applied", arti: "menggunakan / menerapkan" },
  { v1: "Appoint", v2: "appointed", v3: "appointed", arti: "menunjuk / menetapkan" },
  { v1: "Apportion", v2: "apportioned", v3: "apportioned", arti: "membagi secara adil" },
  { v1: "Appreciate", v2: "appreciated", v3: "appreciated", arti: "menghargai" },
  { v1: "Apprise", v2: "apprised", v3: "apprised", arti: "memberi kabar / memberitahu" },
  { v1: "Approach", v2: "approached", v3: "approached", arti: "mendekat / menghampiri" },
  { v1: "Appropriate", v2: "appropriated", v3: "appropriated", arti: "menyediakan / mengalokasikan" },
  { v1: "Approve", v2: "approved", v3: "approved", arti: "menyetujui" },
  { v1: "Arbitrate", v2: "arbitrated", v3: "arbitrated", arti: "menengahi / menjadi penengah" },
  { v1: "Argue", v2: "argued", v3: "argued", arti: "mendebatkan / berargumen" },
  { v1: "Arrange", v2: "arranged", v3: "arranged", arti: "menata / mengatur" },
  { v1: "Array", v2: "arrayed", v3: "arrayed", arti: "mempersiapkan / menyusun (barisan)" },
  { v1: "Arrive", v2: "arrived", v3: "arrived", arti: "tiba" },
  { v1: "Ascertain", v2: "ascertained", v3: "ascertained", arti: "memastikan" },
  { v1: "Ascribe", v2: "ascribed", v3: "ascribed", arti: "menganggap berasal" },
  { v1: "Ask", v2: "asked", v3: "asked", arti: "bertanya" },
  { v1: "Aspirate", v2: "aspirated", v3: "aspirated", arti: "mengucap bunyi dengan nafas keras" },
  { v1: "Aspire", v2: "aspired", v3: "aspired", arti: "bercita-cita" },
  { v1: "Assail", v2: "assailed", v3: "assailed", arti: "menyerang" },
  { v1: "Assay", v2: "assayed", v3: "assayed", arti: "menguji / mencoba" },
  { v1: "Assemble", v2: "assembled", v3: "assembled", arti: "memasang / merakit / berkumpul" },
  { v1: "Assert", v2: "asserted", v3: "asserted", arti: "menegaskan" },
  { v1: "Assess", v2: "assessed", v3: "assessed", arti: "menaksir / menilai" },
  { v1: "Assign", v2: "assigned", v3: "assigned", arti: "menugaskan" },
  { v1: "Assimilate", v2: "assimilated", v3: "assimilated", arti: "mengasimilasi" },
  { v1: "Associate", v2: "associated", v3: "associated", arti: "menghubungkan / berhubungan" },
  { v1: "Assort", v2: "assorted", v3: "assorted", arti: "memilih / menyortir" },
  { v1: "Assuage", v2: "assuaged", v3: "assuaged", arti: "meredakan / menenangkan" },
  { v1: "Assure", v2: "assured", v3: "assured", arti: "menjamin" },
  { v1: "Astonish", v2: "astonished", v3: "astonished", arti: "mengherankan" },
  { v1: "Astound", v2: "astounded", v3: "astounded", arti: "mengejutkan / mengagumkan" },
  { v1: "Atone", v2: "atoned", v3: "atoned", arti: "bertobat / menebus kesalahan" },
  { v1: "Attach", v2: "attached", v3: "attached", arti: "melampirkan" },
  { v1: "Attack", v2: "attacked", v3: "attacked", arti: "menyerang" },
  { v1: "Attain", v2: "attained", v3: "attained", arti: "mencapai" },
  { v1: "Attempt", v2: "attempted", v3: "attempted", arti: "berusaha" },
  { v1: "Attend", v2: "attended", v3: "attended", arti: "menghadiri" },
  { v1: "Attenuate", v2: "attenuated", v3: "attenuated", arti: "melemahkan / menipiskan" },
  { v1: "Attest", v2: "attested", v3: "attested", arti: "membuktikan / bersaksi" },
  { v1: "Attire", v2: "attired", v3: "attired", arti: "berpakaian" },
  { v1: "Attract", v2: "attracted", v3: "attracted", arti: "memikat / menarik" },
  { v1: "Attune", v2: "attuned", v3: "attuned", arti: "mencoba bunyi / menyesuaikan" },
  { v1: "Augment", v2: "augmented", v3: "augmented", arti: "memperbanyak / menambah" },
  { v1: "Augur", v2: "augured", v3: "augured", arti: "meramalkan / menandakan" },
  { v1: "Authorize", v2: "authorized", v3: "authorized", arti: "mengesahkan / memberi wewenang" },
  { v1: "Avert", v2: "averted", v3: "averted", arti: "mencegah / menghindarkan" },
  { v1: "Aviate", v2: "aviated", v3: "aviated", arti: "terbang dengan pesawat" },
  { v1: "Avoid", v2: "avoided", v3: "avoided", arti: "menghindari" },
  { v1: "Avouch", v2: "avouched", v3: "avouched", arti: "menjamin / menyatakan dengan tegas" },
  { v1: "Avow", v2: "avowed", v3: "avowed", arti: "mengakui / menyatakan" },
  { v1: "Await", v2: "awaited", v3: "awaited", arti: "menunggu" },
  { v1: "Award", v2: "awarded", v3: "awarded", arti: "menganugerahi" },
  { v1: "Axe", v2: "axed", v3: "axed", arti: "memotong / menghapuskan" },
  //Awalan B
  { v1: "Babble", v2: "babbled", v3: "babbled", arti: "ngoceh / bergumam" },
  { v1: "Balance", v2: "balanced", v3: "balanced", arti: "mencocokkan / menyeimbangkan" },
  { v1: "Balk", v2: "balked", v3: "balked", arti: "mogok / enggan" },
  { v1: "Bamboozle", v2: "bamboozled", v3: "bamboozled", arti: "memperdayakan / menipu" },
  { v1: "Ban", v2: "banned", v3: "banned", arti: "melarang" },
  { v1: "Bandage", v2: "bandaged", v3: "bandaged", arti: "membalut" },
  { v1: "Banish", v2: "banished", v3: "banished", arti: "membuang / mengusir" },
  { v1: "Baptize", v2: "baptized", v3: "baptized", arti: "membaptis" },
  { v1: "Barbarize", v2: "barbarized", v3: "barbarized", arti: "menjadi biadab" },
  { v1: "Bargain", v2: "bargained", v3: "bargained", arti: "tawar-menawar" },
  { v1: "Bark", v2: "barked", v3: "barked", arti: "menyalak" },
  { v1: "Bate", v2: "bated", v3: "bated", arti: "mengurangi / menahan" },
  { v1: "Bathe", v2: "bathed", v3: "bathed", arti: "memandikan / mandi" },
  { v1: "Batter", v2: "battered", v3: "battered", arti: "memukul berulang-ulang" },
  { v1: "Bawl", v2: "bawled", v3: "bawled", arti: "berteriak / menangis keras" },
  { v1: "Becalm", v2: "becalmed", v3: "becalmed", arti: "menenangkan / membuat diam" },
  { v1: "Beckon", v2: "beckoned", v3: "beckoned", arti: "mengisyaratkan / memanggil dengan gerakan" },
  { v1: "Bedazzle", v2: "bedazzled", v3: "bedazzled", arti: "menyilaukan / mempesona" },
  { v1: "Bedeck", v2: "bedecked", v3: "bedecked", arti: "menghias" },
  { v1: "Bedevil", v2: "bedeviled", v3: "bedeviled", arti: "menggoda / mengganggu" },
  { v1: "Bedew", v2: "bedewed", v3: "bedewed", arti: "melumuri / membasahi" },
  { v1: "Befit", v2: "befitted", v3: "befitted", arti: "mencocokkan / sesuai" },
  { v1: "Befool", v2: "befooled", v3: "befooled", arti: "membodohi" },
  { v1: "Beg", v2: "begged", v3: "begged", arti: "meminta / mengemis" },
  { v1: "Begrime", v2: "begrimed", v3: "begrimed", arti: "mencemari / mengotori" },
  { v1: "Begrudge", v2: "begrudged", v3: "begrudged", arti: "mengiri / merasa berat hati" },
  { v1: "Beguile", v2: "beguiled", v3: "beguiled", arti: "memperdayakan / menipu dengan rayuan" },
  { v1: "Behead", v2: "beheaded", v3: "beheaded", arti: "memenggal" },
  { v1: "Belabour", v2: "belaboured", v3: "belaboured", arti: "memukul dengan keras / mengulang-ulang" },
  { v1: "Belaud", v2: "belauded", v3: "belauded", arti: "memuji" },
  { v1: "Beleaguer", v2: "beleaguered", v3: "beleaguered", arti: "mengepung / mengepung musuh" },
  { v1: "Believe", v2: "believed", v3: "believed", arti: "mempercayai" },
  { v1: "Belittle", v2: "belittled", v3: "belittled", arti: "meremehkan / mengecilkan" },
  { v1: "Bellow", v2: "bellowed", v3: "bellowed", arti: "melenguh / berteriak keras" },
  { v1: "Bemoan", v2: "bemoaned", v3: "bemoaned", arti: "meratapi / meratapkan" },
  { v1: "Benumb", v2: "benumbed", v3: "benumbed", arti: "menjadi kaku kedinginan / membuat kebas" },
  { v1: "Bequeath", v2: "bequeathed", v3: "bequeathed", arti: "mewariskan" },
  { v1: "Bereave", v2: "bereaved/bereft", v3: "bereaved/bereft", arti: "merampas / membuat kehilangan" },
  { v1: "Besiege", v2: "besieged", v3: "besieged", arti: "mengepung" },
  { v1: "Besmear", v2: "besmeared", v3: "besmeared", arti: "mengotori" },
  { v1: "Besprinkle", v2: "besprinkled", v3: "besprinkled", arti: "memerciki" },
  { v1: "Betray", v2: "betrayed", v3: "betrayed", arti: "mengkhianati" },
  { v1: "Betroth", v2: "betrothed", v3: "betrothed", arti: "bertunangan" },
  { v1: "Bevel", v2: "beveled", v3: "beveled", arti: "memiringkan / memotong miring" },
  { v1: "Bewail", v2: "bewailed", v3: "bewailed", arti: "meratapi" },
  { v1: "Bewilder", v2: "bewildered", v3: "bewildered", arti: "membingungkan" },
  { v1: "Bewitch", v2: "bewitched", v3: "bewitched", arti: "mempesonakan / menyihir" },
  { v1: "Bicker", v2: "bickered", v3: "bickered", arti: "bercekcok" },
  { v1: "Bivouac", v2: "bivouacked", v3: "bivouacked", arti: "berkemah" },
  { v1: "Blame", v2: "blamed", v3: "blamed", arti: "menyalahkan" },
  { v1: "Blast", v2: "blasted", v3: "blasted", arti: "menghancurkan / meledakkan" },
  { v1: "Bless", v2: "blessed", v3: "blessed", arti: "memberkahi" },
  { v1: "Block", v2: "blocked", v3: "blocked", arti: "merintangi / menghalangi" },
  { v1: "Bluster", v2: "blustered", v3: "blustered", arti: "menggertak / mengamuk" },
  { v1: "Boast", v2: "boasted", v3: "boasted", arti: "menyombongkan diri" },
  { v1: "Bode", v2: "boded", v3: "boded", arti: "menunjukkan / meramalkan" },
  { v1: "Boggle", v2: "boggled", v3: "boggled", arti: "meragukan / terkejut bingung" },
  { v1: "Boil", v2: "boiled", v3: "boiled", arti: "mendidihkan" },
  { v1: "Boobytrap", v2: "boobytrapped", v3: "boobytrapped", arti: "memasang ranjau" },
  { v1: "Bootleg", v2: "bootlegged", v3: "bootlegged", arti: "menyelundupkan" },
  { v1: "Bop", v2: "bopped", v3: "bopped", arti: "memukul" },
  { v1: "Bounce", v2: "bounced", v3: "bounced", arti: "memantul" },
  { v1: "Boycott", v2: "boycotted", v3: "boycotted", arti: "memboikot" },
  { v1: "Brag", v2: "bragged", v3: "bragged", arti: "menyombongkan" },
  { v1: "Brandish", v2: "brandished", v3: "brandished", arti: "mengacungkan" },
  { v1: "Braze", v2: "brazed", v3: "brazed", arti: "memateri / menyolder" },
  { v1: "Breathe", v2: "breathed", v3: "breathed", arti: "bernafas" },
  { v1: "Bribe", v2: "bribed", v3: "bribed", arti: "menyuap" },
  { v1: "Brim", v2: "brimmed", v3: "brimmed", arti: "penuh sampai tepi / meluap" },
  { v1: "Broadcast", v2: "broadcast", v3: "broadcast", arti: "menyiarkan" },
  { v1: "Brush", v2: "brushed", v3: "brushed", arti: "menyikat" },
  { v1: "Bulge", v2: "bulged", v3: "bulged", arti: "menonjol (keluar)" },
  { v1: "Burden", v2: "burdened", v3: "burdened", arti: "menyusahkan" },
  { v1: "Burgle", v2: "burgled", v3: "burgled", arti: "membongkar" },
  { v1: "Burrow", v2: "burrowed", v3: "burrowed", arti: "bersembunyi" },
  { v1: "Bury", v2: "buried", v3: "buried", arti: "mengubur" },
  //Awalan C
  { v1: "Cackle", v2: "cackled", v3: "cackled", arti: "tertawa cekikikan" },
  { v1: "Cadge", v2: "cadged", v3: "cadged", arti: "mengemis / meminta-minta" },
  { v1: "Calcify", v2: "calcified", v3: "calcified", arti: "mengeras (jadi batu kapur)" },
  { v1: "Calculate", v2: "calculated", v3: "calculated", arti: "menghitung" },
  { v1: "Call", v2: "called", v3: "called", arti: "memanggil" },
  { v1: "Calumniate", v2: "calumniated", v3: "calumniated", arti: "memfitnah" },
  { v1: "Canvass", v2: "canvassed", v3: "canvassed", arti: "meneliti / mengampanyekan" },
  { v1: "Capitulate", v2: "capitulated", v3: "capitulated", arti: "menyerah" },
  { v1: "Capture", v2: "captured", v3: "captured", arti: "menangkap" },
  { v1: "Carry", v2: "carried", v3: "carried", arti: "membawa" },
  { v1: "Castigate", v2: "castigated", v3: "castigated", arti: "menghukum keras / menyiksa" },
  { v1: "Celebrate", v2: "celebrated", v3: "celebrated", arti: "merayakan" },
  { v1: "Charge", v2: "charged", v3: "charged", arti: "menagih / menuduh / menyerang" },
  { v1: "Charter", v2: "chartered", v3: "chartered", arti: "mencarter" },
  { v1: "Chat", v2: "chatted", v3: "chatted", arti: "mengobrol" },
  { v1: "Cheat", v2: "cheated", v3: "cheated", arti: "menipu" },
  { v1: "Check", v2: "checked", v3: "checked", arti: "memeriksa" },
  { v1: "Cherish", v2: "cherished", v3: "cherished", arti: "menghargai / menyayangi" },
  { v1: "Chew", v2: "chewed", v3: "chewed", arti: "mengunyah" },
  { v1: "Chicane", v2: "chicaned", v3: "chicaned", arti: "mengelabui / mengganggu" },
  { v1: "Chum", v2: "chummed", v3: "chummed", arti: "berteman akrab" },
  { v1: "Circulate", v2: "circulated", v3: "circulated", arti: "mengedarkan" }
];
