window.loadedQuestions = [
  { v1: "Travel", v2: "traveled", v3: "traveled", arti: "bepergian" },
  { v1: "Drive", v2: "drove", v3: "driven", arti: "mengemudi" },
  { v1: "Ride", v2: "rode", v3: "ridden", arti: "menaiki (kendaraan, kuda)" },
  { v1: "Fly", v2: "flew", v3: "flown", arti: "terbang" },
  { v1: "Sail", v2: "sailed", v3: "sailed", arti: "berlayar" },
  { v1: "Walk", v2: "walked", v3: "walked", arti: "berjalan kaki" },
  { v1: "Run", v2: "ran", v3: "run", arti: "berlari" },
  { v1: "Take", v2: "took", v3: "taken", arti: "mengambil / naik (kendaraan)" },
  { v1: "Catch", v2: "caught", v3: "caught", arti: "menangkap / mengejar (kendaraan)" },
  { v1: "Miss", v2: "missed", v3: "missed", arti: "ketinggalan (kendaraan)" },
  { v1: "Book", v2: "booked", v3: "booked", arti: "memesan" },
  { v1: "Arrive", v2: "arrived", v3: "arrived", arti: "tiba" },
  { v1: "Depart", v2: "departed", v3: "departed", arti: "berangkat" },
  { v1: "Check", v2: "checked", v3: "checked", arti: "memeriksa / check-in" },
  { v1: "Pack", v2: "packed", v3: "packed", arti: "mengemas" },
  { v1: "Unpack", v2: "unpacked", v3: "unpacked", arti: "membongkar barang" },
  { v1: "Wait", v2: "waited", v3: "waited", arti: "menunggu" },
  { v1: "Stay", v2: "stayed", v3: "stayed", arti: "menginap / tinggal" },
  { v1: "Visit", v2: "visited", v3: "visited", arti: "mengunjungi" },
  { v1: "Explore", v2: "explored", v3: "explored", arti: "menjelajahi" },
  { v1: "Tour", v2: "toured", v3: "toured", arti: "berwisata / berkeliling" },
  { v1: "Map", v2: "mapped", v3: "mapped", arti: "memetakan" },
  { v1: "Guide", v2: "guided", v3: "guided", arti: "memandu" },
  { v1: "Reserve", v2: "reserved", v3: "reserved", arti: "memesan / reservasi" },
  { v1: "Transport", v2: "transported", v3: "transported", arti: "mengangkut / mengirim" }
];
