window.loadedQuestions = [
  { v1: "Abase", v2: "abased", v3: "abased", arti: "menghinakan" },
  { v1: "Abash", v2: "abashed", v3: "abashed", arti: "memalukan" },
  { v1: "Abate", v2: "abated", v3: "abated", arti: "berkurang" },
  { v1: "Abbreviate", v2: "abbreviated", v3: "abbreviated", arti: "menyingkat" },
  { v1: "Abdicate", v2: "abdicated", v3: "abdicated", arti: "turun tahta" },
  { v1: "Abduct", v2: "abducted", v3: "abducted", arti: "menculik" },
  { v1: "Abhor", v2: "abhorred", v3: "abhorred", arti: "membenci" },
  { v1: "Abolish", v2: "abolished", v3: "abolished", arti: "menghapuskan" },
  { v1: "Abridge", v2: "abridged", v3: "abridged", arti: "menyingkat" },
  { v1: "Abrogate", v2: "abrogated", v3: "abrogated", arti: "membatalkan" },
  { v1: "Absolve", v2: "absolved", v3: "absolved", arti: "membebaskan" },
  { v1: "Absorb", v2: "absorbed", v3: "absorbed", arti: "menyerap" },
  { v1: "Abstain", v2: "abstained", v3: "abstained", arti: "berpantang" },
  { v1: "Abuse", v2: "abused", v3: "abused", arti: "mencaci maki" },
  { v1: "Accede", v2: "acceded", v3: "acceded", arti: "naik (tahta)" },
  { v1: "Accelerate", v2: "accelerated", v3: "accelerated", arti: "mempercepat" },
  { v1: "Accentuate", v2: "accentuated", v3: "accentuated", arti: "menekankan / memperjelas" },
  { v1: "Accept", v2: "accepted", v3: "accepted", arti: "menerima" },
  { v1: "Acclaim", v2: "acclaimed", v3: "acclaimed", arti: "menyambut gembira" },
  { v1: "Acclimate", v2: "acclimated", v3: "acclimated", arti: "menyesuaikan diri dengan iklim" },
  { v1: "Accommodate", v2: "accommodated", v3: "accommodated", arti: "menampung" },
  { v1: "Accompany", v2: "accompanied", v3: "accompanied", arti: "menemani" },
  { v1: "Accomplish", v2: "accomplished", v3: "accomplished", arti: "menyelesaikan" },
  { v1: "Accost", v2: "accosted", v3: "accosted", arti: "menegur" },
  { v1: "Account", v2: "accounted", v3: "accounted", arti: "menghitung / mempertanggungjawabkan" },
  { v1: "Accrue", v2: "accrued", v3: "accrued", arti: "bertambah / meluas" },
  { v1: "Accumulate", v2: "accumulated", v3: "accumulated", arti: "menimbun / mengumpulkan" },
  { v1: "Accuse", v2: "accused", v3: "accused", arti: "menuduh" },
  { v1: "Achieve", v2: "achieved", v3: "achieved", arti: "mencapai" },
  { v1: "Acquaint", v2: "acquainted", v3: "acquainted", arti: "memperkenalkan" },
  { v1: "Acquire", v2: "acquired", v3: "acquired", arti: "memperoleh" },
  { v1: "Acquit", v2: "acquitted", v3: "acquitted", arti: "membebaskan" },
  { v1: "Cross", v2: "crossed", v3: "crossed", arti: "melintasi / menyeberang" },
  { v1: "Act", v2: "acted", v3: "acted", arti: "bertindak" },
  { v1: "Actuate", v2: "actuated", v3: "actuated", arti: "menjalankan / menggerakkan" },
  { v1: "Adapt", v2: "adapted", v3: "adapted", arti: "menyesuaikan" },
  { v1: "Add", v2: "added", v3: "added", arti: "menambahkan" },
  { v1: "Address", v2: "addressed", v3: "addressed", arti: "mengalamatkan / menyampaikan" },
  { v1: "Adhere", v2: "adhered", v3: "adhered", arti: "menganut / melekat" },
  { v1: "Adjoin", v2: "adjoined", v3: "adjoined", arti: "menggabungkan / berdampingan" },
  { v1: "Adjourn", v2: "adjourned", v3: "adjourned", arti: "menangguhkan / menunda" },
  { v1: "Adjudge", v2: "adjudged", v3: "adjudged", arti: "menghukum / memutuskan" },
  { v1: "Adjure", v2: "adjured", v3: "adjured", arti: "meminta dengan sangat / memohon" },
  { v1: "Adjust", v2: "adjusted", v3: "adjusted", arti: "menyesuaikan" },
  { v1: "Administer", v2: "administered", v3: "administered", arti: "mengelola / mengatur" },
  { v1: "Admire", v2: "admired", v3: "admired", arti: "memuji / mengagumi" },
  { v1: "Admit", v2: "admitted", v3: "admitted", arti: "mengakui / mengizinkan masuk" },
  { v1: "Admix", v2: "admixed", v3: "admixed", arti: "mencampurkan" },
  { v1: "Admonish", v2: "admonished", v3: "admonished", arti: "memperingatkan / menegur" },
  { v1: "Adopt", v2: "adopted", v3: "adopted", arti: "memungut / mengadopsi" },
  { v1: "Adore", v2: "adored", v3: "adored", arti: "memuja" },
  { v1: "Adorn", v2: "adorned", v3: "adorned", arti: "menghiasi" },
  { v1: "Adulate", v2: "adulated", v3: "adulated", arti: "membujuk / memuja berlebihan" },
  { v1: "Adulterate", v2: "adulterated", v3: "adulterated", arti: "memalsukan / mencampur" },
  { v1: "Advance", v2: "advanced", v3: "advanced", arti: "memajukan" },
  { v1: "Advert", v2: "adverted", v3: "adverted", arti: "memperhatikan" },
  { v1: "Advertise", v2: "advertised", v3: "advertised", arti: "mengiklankan" },
  { v1: "Advise", v2: "advised", v3: "advised", arti: "menasehati" },
  { v1: "Advocate", v2: "advocated", v3: "advocated", arti: "membela / mendukung" },
  { v1: "Affect", v2: "affected", v3: "affected", arti: "mempengaruhi" },
  { v1: "Affiliate", v2: "affiliated", v3: "affiliated", arti: "menggabungkan diri" },
  { v1: "Affirm", v2: "affirmed", v3: "affirmed", arti: "menegaskan" },
  { v1: "Afford", v2: "afforded", v3: "afforded", arti: "mampu / menyediakan" },
  { v1: "Afforest", v2: "afforested", v3: "afforested", arti: "menghutankan" },
  { v1: "Affranchise", v2: "affranchised", v3: "affranchised", arti: "memerdekakan" },
  { v1: "Affront", v2: "affronted", v3: "affronted", arti: "menghina" },
  { v1: "Agglomerate", v2: "agglomerated", v3: "agglomerated", arti: "mengelompokkan" },
  { v1: "Agglutinate", v2: "agglutinated", v3: "agglutinated", arti: "melekatkan" },
  { v1: "Aggrandize", v2: "aggrandized", v3: "aggrandized", arti: "memperbesar" },
  { v1: "Aggravate", v2: "aggravated", v3: "aggravated", arti: "menjengkelkan / memperburuk" },
  { v1: "Aggress", v2: "aggressed", v3: "aggressed", arti: "menyerang" },
  { v1: "Agitate", v2: "agitated", v3: "agitated", arti: "menghasut / mengguncang" },
  { v1: "Aid", v2: "aided", v3: "aided", arti: "membantu" },
  { v1: "Aim", v2: "aimed", v3: "aimed", arti: "membidik / bertujuan" },
  { v1: "Alight", v2: "alighted", v3: "alighted", arti: "hinggap / turun" },
  // Tambahkan soal lain sesuai kebutuhan
];

