window.loadedQuestions = [
  { word: "amazing", arti: "menakjubkan" },
  { word: "amazed", arti: "terkejut" },
  { word: "boring", arti: "membosankan" },
  { word: "bored", arti: "bosan" },
  { word: "tiring", arti: "melelahkan" },
  { word: "tired", arti: "lelah" },
  { word: "exciting", arti: "menyenangkan" },
  { word: "excited", arti: "bersemangat" },
  { word: "confusing", arti: "membingungkan" },
  { word: "confused", arti: "bingung" },
  { word: "frightening", arti: "menakutkan" },
  { word: "frightened", arti: "takut" },
  { word: "satisfying", arti: "memuaskan" },
  { word: "satisfied", arti: "puas" },
  { word: "embarrassing", arti: "memalukan" },
  { word: "embarrassed", arti: "malu" },
  { word: "disappointing", arti: "mengecewakan" },
  { word: "disappointed", arti: "kecewa" },
  { word: "relaxing", arti: "menenangkan" },
  { word: "relaxed", arti: "santai" },
  { word: "shocking", arti: "mengagetkan" },
  { word: "shocked", arti: "terkejut" },
  { word: "annoying", arti: "menjengkelkan" },
  { word: "annoyed", arti: "kesal" },
  { word: "alarming", arti: "mengkhawatirkan" },
  { word: "alarmed", arti: "terkejut / khawatir" },
  { word: "worrying", arti: "mengkhawatirkan" },
  { word: "worried", arti: "khawatir" },
  { word: "depressing", arti: "menyedihkan" },
  { word: "depressed", arti: "tertekan" },
  { word: "fascinating", arti: "memikat" },
  { word: "fascinated", arti: "terpikat" },
  { word: "disgusting", arti: "menjijikkan" },
  { word: "disgusted", arti: "jijik" },
  { word: "thrilling", arti: "mendebarkan" },
  { word: "thrilled", arti: "gembira sekali" },
  { word: "puzzling", arti: "membingungkan" },
  { word: "puzzled", arti: "bingung" },
  { word: "surprising", arti: "mengejutkan" },
  { word: "surprised", arti: "terkejut" },
  { word: "touching", arti: "mengharukan" },
  { word: "touched", arti: "tersentuh" },
  { word: "rewarding", arti: "berharga / memuaskan" },
  { word: "challenging", arti: "menantang" },
  { word: "encouraging", arti: "menyemangati" },
  { word: "encouraged", arti: "tersupport" },
  { word: "exhausting", arti: "sangat melelahkan" },
  { word: "exhausted", arti: "sangat lelah" },
  { word: "tempting", arti: "menggoda" },
  { word: "tempted", arti: "tergoda" }
];
