window.loadedQuestions = [
  { word: "amazing", arti: "menakjubkan" },
  { word: "awful", arti: "mengerikan / buruk" },
  { word: "bad", arti: "buruk" },
  { word: "beautiful", arti: "indah / cantik" },
  { word: "boring", arti: "membosankan" },
  { word: "brilliant", arti: "cemerlang" },
  { word: "confusing", arti: "membingungkan" },
  { word: "cool", arti: "keren" },
  { word: "delicious", arti: "lezat" },
  { word: "disgusting", arti: "menjijikkan" },
  { word: "dull", arti: "membosankan / tumpul" },
  { word: "enjoyable", arti: "menyenangkan" },
  { word: "excellent", arti: "hebat / luar biasa" },
  { word: "fantastic", arti: "fantastis" },
  { word: "fascinating", arti: "menarik" },
  { word: "fine", arti: "baik" },
  { word: "fun", arti: "menyenangkan" },
  { word: "funny", arti: "lucu" },
  { word: "good", arti: "baik" },
  { word: "great", arti: "hebat" },
  { word: "horrible", arti: "mengerikan" },
  { word: "interesting", arti: "menarik" },
  { word: "lovely", arti: "menawan" },
  { word: "magnificent", arti: "agung / luar biasa" },
  { word: "marvelous", arti: "luar biasa" },
  { word: "nice", arti: "bagus / menyenangkan" },
  { word: "odd", arti: "aneh" },
  { word: "outstanding", arti: "unggul" },
  { word: "pleasant", arti: "menyenangkan" },
  { word: "poor", arti: "buruk / miskin" },
  { word: "remarkable", arti: "luar biasa" },
  { word: "ridiculous", arti: "konyol" },
  { word: "satisfying", arti: "memuaskan" },
  { word: "scary", arti: "menakutkan" },
  { word: "silly", arti: "bodoh / konyol" },
  { word: "stupid", arti: "bodoh" },
  { word: "superb", arti: "sangat bagus" },
  { word: "terrible", arti: "mengerikan / buruk sekali" },
  { word: "tiring", arti: "melelahkan" },
  { word: "ugly", arti: "jelek" },
  { word: "unbelievable", arti: "tidak bisa dipercaya" },
  { word: "uninteresting", arti: "tidak menarik" },
  { word: "useless", arti: "tidak berguna" },
  { word: "useful", arti: "berguna" },
  { word: "valuable", arti: "berharga" },
  { word: "weird", arti: "aneh" },
  { word: "wonderful", arti: "menakjubkan" },
  { word: "worthless", arti: "tidak bernilai" },
  { word: "worthy", arti: "layak / pantas" },
  { word: "worst", arti: "paling buruk" }
];
