window.loadedQuestions = [
  { word: "this", arti: "ini (tunggal, dekat)" },
  { word: "that", arti: "itu (tunggal, jauh)" },
  { word: "these", arti: "ini (jamak, dekat)" },
  { word: "those", arti: "itu (jamak, jauh)" },
  { word: "such", arti: "seperti itu" },
  { word: "the very", arti: "yang sangat (itu juga)" },
  { word: "either of these", arti: "salah satu dari ini" },
  { word: "neither of those", arti: "tidak satu pun dari itu" },
  { word: "one of these", arti: "salah satu dari ini" },
  { word: "both of those", arti: "keduanya dari itu" },
  { word: "another", arti: "yang lain (tambahan, tunggal)" },
  { word: "the other", arti: "yang lainnya (dari dua)" },
  { word: "other", arti: "lain (jamak/tak tentu)" },
  { word: "some of these", arti: "beberapa dari ini" },
  { word: "most of those", arti: "sebagian besar dari itu" },
  { word: "that kind of", arti: "jenis yang itu" },
  { word: "this type of", arti: "jenis yang ini" },
  { word: "these kinds of", arti: "jenis-jenis yang ini" },
  { word: "those types of", arti: "jenis-jenis yang itu" },
  { word: "that particular", arti: "yang itu secara spesifik" },
  { word: "this particular", arti: "yang ini secara spesifik" },
  { word: "certain", arti: "tertentu" },
  { word: "same", arti: "sama" },
  { word: "next", arti: "berikutnya" },
  { word: "previous", arti: "sebelumnya" },
  { word: "last", arti: "terakhir" },
  { word: "first", arti: "pertama" },
  { word: "next one", arti: "yang selanjutnya" },
  { word: "last one", arti: "yang terakhir" },
  { word: "this one", arti: "yang ini" },
  { word: "that one", arti: "yang itu" },
  { word: "those ones", arti: "yang itu (jamak)" },
  { word: "these ones", arti: "yang ini (jamak)" },
  { word: "that same", arti: "yang sama itu" },
  { word: "this same", arti: "yang sama ini" },
  { word: "a certain", arti: "suatu/tertentu" },
  { word: "those particular", arti: "yang itu secara khusus" },
  { word: "this exact", arti: "yang persis ini" },
  { word: "that exact", arti: "yang persis itu" },
  { word: "this very", arti: "yang sangat ini" },
  { word: "that very", arti: "yang sangat itu" },
  { word: "each of these", arti: "masing-masing dari ini" },
  { word: "all of those", arti: "semua dari itu" },
  { word: "none of these", arti: "tidak ada dari ini" },
  { word: "few of those", arti: "sedikit dari itu" },
  { word: "this kind", arti: "jenis ini" },
  { word: "that kind", arti: "jenis itu" },
  { word: "these two", arti: "dua ini" },
  { word: "those three", arti: "tiga itu" }
];
