window.loadedQuestions = [
  { word: "each", arti: "masing-masing" },
  { word: "every", arti: "setiap" },
  { word: "either", arti: "salah satu (dari dua)" },
  { word: "neither", arti: "tidak satupun (dari dua)" },
  { word: "any", arti: "salah satu / apa saja" },
  { word: "both", arti: "keduanya" },
  { word: "all", arti: "semua" },
  { word: "none", arti: "tidak ada satupun" },
  { word: "each student", arti: "setiap siswa" },
  { word: "every child", arti: "setiap anak" },
  { word: "either answer", arti: "salah satu jawaban" },
  { word: "neither option", arti: "tidak satu pun opsi" },
  { word: "any question", arti: "pertanyaan apa saja" },
  { word: "both teams", arti: "kedua tim" },
  { word: "all books", arti: "semua buku" },
  { word: "none of them", arti: "tidak ada dari mereka" },
  { word: "each person", arti: "setiap orang" },
  { word: "every student", arti: "setiap murid" },
  { word: "either road", arti: "salah satu jalan" },
  { word: "neither side", arti: "tidak satupun sisi" },
  { word: "any answer", arti: "jawaban apa saja" },
  { word: "both choices", arti: "kedua pilihan" },
  { word: "all participants", arti: "semua peserta" },
  { word: "none of the answers", arti: "tidak ada dari jawaban" },
  { word: "each of them", arti: "masing-masing dari mereka" },
  { word: "every house", arti: "setiap rumah" },
  { word: "either way", arti: "salah satu cara" },
  { word: "neither decision", arti: "tidak satu pun keputusan" },
  { word: "any student", arti: "siswa mana pun" },
  { word: "both options", arti: "kedua opsi" },
  { word: "all of us", arti: "kita semua" },
  { word: "none of these", arti: "tidak satu pun dari ini" },
  { word: "each question", arti: "setiap pertanyaan" },
  { word: "every answer", arti: "setiap jawaban" },
  { word: "either person", arti: "salah satu orang" },
  { word: "neither man", arti: "tidak satupun pria" },
  { word: "any item", arti: "barang apa saja" },
  { word: "both students", arti: "kedua siswa" },
  { word: "all cars", arti: "semua mobil" },
  { word: "none of those", arti: "tidak satu pun dari itu" },
  { word: "each side", arti: "setiap sisi" },
  { word: "every member", arti: "setiap anggota" },
  { word: "either shirt", arti: "salah satu baju" },
  { word: "neither solution", arti: "tidak satupun solusi" },
  { word: "any person", arti: "orang siapa saja" },
  { word: "both books", arti: "kedua buku" },
  { word: "all answers", arti: "semua jawaban" },
  { word: "none of the people", arti: "tidak satupun dari orang-orang itu" },
  { word: "each moment", arti: "setiap momen" }
];
