window.loadedQuestions = [
  { word: "my", arti: "milik saya" },
  { word: "your", arti: "milik kamu/Anda" },
  { word: "his", arti: "milik dia (laki-laki)" },
  { word: "her", arti: "milik dia (perempuan)" },
  { word: "its", arti: "miliknya (benda/hewan)" },
  { word: "our", arti: "milik kami/kita" },
  { word: "their", arti: "milik mereka" },
  { word: "my book", arti: "buku saya" },
  { word: "your bag", arti: "tas kamu" },
  { word: "his car", arti: "mobilnya (laki-laki)" },
  { word: "her phone", arti: "teleponnya (perempuan)" },
  { word: "its tail", arti: "ekornya (hewan)" },
  { word: "our house", arti: "rumah kami" },
  { word: "their school", arti: "sekolah mereka" },
  { word: "my friend", arti: "teman saya" },
  { word: "your teacher", arti: "guru kamu" },
  { word: "his brother", arti: "saudara laki-lakinya" },
  { word: "her sister", arti: "saudara perempuannya" },
  { word: "our project", arti: "proyek kami" },
  { word: "their idea", arti: "ide mereka" },
  { word: "my job", arti: "pekerjaan saya" },
  { word: "your homework", arti: "PR kamu" },
  { word: "his opinion", arti: "pendapatnya (dia laki-laki)" },
  { word: "her voice", arti: "suaranya (dia perempuan)" },
  { word: "its name", arti: "namanya (hewan/benda)" },
  { word: "our journey", arti: "perjalanan kami" },
  { word: "their apartment", arti: "apartemen mereka" },
  { word: "my country", arti: "negara saya" },
  { word: "your family", arti: "keluarga kamu" },
  { word: "his laptop", arti: "laptopnya (dia laki-laki)" },
  { word: "her shoes", arti: "sepatu dia (perempuan)" },
  { word: "its color", arti: "warnanya (benda/hewan)" },
  { word: "our classroom", arti: "kelas kami" },
  { word: "their neighborhood", arti: "lingkungan mereka" },
  { word: "my responsibility", arti: "tanggung jawab saya" },
  { word: "your answer", arti: "jawaban kamu" },
  { word: "his mistake", arti: "kesalahan dia (laki-laki)" },
  { word: "her smile", arti: "senyum dia (perempuan)" },
  { word: "our choice", arti: "pilihan kami" },
  { word: "their plan", arti: "rencana mereka" },
  { word: "my dream", arti: "impian saya" },
  { word: "your goal", arti: "tujuan kamu" },
  { word: "his success", arti: "kesuksesannya (laki-laki)" },
  { word: "her failure", arti: "kegagalan dia (perempuan)" },
  { word: "its function", arti: "fungsinya (benda/hewan)" },
  { word: "our culture", arti: "budaya kami" },
  { word: "their language", arti: "bahasa mereka" },
  { word: "my future", arti: "masa depan saya" },
  { word: "your past", arti: "masa lalu kamu" }
];
