window.loadedQuestions = [
  { word: "angry", arti: "marah" },
  { word: "happy", arti: "bahagia" },
  { word: "sad", arti: "sedih" },
  { word: "anxious", arti: "cemas" },
  { word: "nervous", arti: "gugup" },
  { word: "excited", arti: "bersemangat" },
  { word: "afraid", arti: "takut" },
  { word: "lonely", arti: "kesepian" },
  { word: "grateful", arti: "bersyukur" },
  { word: "hopeful", arti: "penuh harapan" },
  { word: "confused", arti: "bingung" },
  { word: "frustrated", arti: "frustrasi" },
  { word: "relaxed", arti: "santai" },
  { word: "bored", arti: "bosan" },
  { word: "ashamed", arti: "malu" },
  { word: "jealous", arti: "iri / cemburu" },
  { word: "proud", arti: "bangga" },
  { word: "guilty", arti: "bersalah" },
  { word: "embarrassed", arti: "malu" },
  { word: "inspired", arti: "terinspirasi" },
  { word: "loved", arti: "dicintai" },
  { word: "rejected", arti: "ditolak" },
  { word: "depressed", arti: "tertekan" },
  { word: "worried", arti: "khawatir" },
  { word: "shocked", arti: "terkejut" },
  { word: "surprised", arti: "terkejut" },
  { word: "curious", arti: "penasaran" },
  { word: "hopeful", arti: "berharap" },
  { word: "peaceful", arti: "tenang / damai" },
  { word: "resentful", arti: "kesal" },
  { word: "overwhelmed", arti: "kewalahan" },
  { word: "touched", arti: "tersentuh" },
  { word: "miserable", arti: "sangat sedih" },
  { word: "terrified", arti: "sangat takut" },
  { word: "content", arti: "puas" },
  { word: "thankful", arti: "bersyukur" },
  { word: "tense", arti: "tegang" },
  { word: "cheerful", arti: "ceria" },
  { word: "resentful", arti: "pendendam" },
  { word: "hurt", arti: "terluka" },
  { word: "sympathetic", arti: "simpati" },
  { word: "moody", arti: "murung" },
  { word: "insecure", arti: "tidak percaya diri" },
  { word: "grumpy", arti: "pemarah / rewel" },
  { word: "optimistic", arti: "optimis" },
  { word: "pessimistic", arti: "pesimis" },
  { word: "fearful", arti: "penuh ketakutan" },
  { word: "hopeless", arti: "putus asa" },
  { word: "joyful", arti: "penuh sukacita" }
];
