window.loadedQuestions = [
  { word: "what", arti: "apa" },
  { word: "which", arti: "yang mana" },
  { word: "whose", arti: "milik siapa" },
  { word: "what color", arti: "warna apa" },
  { word: "what size", arti: "ukuran apa" },
  { word: "what time", arti: "jam berapa" },
  { word: "what day", arti: "hari apa" },
  { word: "what kind", arti: "jenis apa" },
  { word: "what type", arti: "tipe apa" },
  { word: "what subject", arti: "mata pelajaran apa" },
  { word: "what reason", arti: "alasan apa" },
  { word: "what book", arti: "buku apa" },
  { word: "what movie", arti: "film apa" },
  { word: "what food", arti: "makanan apa" },
  { word: "what song", arti: "lagu apa" },
  { word: "what language", arti: "bahasa apa" },
  { word: "what answer", arti: "jawaban apa" },
  { word: "what question", arti: "pertanyaan apa" },
  { word: "what result", arti: "hasil apa" },
  { word: "what topic", arti: "topik apa" },
  { word: "which book", arti: "buku yang mana" },
  { word: "which person", arti: "orang yang mana" },
  { word: "which way", arti: "jalan yang mana" },
  { word: "which class", arti: "kelas yang mana" },
  { word: "which option", arti: "opsi yang mana" },
  { word: "which team", arti: "tim yang mana" },
  { word: "which country", arti: "negara yang mana" },
  { word: "which movie", arti: "film yang mana" },
  { word: "which subject", arti: "mata pelajaran yang mana" },
  { word: "which color", arti: "warna yang mana" },
  { word: "which food", arti: "makanan yang mana" },
  { word: "whose bag", arti: "tas milik siapa" },
  { word: "whose pen", arti: "pena milik siapa" },
  { word: "whose idea", arti: "ide milik siapa" },
  { word: "whose phone", arti: "telepon milik siapa" },
  { word: "whose car", arti: "mobil milik siapa" },
  { word: "whose house", arti: "rumah milik siapa" },
  { word: "whose book", arti: "buku milik siapa" },
  { word: "whose shoes", arti: "sepatu milik siapa" },
  { word: "whose turn", arti: "giliran siapa" },
  { word: "whose name", arti: "nama siapa" },
  { word: "what kind of movie", arti: "jenis film apa" },
  { word: "what kind of food", arti: "jenis makanan apa" },
  { word: "what kind of music", arti: "jenis musik apa" },
  { word: "which one", arti: "yang mana (satu)" },
  { word: "which ones", arti: "yang mana (beberapa)" },
  { word: "what brand", arti: "merek apa" },
  { word: "what price", arti: "harga apa" },
  { word: "what game", arti: "permainan apa" }
];
