window.loadedQuestions = [
  { word: "some", arti: "beberapa" },
  { word: "many", arti: "banyak (benda jamak)" },
  { word: "much", arti: "banyak (benda tak terhitung)" },
  { word: "few", arti: "sedikit (benda jamak)" },
  { word: "little", arti: "sedikit (benda tak terhitung)" },
  { word: "several", arti: "beberapa" },
  { word: "all", arti: "semua" },
  { word: "any", arti: "apa saja / beberapa" },
  { word: "no", arti: "tidak ada" },
  { word: "each", arti: "masing-masing" },
  { word: "every", arti: "setiap" },
  { word: "either", arti: "salah satu (dari dua)" },
  { word: "neither", arti: "tidak satu pun (dari dua)" },
  { word: "enough", arti: "cukup" },
  { word: "most", arti: "kebanyakan" },
  { word: "half", arti: "setengah" },
  { word: "whole", arti: "seluruh" },
  { word: "plenty of", arti: "banyak sekali" },
  { word: "a lot of", arti: "banyak" },
  { word: "a few", arti: "beberapa (positif)" },
  { word: "a little", arti: "sedikit (positif)" },
  { word: "lots of", arti: "banyak" },
  { word: "dozens of", arti: "lusinan" },
  { word: "scores of", arti: "puluhan" },
  { word: "hundreds of", arti: "ratusan" },
  { word: "thousands of", arti: "ribuan" },
  { word: "millions of", arti: "jutaan" },
  { word: "various", arti: "bermacam-macam" },
  { word: "numerous", arti: "tak terhitung jumlahnya" },
  { word: "countless", arti: "tidak terhitung" },
  { word: "adequate", arti: "cukup/memadai" },
  { word: "insufficient", arti: "tidak cukup" },
  { word: "abundant", arti: "berlimpah" },
  { word: "minimal", arti: "sedikit sekali" },
  { word: "maximum", arti: "maksimal" },
  { word: "ample", arti: "cukup besar" },
  { word: "double", arti: "dua kali lipat" },
  { word: "triple", arti: "tiga kali lipat" },
  { word: "multiple", arti: "ganda/berlipat" },
  { word: "single", arti: "satu/tunggal" },
  { word: "no less than", arti: "tidak kurang dari" },
  { word: "only", arti: "hanya" },
  { word: "just", arti: "hanya/tepat" },
  { word: "one-third", arti: "sepertiga" },
  { word: "two-thirds", arti: "dua pertiga" },
  { word: "somewhat", arti: "agak" },
  { word: "barely", arti: "hampir tidak" },
  { word: "approximately", arti: "sekitar" },
  { word: "about", arti: "sekitar" }
];
