window.loadedQuestions = [
  { word: "beautiful", arti: "cantik" },
  { word: "strong", arti: "kuat" },
  { word: "happy", arti: "bahagia" },
  { word: "angry", arti: "marah" },
  { word: "brave", arti: "berani" },
  { word: "tall", arti: "tinggi" },
  { word: "short", arti: "pendek" },
  { word: "fat", arti: "gemuk" },
  { word: "thin", arti: "kurus" },
  { word: "young", arti: "muda" },
  { word: "old", arti: "tua" },
  { word: "clean", arti: "bersih" },
  { word: "dirty", arti: "kotor" },
  { word: "rich", arti: "kaya" },
  { word: "poor", arti: "miskin" },
  { word: "clever", arti: "cerdas" },
  { word: "stupid", arti: "bodoh" },
  { word: "kind", arti: "baik hati" },
  { word: "cruel", arti: "kejam" },
  { word: "friendly", arti: "ramah" },
  { word: "mean", arti: "pelit" },
  { word: "polite", arti: "sopan" },
  { word: "rude", arti: "kasar" },
  { word: "honest", arti: "jujur" },
  { word: "dishonest", arti: "tidak jujur" },
  { word: "funny", arti: "lucu" },
  { word: "boring", arti: "membosankan" },
  { word: "interesting", arti: "menarik" },
  { word: "exciting", arti: "menyenangkan" },
  { word: "lazy", arti: "malas" },
  { word: "hardworking", arti: "rajin" },
  { word: "quiet", arti: "pendiam" },
  { word: "noisy", arti: "berisik" },
  { word: "calm", arti: "tenang" },
  { word: "nervous", arti: "gugup" },
  { word: "confident", arti: "percaya diri" },
  { word: "shy", arti: "pemalu" },
  { word: "fast", arti: "cepat" },
  { word: "slow", arti: "lambat" },
  { word: "cold", arti: "dingin" },
  { word: "hot", arti: "panas" },
  { word: "wet", arti: "basah" },
  { word: "dry", arti: "kering" },
  { word: "soft", arti: "lembut" },
  { word: "hard", arti: "keras" },
  { word: "sweet", arti: "manis" },
  { word: "bitter", arti: "pahit" },
  { word: "sour", arti: "asam" },
  { word: "salty", arti: "asin" },
  { word: "cute", arti: "imut" }
];
