window.loadedQuestions = [
  { word: "one", arti: "satu" },
  { word: "two", arti: "dua" },
  { word: "three", arti: "tiga" },
  { word: "four", arti: "empat" },
  { word: "five", arti: "lima" },
  { word: "six", arti: "enam" },
  { word: "seven", arti: "tujuh" },
  { word: "eight", arti: "delapan" },
  { word: "nine", arti: "sembilan" },
  { word: "ten", arti: "sepuluh" },
  { word: "eleven", arti: "sebelas" },
  { word: "twelve", arti: "dua belas" },
  { word: "thirteen", arti: "tiga belas" },
  { word: "fourteen", arti: "empat belas" },
  { word: "fifteen", arti: "lima belas" },
  { word: "sixteen", arti: "enam belas" },
  { word: "seventeen", arti: "tujuh belas" },
  { word: "eighteen", arti: "delapan belas" },
  { word: "nineteen", arti: "sembilan belas" },
  { word: "twenty", arti: "dua puluh" },
  { word: "first", arti: "pertama" },
  { word: "second", arti: "kedua" },
  { word: "third", arti: "ketiga" },
  { word: "fourth", arti: "keempat" },
  { word: "fifth", arti: "kelima" },
  { word: "sixth", arti: "keenam" },
  { word: "seventh", arti: "ketujuh" },
  { word: "eighth", arti: "kedelapan" },
  { word: "ninth", arti: "kesembilan" },
  { word: "tenth", arti: "kesepuluh" },
  { word: "eleventh", arti: "kesebelas" },
  { word: "twelfth", arti: "keduabelas" },
  { word: "last", arti: "terakhir" },
  { word: "next", arti: "berikutnya" },
  { word: "single", arti: "satu" },
  { word: "double", arti: "dua kali lipat" },
  { word: "triple", arti: "tiga kali lipat" },
  { word: "quadruple", arti: "empat kali lipat" },
  { word: "half", arti: "setengah" },
  { word: "quarter", arti: "seperempat" },
  { word: "dozen", arti: "lusin" },
  { word: "hundred", arti: "seratus" },
  { word: "thousand", arti: "seribu" },
  { word: "million", arti: "satu juta" },
  { word: "twenty-one", arti: "dua puluh satu" },
  { word: "thirty", arti: "tiga puluh" },
  { word: "forty", arti: "empat puluh" },
  { word: "fifty", arti: "lima puluh" },
  { word: "sixty", arti: "enam puluh" }
];
